CODE    SEGMENT PARA PUBLIC 'CODE'      ;AN000;segment for near routine
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
        PUBLIC  _MAIN
_MAIN   PROC    FAR
        RET
_MAIN   ENDP
                                        ;
        PUBLIC  INDBC
INDBC   PROC    FAR
        RET
INDBC   ENDP
                                        ;
        PUBLIC  BOXDR
BOXDR   PROC    FAR
        RET
BOXDR   ENDP
                                        ;
        PUBLIC  GRAPH
GRAPH   PROC    FAR
        RET
GRAPH   ENDP
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CODE    ENDS
        END

