BIOS_DIR := $(SRC)/BIOS
BIOS_OUT := $(BIOS_DIR)/IO.SYS

bios: $(BIOS_OUT) $(BIOS_DIR)/SYSMENU.OVL

BIOS_AINC := -I. -ID:\\TOOLS\\INC -I..\\INC

$(BIOS_DIR)/MSBIO.CL1: $(BIOS_DIR)/MSBIO.SKL $(MESSAGES_OUT) $(NOSRVBLD) $(MESSAGE_CATALOG)
	cd $(BIOS_DIR) && $(NOSRVBLD) MSBIO.SKL "..\MESSAGES\USA-MS.MSG"

$(BIOS_DIR)/MSBIO.CL2 $(BIOS_DIR)/MSBIO.CL3 \
$(BIOS_DIR)/MSBIO.CL4 $(BIOS_DIR)/MSBIO.CL5: $(BIOS_DIR)/MSBIO.CL1

$(BIOS_DIR)/MSBIO1.OBJ: $(BIOS_DIR)/MSBIO1.ASM $(BIOS_DIR)/MSBDATA.INC $(BIOS_DIR)/DEVTABLE.INC \
    $(BIOS_DIR)/MSIOLDAT.INC $(BIOS_DIR)/MSIOLIM.INC $(BIOS_DIR)/MSBSEG.INC \
    $(BIOS_DIR)/HIGHDEV.INC $(BIOS_DIR)/LOWINT.INC $(BIOS_DIR)/LOWBIND.INC \
    $(BIOS_DIR)/HIGHROM.INC $(BIOS_DIR)/HIGHCHARROM.INC $(BIOS_DIR)/DISPATCH.INC $(BIOS_DIR)/COMPLETE.INC
	cd $(BIOS_DIR) && $(MASM) "$(AFLAGS) $(BIOS_AINC)" "MSBIO1.ASM,MSBIO1.OBJ;"

$(BIOS_DIR)/MSCON.OBJ: $(BIOS_DIR)/MSCON.ASM $(BIOS_DIR)/CHARSEG.INC
	cd $(BIOS_DIR) && $(MASM) "$(AFLAGS) $(BIOS_AINC)" "MSCON.ASM,MSCON.OBJ;"

$(BIOS_DIR)/MSAUX.OBJ: $(BIOS_DIR)/MSAUX.ASM $(BIOS_DIR)/CHARSEG.INC
	cd $(BIOS_DIR) && $(MASM) "$(AFLAGS) $(BIOS_AINC)" "MSAUX.ASM,MSAUX.OBJ;"

$(BIOS_DIR)/MSLPT.OBJ: $(BIOS_DIR)/MSLPT.ASM $(BIOS_DIR)/CHARSEG.INC
	cd $(BIOS_DIR) && $(MASM) "$(AFLAGS) $(BIOS_AINC)" "MSLPT.ASM,MSLPT.OBJ;"

$(BIOS_DIR)/MSCLOCK.OBJ: $(BIOS_DIR)/MSCLOCK.ASM $(BIOS_DIR)/CHARSEG.INC
	cd $(BIOS_DIR) && $(MASM) "$(AFLAGS) $(BIOS_AINC)" "MSCLOCK.ASM,MSCLOCK.OBJ;"

$(BIOS_DIR)/MSDISK.OBJ: $(BIOS_DIR)/MSDISK.ASM $(BIOS_DIR)/MSDSKHIG.INC \
    $(BIOS_DIR)/MSIOCTL.INC $(BIOS_DIR)/MSBSEG.INC $(BIOS_DIR)/MSIOLIM.INC \
    $(BIOS_DIR)/HIGHNEAR.INC
	cd $(BIOS_DIR) && $(MASM) "$(AFLAGS) $(BIOS_AINC)" "MSDISK.ASM,MSDISK.OBJ;"

$(BIOS_DIR)/MSBIO2.OBJ: $(BIOS_DIR)/MSBIO2.ASM $(BIOS_DIR)/MSBIO.CL2 \
    $(BIOS_DIR)/MS96TPI.INC $(BIOS_DIR)/MSCHKRSL.INC $(BIOS_DIR)/MSBSEG.INC
	cd $(BIOS_DIR) && $(MASM) "$(AFLAGS) $(BIOS_AINC)" "MSBIO2.ASM,MSBIO2.OBJ;"

$(BIOS_DIR)/MSHARD.OBJ: $(BIOS_DIR)/MSHARD.ASM
	cd $(BIOS_DIR) && $(MASM) "$(AFLAGS) $(BIOS_AINC)" "MSHARD.ASM,MSHARD.OBJ;"

$(BIOS_DIR)/MSINIT.OBJ: $(BIOS_DIR)/MSINIT.ASM
	cd $(BIOS_DIR) && $(MASM) "$(AFLAGS) $(BIOS_AINC)" "MSINIT.ASM,MSINIT.OBJ;"

$(BIOS_DIR)/DOSCOPY.INC: $(DOS_DIR)/MSDOS.SYS tools/gen_dos_copy_size.py
	python3 tools/gen_dos_copy_size.py $< $@

$(BIOS_DIR)/SYSINIT1.OBJ: $(BIOS_DIR)/SYSINIT1.ASM $(BIOS_DIR)/HMAPLAN.INC $(BIOS_DIR)/TABLEUMB.INC $(BIOS_DIR)/DOSCOPY.INC \
    $(BIOS_DIR)/MSBIO.CL4 $(BIOS_DIR)/MSBIO.CL5
	cd $(BIOS_DIR) && $(MASM) "$(AFLAGS) $(BIOS_AINC)" "SYSINIT1.ASM,SYSINIT1.OBJ;"

$(BIOS_DIR)/SYSCONF.OBJ: $(BIOS_DIR)/SYSCONF.ASM $(BIOS_DIR)/BOOTBIOS.INC $(SRC)/INC/BOOTPROV.INC
	cd $(BIOS_DIR) && $(MASM) "$(AFLAGS) $(BIOS_AINC)" "SYSCONF.ASM,SYSCONF.OBJ;"

$(BIOS_DIR)/SYSINIT2.OBJ: $(BIOS_DIR)/SYSINIT2.ASM
	cd $(BIOS_DIR) && $(MASM) "$(AFLAGS) $(BIOS_AINC)" "SYSINIT2.ASM,SYSINIT2.OBJ;"

$(BIOS_DIR)/SYSIMES.OBJ: $(BIOS_DIR)/SYSIMES.ASM $(BIOS_DIR)/MSBIO.CL3
	cd $(BIOS_DIR) && $(MASM) "$(AFLAGS) $(BIOS_AINC)" "SYSIMES.ASM,SYSIMES.OBJ;"

$(BIOS_DIR)/MSLOAD.OBJ: $(BIOS_DIR)/MSLOAD.ASM $(BIOS_DIR)/MSBIO.CL1 \
    $(INC_DIR)/VERSIONA.INC
	cd $(BIOS_DIR) && $(MASM) "$(AFLAGS) $(BIOS_AINC)" "MSLOAD.ASM,MSLOAD.OBJ;"

$(BIOS_DIR)/MSLOAD.EXE: $(BIOS_DIR)/MSLOAD.OBJ
	cd $(BIOS_DIR) && $(WLINK) "MSLOAD.OBJ,MSLOAD,,;"

$(BIOS_DIR)/MSLOAD.COM: $(BIOS_DIR)/MSLOAD.EXE
	cd $(BIOS_DIR) && $(EXE2BIN) "MSLOAD.EXE MSLOAD.COM"

$(BIOS_DIR)/SYSMENU.OVL: $(BIOS_DIR)/SYSMENU.ASM
	nasm -f bin $< -o $@

BIOS_OBJS := MSBIO1.OBJ MSCON.OBJ MSAUX.OBJ MSLPT.OBJ MSCLOCK.OBJ MSDISK.OBJ \
             MSBIO2.OBJ MSHARD.OBJ MSINIT.OBJ SYSINIT1.OBJ SYSCONF.OBJ \
             SYSINIT2.OBJ SYSIMES.OBJ
BIOS_OBJ_PATHS := $(addprefix $(BIOS_DIR)/,$(BIOS_OBJS))

$(BIOS_DIR)/MSBIO.EXE: $(BIOS_OBJ_PATHS)
	cd $(BIOS_DIR) && $(WLINK) "@MSBIO.LNK"

$(BIOS_DIR)/MSBIO.BIN: $(BIOS_DIR)/MSBIO.EXE
	cd $(BIOS_DIR) && $(EXE2BIN) "MSBIO.EXE MSBIO.BIN" <LOCSCR

$(BIOS_OUT): $(BIOS_DIR)/MSLOAD.COM $(BIOS_DIR)/MSBIO.BIN
	cat $(BIOS_DIR)/MSLOAD.COM $(BIOS_DIR)/MSBIO.BIN > $(BIOS_OUT)
