# ---------------------------------------------------------------------------
# CMD (command.com + utilities)
# ---------------------------------------------------------------------------
CMD_DIR  := $(SRC)/CMD
COMMAND_DIR := $(CMD_DIR)/COMMAND
COMMAND_OUT := $(COMMAND_DIR)/COMMAND.COM

SYS_DIR    := $(CMD_DIR)/SYS
SYS_OUT    := $(SYS_DIR)/SYS.COM

FORMAT_DIR := $(CMD_DIR)/FORMAT
FORMAT_OUT := $(FORMAT_DIR)/FORMAT.COM

CHKDSK_DIR := $(CMD_DIR)/CHKDSK
CHKDSK_OUT := $(CHKDSK_DIR)/CHKDSK.COM

DEBUG_DIR  := $(CMD_DIR)/DEBUG
DEBUG_OUT  := $(DEBUG_DIR)/DEBUG.COM

MEM_DIR    := $(CMD_DIR)/MEM
MEM_OUT    := $(MEM_DIR)/MEM.EXE

FDISK_DIR  := $(CMD_DIR)/FDISK
FDISK_OUT  := $(FDISK_DIR)/FDISK.EXE

MORE_DIR   := $(CMD_DIR)/MORE
MORE_OUT   := $(MORE_DIR)/MORE.COM

SORT_DIR   := $(CMD_DIR)/SORT
SORT_OUT   := $(SORT_DIR)/SORT.EXE

LABEL_DIR  := $(CMD_DIR)/LABEL
LABEL_OUT  := $(LABEL_DIR)/LABEL.COM

FIND_DIR   := $(CMD_DIR)/FIND
FIND_OUT   := $(FIND_DIR)/FIND.EXE

TREE_DIR   := $(CMD_DIR)/TREE
TREE_OUT   := $(TREE_DIR)/TREE.COM

COMP_DIR   := $(CMD_DIR)/COMP
COMP_OUT   := $(COMP_DIR)/COMP.COM

ATTRIB_DIR := $(CMD_DIR)/ATTRIB
ATTRIB_OUT := $(ATTRIB_DIR)/ATTRIB.EXE

EDLIN_DIR  := $(CMD_DIR)/EDLIN
EDLIN_OUT  := $(EDLIN_DIR)/EDLIN.COM

FC_DIR     := $(CMD_DIR)/FC
FC_OUT     := $(FC_DIR)/FC.EXE

cmd: $(COMMAND_OUT) $(SYS_OUT) $(FORMAT_OUT) $(CHKDSK_OUT) $(DEBUG_OUT) \
     $(MEM_OUT) $(FDISK_OUT) \
     $(MORE_OUT) $(SORT_OUT) $(LABEL_OUT) $(FIND_OUT) $(TREE_OUT) $(COMP_OUT) \
     $(ATTRIB_OUT) $(EDLIN_OUT) $(FC_OUT)

# COMMAND include paths (two levels up from CMD/COMMAND/)
COMMAND_AINC := -I. -ID:\\TOOLS\\INC -I..\\..\\INC -I..\\..\\DOS

# ---------------------------------------------------------------------------
# Step 1: BUILDMSG generates COMMAND.CTL + COMMAND.CL[1-4,A-F]
# ---------------------------------------------------------------------------
$(COMMAND_DIR)/COMMAND.CTL: $(COMMAND_DIR)/COMMAND.SKL $(MESSAGES_OUT)
	cd $(COMMAND_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" COMMAND.SKL

# All CL files are side-effects of the same BUILDMSG run
$(COMMAND_DIR)/COMMAND.CL1 $(COMMAND_DIR)/COMMAND.CL2 \
$(COMMAND_DIR)/COMMAND.CL3 $(COMMAND_DIR)/COMMAND.CL4 \
$(COMMAND_DIR)/COMMAND.CLA $(COMMAND_DIR)/COMMAND.CLB \
$(COMMAND_DIR)/COMMAND.CLC $(COMMAND_DIR)/COMMAND.CLD \
$(COMMAND_DIR)/COMMAND.CLE $(COMMAND_DIR)/COMMAND.CLF: \
    $(COMMAND_DIR)/COMMAND.CTL

# ---------------------------------------------------------------------------
# Step 2: Assemble COMMAND objects
# ---------------------------------------------------------------------------
$(COMMAND_DIR)/COMMAND1.OBJ: $(COMMAND_DIR)/COMMAND1.ASM \
    $(COMMAND_DIR)/COMMAND.CTL
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "COMMAND1.ASM,COMMAND1.OBJ;"

$(COMMAND_DIR)/COMMAND2.OBJ: $(COMMAND_DIR)/COMMAND2.ASM \
    $(COMMAND_DIR)/COMMAND.CTL
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "COMMAND2.ASM,COMMAND2.OBJ;"

$(COMMAND_DIR)/RUCODE.OBJ: $(COMMAND_DIR)/RUCODE.ASM \
    $(COMMAND_DIR)/COMMAND.CTL
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "RUCODE.ASM,RUCODE.OBJ;"

$(COMMAND_DIR)/RDATA.OBJ: $(COMMAND_DIR)/RDATA.ASM \
    $(COMMAND_DIR)/COMMAND.CLA $(COMMAND_DIR)/COMMAND.CL3 \
    $(COMMAND_DIR)/COMMAND.CL4 $(COMMAND_DIR)/COMMAND.CLD \
    $(COMMAND_DIR)/COMMAND.CLC $(COMMAND_DIR)/COMMAND.CLE \
    $(COMMAND_DIR)/COMMAND.CTL
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "RDATA.ASM,RDATA.OBJ;"

$(COMMAND_DIR)/INIT.OBJ: $(COMMAND_DIR)/INIT.ASM \
    $(COMMAND_DIR)/COMMAND.CTL
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "INIT.ASM,INIT.OBJ;"

$(COMMAND_DIR)/IPARSE.OBJ: $(COMMAND_DIR)/IPARSE.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "IPARSE.ASM,IPARSE.OBJ;"

$(COMMAND_DIR)/UINIT.OBJ: $(COMMAND_DIR)/UINIT.ASM \
    $(COMMAND_DIR)/COMMAND.CLB $(COMMAND_DIR)/COMMAND.CTL
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "UINIT.ASM,UINIT.OBJ;"

$(COMMAND_DIR)/TCODE.OBJ: $(COMMAND_DIR)/TCODE.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TCODE.ASM,TCODE.OBJ;"

$(COMMAND_DIR)/TBATCH.OBJ: $(COMMAND_DIR)/TBATCH.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TBATCH.ASM,TBATCH.OBJ;"

$(COMMAND_DIR)/TBATCH2.OBJ: $(COMMAND_DIR)/TBATCH2.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TBATCH2.ASM,TBATCH2.OBJ;"

$(COMMAND_DIR)/TFOR.OBJ: $(COMMAND_DIR)/TFOR.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TFOR.ASM,TFOR.OBJ;"

$(COMMAND_DIR)/TCMD1A.OBJ: $(COMMAND_DIR)/TCMD1A.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TCMD1A.ASM,TCMD1A.OBJ;"

$(COMMAND_DIR)/TCMD1B.OBJ: $(COMMAND_DIR)/TCMD1B.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TCMD1B.ASM,TCMD1B.OBJ;"

$(COMMAND_DIR)/TCMD2A.OBJ: $(COMMAND_DIR)/TCMD2A.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TCMD2A.ASM,TCMD2A.OBJ;"

$(COMMAND_DIR)/TCMD2B.OBJ: $(COMMAND_DIR)/TCMD2B.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TCMD2B.ASM,TCMD2B.OBJ;"

$(COMMAND_DIR)/TENV.OBJ: $(COMMAND_DIR)/TENV.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TENV.ASM,TENV.OBJ;"

$(COMMAND_DIR)/TENV2.OBJ: $(COMMAND_DIR)/TENV2.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TENV2.ASM,TENV2.OBJ;"

$(COMMAND_DIR)/TMISC1.OBJ: $(COMMAND_DIR)/TMISC1.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TMISC1.ASM,TMISC1.OBJ;"

$(COMMAND_DIR)/TMISC2.OBJ: $(COMMAND_DIR)/TMISC2.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TMISC2.ASM,TMISC2.OBJ;"

$(COMMAND_DIR)/TPIPE.OBJ: $(COMMAND_DIR)/TPIPE.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TPIPE.ASM,TPIPE.OBJ;"

$(COMMAND_DIR)/PARSE2.OBJ: $(COMMAND_DIR)/PARSE2.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "PARSE2.ASM,PARSE2.OBJ;"

$(COMMAND_DIR)/PATH1.OBJ: $(COMMAND_DIR)/PATH1.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "PATH1.ASM,PATH1.OBJ;"

$(COMMAND_DIR)/PATH2.OBJ: $(COMMAND_DIR)/PATH2.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "PATH2.ASM,PATH2.OBJ;"

$(COMMAND_DIR)/TUCODE.OBJ: $(COMMAND_DIR)/TUCODE.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TUCODE.ASM,TUCODE.OBJ;"

$(COMMAND_DIR)/COPY.OBJ: $(COMMAND_DIR)/COPY.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "COPY.ASM,COPY.OBJ;"

$(COMMAND_DIR)/COPYPR1.OBJ: $(COMMAND_DIR)/COPYPR1.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "COPYPR1.ASM,COPYPR1.OBJ;"

$(COMMAND_DIR)/COPYPR2.OBJ: $(COMMAND_DIR)/COPYPR2.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "COPYPR2.ASM,COPYPR2.OBJ;"

$(COMMAND_DIR)/CPARSE.OBJ: $(COMMAND_DIR)/CPARSE.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "CPARSE.ASM,CPARSE.OBJ;"

$(COMMAND_DIR)/TPARSE.OBJ: $(COMMAND_DIR)/TPARSE.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TPARSE.ASM,TPARSE.OBJ;"

$(COMMAND_DIR)/TPRINTF.OBJ: $(COMMAND_DIR)/TPRINTF.ASM \
    $(COMMAND_DIR)/COMMAND.CTL
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TPRINTF.ASM,TPRINTF.OBJ;"

$(COMMAND_DIR)/TDATA.OBJ: $(COMMAND_DIR)/TDATA.ASM \
    $(COMMAND_DIR)/COMMAND.CLF $(COMMAND_DIR)/COMMAND.CL1 \
    $(COMMAND_DIR)/COMMAND.CL2 $(COMMAND_DIR)/COMMAND.CTL
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TDATA.ASM,TDATA.OBJ;"

$(COMMAND_DIR)/TSPC.OBJ: $(COMMAND_DIR)/TSPC.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TSPC.ASM,TSPC.OBJ;"

# ---------------------------------------------------------------------------
# Step 3: Link -> COMMAND.EXE -> EXE2BIN -> COMMAND.COM
# ---------------------------------------------------------------------------
COMMAND_OBJS := COMMAND1.OBJ COMMAND2.OBJ RUCODE.OBJ RDATA.OBJ INIT.OBJ \
    IPARSE.OBJ UINIT.OBJ TCODE.OBJ TBATCH.OBJ TBATCH2.OBJ TFOR.OBJ \
    TCMD1A.OBJ TCMD1B.OBJ TCMD2A.OBJ TCMD2B.OBJ TENV.OBJ TENV2.OBJ \
    TMISC1.OBJ TMISC2.OBJ TPIPE.OBJ PARSE2.OBJ PATH1.OBJ PATH2.OBJ \
    TUCODE.OBJ COPY.OBJ COPYPR1.OBJ COPYPR2.OBJ CPARSE.OBJ \
    TPARSE.OBJ TPRINTF.OBJ TDATA.OBJ TSPC.OBJ

COMMAND_OBJ_PATHS := $(addprefix $(COMMAND_DIR)/,$(COMMAND_OBJS))

$(COMMAND_DIR)/COMMAND.EXE: $(COMMAND_OBJ_PATHS)
	cd $(COMMAND_DIR) && $(LINK) "@COMMAND.LNK"

$(COMMAND_OUT): $(COMMAND_DIR)/COMMAND.EXE
	cd $(COMMAND_DIR) && $(EXE2BIN) "COMMAND.EXE COMMAND.COM"

# ---------------------------------------------------------------------------
# SYS (sys.com)
# ---------------------------------------------------------------------------
# Include paths: current dir (for SYSHDR.INC, generated SYSMSG.INC/CL*) + INC/
SYS_AINC := -I. -ID:\\TOOLS\\INC -I..\\..\\INC

# Step 1: BUILDMSG generates SYS.CTL + SYS.CL[1,2,A-D]
$(SYS_DIR)/SYS.CTL: $(SYS_DIR)/SYS.SKL $(MESSAGES_OUT)
	cd $(SYS_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" SYS.SKL

$(SYS_DIR)/SYS.CL1 $(SYS_DIR)/SYS.CL2 \
$(SYS_DIR)/SYS.CLA $(SYS_DIR)/SYS.CLB \
$(SYS_DIR)/SYS.CLC $(SYS_DIR)/SYS.CLD: \
    $(SYS_DIR)/SYS.CTL

# Step 2: Assemble objects
$(SYS_DIR)/SYS1.OBJ: $(SYS_DIR)/SYS1.ASM $(SYS_DIR)/SYS.CTL
	cd $(SYS_DIR) && $(MASM) "$(AFLAGS) $(SYS_AINC)" "SYS1.ASM,SYS1.OBJ;"

$(SYS_DIR)/SYS2.OBJ: $(SYS_DIR)/SYS2.ASM $(SYS_DIR)/SYS.CTL
	cd $(SYS_DIR) && $(MASM) "$(AFLAGS) $(SYS_AINC)" "SYS2.ASM,SYS2.OBJ;"

$(SYS_DIR)/SYSSR.OBJ: $(SYS_DIR)/SYSSR.ASM \
    $(SYS_DIR)/SYS.CTL $(SYS_DIR)/SYS.CL1 $(SYS_DIR)/SYS.CL2 \
    $(SYS_DIR)/SYS.CLA $(SYS_DIR)/SYS.CLB \
    $(SYS_DIR)/SYS.CLC $(SYS_DIR)/SYS.CLD
	cd $(SYS_DIR) && $(MASM) "$(AFLAGS) $(SYS_AINC)" "SYSSR.ASM,SYSSR.OBJ;"

# Step 3: Link -> SYS.EXE -> EXE2BIN -> SYS.COM
$(SYS_DIR)/SYS.EXE: $(SYS_DIR)/SYS1.OBJ $(SYS_DIR)/SYS2.OBJ $(SYS_DIR)/SYSSR.OBJ
	cd $(SYS_DIR) && $(LINK) "@SYS.LNK"

$(SYS_OUT): $(SYS_DIR)/SYS.EXE
	cd $(SYS_DIR) && $(EXE2BIN) "SYS.EXE SYS.COM"

# ---------------------------------------------------------------------------
# FORMAT (format.com)
# ---------------------------------------------------------------------------
# Uses CONVERT.EXE (not EXE2BIN) to produce COM from EXE.
# MSFOR.ASM includes BOOT.CL1 (from BOOT/) and BOOT11.INC (from INC/).
FORMAT_AINC := -I. -ID:\\TOOLS\\INC -I..\\..\\INC

# Step 1: BUILDMSG generates FORMAT.CTL + FORMAT.CL[1,A,B,C]
$(FORMAT_DIR)/FORMAT.CTL: $(FORMAT_DIR)/FORMAT.SKL $(MESSAGES_OUT)
	cd $(FORMAT_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" FORMAT.SKL

$(FORMAT_DIR)/FORMAT.CL1 $(FORMAT_DIR)/FORMAT.CLA \
$(FORMAT_DIR)/FORMAT.CLB $(FORMAT_DIR)/FORMAT.CLC: \
    $(FORMAT_DIR)/FORMAT.CTL

# Step 2: copy BOOT.CL1 to FORMAT dir (MSFOR.ASM: include BOOT.CL1)
$(FORMAT_DIR)/BOOT.CL1: $(SRC)/BOOT/BOOT.CL1
	cp $< $@

# Step 3: Assemble objects
$(FORMAT_DIR)/DISPLAY.OBJ: $(FORMAT_DIR)/DISPLAY.ASM $(FORMAT_DIR)/FORMAT.CTL
	cd $(FORMAT_DIR) && $(MASM) "$(AFLAGS) $(FORMAT_AINC)" "DISPLAY.ASM,DISPLAY.OBJ;"

$(FORMAT_DIR)/FORINIT.OBJ: $(FORMAT_DIR)/FORINIT.ASM $(FORMAT_DIR)/FORMAT.CTL
	cd $(FORMAT_DIR) && $(MASM) "$(AFLAGS) $(FORMAT_AINC)" "FORINIT.ASM,FORINIT.OBJ;"

$(FORMAT_DIR)/FORLABEL.OBJ: $(FORMAT_DIR)/FORLABEL.ASM $(FORMAT_DIR)/FORMAT.CTL
	cd $(FORMAT_DIR) && $(MASM) "$(AFLAGS) $(FORMAT_AINC)" "FORLABEL.ASM,FORLABEL.OBJ;"

$(FORMAT_DIR)/FORMAT.OBJ: $(FORMAT_DIR)/FORMAT.ASM $(FORMAT_DIR)/FORMAT.CTL
	cd $(FORMAT_DIR) && $(MASM) "$(AFLAGS) $(FORMAT_AINC)" "FORMAT.ASM,FORMAT.OBJ;"

$(FORMAT_DIR)/FORPROC.OBJ: $(FORMAT_DIR)/FORPROC.ASM $(FORMAT_DIR)/FORMAT.CTL
	cd $(FORMAT_DIR) && $(MASM) "$(AFLAGS) $(FORMAT_AINC)" "FORPROC.ASM,FORPROC.OBJ;"

$(FORMAT_DIR)/MSFOR.OBJ: $(FORMAT_DIR)/MSFOR.ASM $(FORMAT_DIR)/FORMAT.CTL \
    $(FORMAT_DIR)/BOOT.CL1
	cd $(FORMAT_DIR) && $(MASM) "$(AFLAGS) $(FORMAT_AINC)" "MSFOR.ASM,MSFOR.OBJ;"

$(FORMAT_DIR)/FOREXEC.OBJ: $(FORMAT_DIR)/FOREXEC.ASM
	cd $(FORMAT_DIR) && $(MASM) "$(AFLAGS) $(FORMAT_AINC)" "FOREXEC.ASM,FOREXEC.OBJ;"

# Step 4: Link → FORMAT.EXE; Step 5: CONVERT → FORMAT.COM
FORMAT_OBJS := $(addprefix $(FORMAT_DIR)/,\
    DISPLAY.OBJ FORINIT.OBJ FORLABEL.OBJ FORMAT.OBJ \
    FORPROC.OBJ MSFOR.OBJ FOREXEC.OBJ)

$(FORMAT_DIR)/FORMAT.EXE: $(FORMAT_OBJS)
	cd $(FORMAT_DIR) && $(LINK) "@FORMAT.LNK"

$(FORMAT_OUT): $(FORMAT_DIR)/FORMAT.EXE
	cd $(FORMAT_DIR) && $(CONVERT) "FORMAT.EXE"

# ---------------------------------------------------------------------------
# CHKDSK (chkdsk.com)
# ---------------------------------------------------------------------------
# SKL defines classes A,B,C,D only; CHKDISP.ASM's Msg_Services macro also
# INCLUDEs CL1 and CL2, so we touch empty stubs for those after BUILDMSG.
CHKDSK_AINC := -I. -ID:\\TOOLS\\INC -I..\\..\\INC

# Step 1: BUILDMSG generates CHKDSK.CTL + CHKDSK.CL[A,B,C,D]
# Also touch empty CL1/CL2 stubs (Msg_Services INCLUDEs them but SKL has no class 1/2)
$(CHKDSK_DIR)/CHKDSK.CTL: $(CHKDSK_DIR)/CHKDSK.SKL $(MESSAGES_OUT)
	cd $(CHKDSK_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" CHKDSK.SKL
	touch $(CHKDSK_DIR)/CHKDSK.CL1 $(CHKDSK_DIR)/CHKDSK.CL2

$(CHKDSK_DIR)/CHKDSK.CLA $(CHKDSK_DIR)/CHKDSK.CLB \
$(CHKDSK_DIR)/CHKDSK.CLC $(CHKDSK_DIR)/CHKDSK.CLD \
$(CHKDSK_DIR)/CHKDSK.CL1 $(CHKDSK_DIR)/CHKDSK.CL2: \
    $(CHKDSK_DIR)/CHKDSK.CTL

# Step 2: Assemble objects
# Most objects don't include CTL/CL files directly; only CHKDISP does (via Msg_Services).
$(CHKDSK_DIR)/CHKDISK.OBJ: $(CHKDSK_DIR)/CHKDISK.ASM
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKDISK.ASM,CHKDISK.OBJ;"

$(CHKDSK_DIR)/CHKDISP.OBJ: $(CHKDSK_DIR)/CHKDISP.ASM \
    $(CHKDSK_DIR)/CHKDSK.CTL \
    $(CHKDSK_DIR)/CHKDSK.CLA $(CHKDSK_DIR)/CHKDSK.CLB \
    $(CHKDSK_DIR)/CHKDSK.CLC $(CHKDSK_DIR)/CHKDSK.CLD \
    $(CHKDSK_DIR)/CHKDSK.CL1 $(CHKDSK_DIR)/CHKDSK.CL2
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKDISP.ASM,CHKDISP.OBJ;"

$(CHKDSK_DIR)/CHKDSK1.OBJ: $(CHKDSK_DIR)/CHKDSK1.ASM
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKDSK1.ASM,CHKDSK1.OBJ;"

$(CHKDSK_DIR)/CHKDSK2.OBJ: $(CHKDSK_DIR)/CHKDSK2.ASM
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKDSK2.ASM,CHKDSK2.OBJ;"

$(CHKDSK_DIR)/CHKFAT.OBJ: $(CHKDSK_DIR)/CHKFAT.ASM
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKFAT.ASM,CHKFAT.OBJ;"

$(CHKDSK_DIR)/CHKINIT.OBJ: $(CHKDSK_DIR)/CHKINIT.ASM
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKINIT.ASM,CHKINIT.OBJ;"

$(CHKDSK_DIR)/CHKPRMT.OBJ: $(CHKDSK_DIR)/CHKPRMT.ASM
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKPRMT.ASM,CHKPRMT.OBJ;"

$(CHKDSK_DIR)/CHKPROC2.OBJ: $(CHKDSK_DIR)/CHKPROC2.ASM
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKPROC2.ASM,CHKPROC2.OBJ;"

$(CHKDSK_DIR)/CHKPROC.OBJ: $(CHKDSK_DIR)/CHKPROC.ASM
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKPROC.ASM,CHKPROC.OBJ;"

# Step 3: Link → CHKDSK.EXE; Step 4: CONVERT → CHKDSK.COM
CHKDSK_OBJS := $(addprefix $(CHKDSK_DIR)/,\
    CHKDISK.OBJ CHKDISP.OBJ CHKDSK1.OBJ CHKDSK2.OBJ \
    CHKFAT.OBJ CHKINIT.OBJ CHKPRMT.OBJ CHKPROC2.OBJ CHKPROC.OBJ)

$(CHKDSK_DIR)/CHKDSK.EXE: $(CHKDSK_OBJS)
	cd $(CHKDSK_DIR) && $(LINK) "@CHKDSK.LNK"

$(CHKDSK_OUT): $(CHKDSK_DIR)/CHKDSK.EXE
	cd $(CHKDSK_DIR) && $(CONVERT) "CHKDSK.EXE"

# ---------------------------------------------------------------------------
# DEBUG (debug.com)
# ---------------------------------------------------------------------------
# BUILDMSG generates all CL files including CL1/CL2 (unlike CHKDSK, no stubs needed).
# Uses CONVERT.EXE (not EXE2BIN) to produce COM from EXE.
DEBUG_AINC := -I. -ID:\\TOOLS\\INC -I..\\..\\INC

# Step 1: BUILDMSG generates DEBUG.CTL + DEBUG.CL[1,2,A,B,C,D]
$(DEBUG_DIR)/DEBUG.CTL: $(DEBUG_DIR)/DEBUG.SKL $(MESSAGES_OUT)
	cd $(DEBUG_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" DEBUG.SKL

$(DEBUG_DIR)/DEBUG.CL1 $(DEBUG_DIR)/DEBUG.CL2 \
$(DEBUG_DIR)/DEBUG.CLA $(DEBUG_DIR)/DEBUG.CLB \
$(DEBUG_DIR)/DEBUG.CLC $(DEBUG_DIR)/DEBUG.CLD: \
    $(DEBUG_DIR)/DEBUG.CTL

# Step 2: Assemble objects
$(DEBUG_DIR)/DEBUG.OBJ: $(DEBUG_DIR)/DEBUG.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBUG.ASM,DEBUG.OBJ;"

$(DEBUG_DIR)/DEBCOM1.OBJ: $(DEBUG_DIR)/DEBCOM1.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBCOM1.ASM,DEBCOM1.OBJ;"

$(DEBUG_DIR)/DEBCOM2.OBJ: $(DEBUG_DIR)/DEBCOM2.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBCOM2.ASM,DEBCOM2.OBJ;"

$(DEBUG_DIR)/DEBCOM3.OBJ: $(DEBUG_DIR)/DEBCOM3.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBCOM3.ASM,DEBCOM3.OBJ;"

$(DEBUG_DIR)/DEBASM.OBJ: $(DEBUG_DIR)/DEBASM.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBASM.ASM,DEBASM.OBJ;"

$(DEBUG_DIR)/DEBUASM.OBJ: $(DEBUG_DIR)/DEBUASM.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBUASM.ASM,DEBUASM.OBJ;"

$(DEBUG_DIR)/DEBERR.OBJ: $(DEBUG_DIR)/DEBERR.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBERR.ASM,DEBERR.OBJ;"

$(DEBUG_DIR)/DEBCONST.OBJ: $(DEBUG_DIR)/DEBCONST.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBCONST.ASM,DEBCONST.OBJ;"

$(DEBUG_DIR)/DEBMES.OBJ: $(DEBUG_DIR)/DEBMES.ASM \
    $(DEBUG_DIR)/DEBUG.CTL \
    $(DEBUG_DIR)/DEBUG.CLA $(DEBUG_DIR)/DEBUG.CLB \
    $(DEBUG_DIR)/DEBUG.CLC $(DEBUG_DIR)/DEBUG.CLD \
    $(DEBUG_DIR)/DEBUG.CL1 $(DEBUG_DIR)/DEBUG.CL2
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBMES.ASM,DEBMES.OBJ;"

$(DEBUG_DIR)/DEBEMS.OBJ: $(DEBUG_DIR)/DEBEMS.ASM
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBEMS.ASM,DEBEMS.OBJ;"

$(DEBUG_DIR)/DEBDATA.OBJ: $(DEBUG_DIR)/DEBDATA.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBDATA.ASM,DEBDATA.OBJ;"

# Step 3: Link → DEBUG.EXE; Step 4: CONVERT → DEBUG.COM
DEBUG_OBJS := $(addprefix $(DEBUG_DIR)/,\
    DEBUG.OBJ DEBCOM1.OBJ DEBCOM2.OBJ DEBCOM3.OBJ \
    DEBASM.OBJ DEBUASM.OBJ DEBERR.OBJ DEBCONST.OBJ \
    DEBMES.OBJ DEBEMS.OBJ DEBDATA.OBJ)

$(DEBUG_DIR)/DEBUG.EXE: $(DEBUG_OBJS)
	cd $(DEBUG_DIR) && $(LINK) "@DEBUG.LNK"

$(DEBUG_OUT): $(DEBUG_DIR)/DEBUG.EXE
	cd $(DEBUG_DIR) && $(CONVERT) "DEBUG.EXE"

# ---------------------------------------------------------------------------
# MEM (mem.exe)
# ---------------------------------------------------------------------------
# C + 2 ASM files. Output is EXE (not COM) — no CONVERT needed.
# Links against src/LIB/MEM.LIB (pre-built small-model C runtime subset).
# Note: MEM.EXE checks for DOS 4.0 via sysloadmsg — won't run under kvikdos.
MEM_AINC := -I. -ID:\\TOOLS\\INC -I..\\..\\INC

# Step 1: BUILDMSG generates MEM.CTL + MEM.CL[1,2,A,B]
$(MEM_DIR)/MEM.CTL: $(MEM_DIR)/MEM.SKL $(MESSAGES_OUT)
	cd $(MEM_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" MEM.SKL

$(MEM_DIR)/MEM.CL1 $(MEM_DIR)/MEM.CL2 \
$(MEM_DIR)/MEM.CLA $(MEM_DIR)/MEM.CLB: \
    $(MEM_DIR)/MEM.CTL

# Step 2: Assemble _MSGRET.OBJ and _PARSE.OBJ
$(MEM_DIR)/_MSGRET.OBJ: $(MEM_DIR)/_MSGRET.ASM \
    $(MEM_DIR)/MEM.CTL \
    $(MEM_DIR)/MEM.CLA $(MEM_DIR)/MEM.CLB \
    $(MEM_DIR)/MEM.CL1 $(MEM_DIR)/MEM.CL2
	cd $(MEM_DIR) && $(MASM) "$(AFLAGS) $(MEM_AINC)" "_MSGRET.ASM,_MSGRET.OBJ;"

$(MEM_DIR)/_PARSE.OBJ: $(MEM_DIR)/_PARSE.ASM
	cd $(MEM_DIR) && $(MASM) "$(AFLAGS) $(MEM_AINC)" "_PARSE.ASM,_PARSE.OBJ;"

# Step 3: Compile MEM.C
$(MEM_DIR)/MEM.OBJ: $(MEM_DIR)/MEM.C $(MEM_DIR)/MEM.CTL
	cd $(MEM_DIR) && $(CL) "-AS -Os -Zp -I. -I..\\..\\H -c -FoMEM.OBJ MEM.C"

# Step 4: Link → MEM.EXE
$(MEM_OUT): $(MEM_DIR)/MEM.OBJ $(MEM_DIR)/_MSGRET.OBJ $(MEM_DIR)/_PARSE.OBJ
	cd $(MEM_DIR) && $(LINK) "MEM+_MSGRET+_PARSE,,,..\\..\\LIB\\MEM;"

# ---------------------------------------------------------------------------
# FDISK (fdisk.exe)
# ---------------------------------------------------------------------------
# Complex build: NOSRVBLD (FDISK5.SKL→CL1 already done for SELECT),
# BUILDMSG (FDISK.SKL→CTL+CL files), MENUBLD (FDISK.MSG→FDISKM.C),
# 20 C files, 4 ASM files, link against MAPPER.LIB + COMSUBS.LIB.
# FDBOOT.OBJ and FDBOOT.INC already built for SELECT — reused here.
FDISK_AINC := -I. -ID:\\TOOLS\\INC -I..\\..\\INC
FDISK_CFLAGS := -AS -Os -Zp -I. -I..\\..\\H -c

# Step 1: BUILDMSG → FDISK.CTL + FDISK.CL[1,2,A,B]
$(FDISK_DIR)/FDISK.CTL: $(FDISK_DIR)/FDISK.SKL $(MESSAGES_OUT)
	cd $(FDISK_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" FDISK.SKL

$(FDISK_DIR)/FDISK.CL1 $(FDISK_DIR)/FDISK.CL2 \
$(FDISK_DIR)/FDISK.CLA $(FDISK_DIR)/FDISK.CLB: \
    $(FDISK_DIR)/FDISK.CTL

# Step 2: MENUBLD → FDISKM.C
$(FDISK_DIR)/FDISKM.C: $(FDISK_DIR)/FDISK.MSG $(MESSAGES_OUT)
	cd $(FDISK_DIR) && $(MENUBLD) "FDISK.MSG ..\\..\\MESSAGES\\USA-MS.MSG"

# Step 3: Compile C objects
$(FDISK_DIR)/MAIN.OBJ: $(FDISK_DIR)/MAIN.C $(FDISK_DIR)/FDISK.CTL
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoMAIN.OBJ MAIN.C"

$(FDISK_DIR)/FDISK.OBJ: $(FDISK_DIR)/FDISK.C $(FDISK_DIR)/FDISK.CTL
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoFDISK.OBJ FDISK.C"

$(FDISK_DIR)/MAINMENU.OBJ: $(FDISK_DIR)/MAINMENU.C
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoMAINMENU.OBJ MAINMENU.C"

$(FDISK_DIR)/DISPLAY.OBJ: $(FDISK_DIR)/DISPLAY.C
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoDISPLAY.OBJ DISPLAY.C"

$(FDISK_DIR)/D_MENUS.OBJ: $(FDISK_DIR)/D_MENUS.C
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoD_MENUS.OBJ D_MENUS.C"

$(FDISK_DIR)/C_MENUS.OBJ: $(FDISK_DIR)/C_MENUS.C
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoC_MENUS.OBJ C_MENUS.C"

$(FDISK_DIR)/INPUT.OBJ: $(FDISK_DIR)/INPUT.C
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoINPUT.OBJ INPUT.C"

$(FDISK_DIR)/TDISPLAY.OBJ: $(FDISK_DIR)/TDISPLAY.C
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoTDISPLAY.OBJ TDISPLAY.C"

$(FDISK_DIR)/VDISPLAY.OBJ: $(FDISK_DIR)/VDISPLAY.C
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoVDISPLAY.OBJ VDISPLAY.C"

$(FDISK_DIR)/SPACE.OBJ: $(FDISK_DIR)/SPACE.C
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoSPACE.OBJ SPACE.C"

$(FDISK_DIR)/PARTINFO.OBJ: $(FDISK_DIR)/PARTINFO.C
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoPARTINFO.OBJ PARTINFO.C"

$(FDISK_DIR)/VIDEO.OBJ: $(FDISK_DIR)/VIDEO.C
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoVIDEO.OBJ VIDEO.C"

$(FDISK_DIR)/MAKEPART.OBJ: $(FDISK_DIR)/MAKEPART.C
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoMAKEPART.OBJ MAKEPART.C"

$(FDISK_DIR)/INT13.OBJ: $(FDISK_DIR)/INT13.C
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoINT13.OBJ INT13.C"

$(FDISK_DIR)/DISKOUT.OBJ: $(FDISK_DIR)/DISKOUT.C
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoDISKOUT.OBJ DISKOUT.C"

$(FDISK_DIR)/MESSAGES.OBJ: $(FDISK_DIR)/MESSAGES.C $(FDISK_DIR)/FDISK.CTL
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoMESSAGES.OBJ MESSAGES.C"

$(FDISK_DIR)/FDPARSE.OBJ: $(FDISK_DIR)/FDPARSE.C
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoFDPARSE.OBJ FDPARSE.C"

$(FDISK_DIR)/CONVERT.OBJ: $(FDISK_DIR)/CONVERT.C
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoCONVERT.OBJ CONVERT.C"

$(FDISK_DIR)/GLOBAL.OBJ: $(FDISK_DIR)/GLOBAL.C
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoGLOBAL.OBJ GLOBAL.C"

$(FDISK_DIR)/FDISKM.OBJ: $(FDISK_DIR)/FDISKM.C
	cd $(FDISK_DIR) && $(CL) "$(FDISK_CFLAGS) -FoFDISKM.OBJ FDISKM.C"

# Step 4: Assemble ASM objects
$(FDISK_DIR)/_MSGRET.OBJ: $(FDISK_DIR)/_MSGRET.ASM \
    $(FDISK_DIR)/FDISK.CTL \
    $(FDISK_DIR)/FDISK.CLA $(FDISK_DIR)/FDISK.CLB \
    $(FDISK_DIR)/FDISK.CL1 $(FDISK_DIR)/FDISK.CL2
	cd $(FDISK_DIR) && $(MASM) "$(AFLAGS) $(FDISK_AINC)" "_MSGRET.ASM,_MSGRET.OBJ;"

$(FDISK_DIR)/_PARSE.OBJ: $(FDISK_DIR)/_PARSE.ASM
	cd $(FDISK_DIR) && $(MASM) "$(AFLAGS) $(FDISK_AINC)" "_PARSE.ASM,_PARSE.OBJ;"

$(FDISK_DIR)/BOOTREC.OBJ: $(FDISK_DIR)/BOOTREC.ASM $(FDISK_DIR)/FDBOOT.INC
	cd $(FDISK_DIR) && $(MASM) "$(AFLAGS) $(FDISK_AINC)" "BOOTREC.ASM,BOOTREC.OBJ;"

$(FDISK_DIR)/REBOOT.OBJ: $(FDISK_DIR)/REBOOT.ASM
	cd $(FDISK_DIR) && $(MASM) "$(AFLAGS) $(FDISK_AINC)" "REBOOT.ASM,REBOOT.OBJ;"

# Step 5: Link → FDISK.EXE
FDISK_C_OBJS := $(addprefix $(FDISK_DIR)/,\
    MAIN.OBJ MAINMENU.OBJ D_MENUS.OBJ C_MENUS.OBJ FDISK.OBJ \
    DISPLAY.OBJ INPUT.OBJ TDISPLAY.OBJ VDISPLAY.OBJ SPACE.OBJ \
    PARTINFO.OBJ VIDEO.OBJ MAKEPART.OBJ INT13.OBJ DISKOUT.OBJ \
    MESSAGES.OBJ FDPARSE.OBJ CONVERT.OBJ GLOBAL.OBJ FDISKM.OBJ)
FDISK_ASM_OBJS := $(addprefix $(FDISK_DIR)/,\
    REBOOT.OBJ BOOTREC.OBJ FDBOOT.OBJ _PARSE.OBJ _MSGRET.OBJ)

$(FDISK_OUT): $(FDISK_C_OBJS) $(FDISK_ASM_OBJS) $(MAPPER_LIB)
	cd $(FDISK_DIR) && $(LINK) "@FDISK.LNK"

# ---------------------------------------------------------------------------
# MORE (more.com) — single ASM file, EXE2BIN
# ---------------------------------------------------------------------------
$(MORE_DIR)/MORE.CTL: $(MORE_DIR)/MORE.SKL $(MESSAGES_OUT)
	cd $(MORE_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" MORE.SKL

$(MORE_DIR)/MORE.OBJ: $(MORE_DIR)/MORE.ASM $(MORE_DIR)/MORE.CTL
	cd $(MORE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MORE.ASM,MORE.OBJ;"

$(MORE_DIR)/MORE.EXE: $(MORE_DIR)/MORE.OBJ
	cd $(MORE_DIR) && $(LINK) "@MORE.LNK"

$(MORE_OUT): $(MORE_DIR)/MORE.EXE
	cd $(MORE_DIR) && $(EXE2BIN) "MORE.EXE MORE.COM"

# ---------------------------------------------------------------------------
# SORT (sort.exe) — 2 ASM files, stays EXE
# ---------------------------------------------------------------------------
$(SORT_DIR)/SORT.CTL: $(SORT_DIR)/SORT.SKL $(MESSAGES_OUT)
	cd $(SORT_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" SORT.SKL

$(SORT_DIR)/SORT.OBJ: $(SORT_DIR)/SORT.ASM $(SORT_DIR)/SORT.CTL
	cd $(SORT_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "SORT.ASM,SORT.OBJ;"

$(SORT_DIR)/SORTMES.OBJ: $(SORT_DIR)/SORTMES.ASM $(SORT_DIR)/SORT.CTL
	cd $(SORT_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "SORTMES.ASM,SORTMES.OBJ;"

$(SORT_OUT): $(SORT_DIR)/SORT.OBJ $(SORT_DIR)/SORTMES.OBJ
	cd $(SORT_DIR) && $(LINK) "SORT+SORTMES,SORT.EXE;"

# ---------------------------------------------------------------------------
# LABEL (label.com) — 2 ASM files, EXE2BIN
# ---------------------------------------------------------------------------
$(LABEL_DIR)/LABL.CTL: $(LABEL_DIR)/LABL.SKL $(MESSAGES_OUT)
	cd $(LABEL_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" LABL.SKL

$(LABEL_DIR)/LABEL.OBJ: $(LABEL_DIR)/LABEL.ASM $(LABEL_DIR)/LABL.CTL
	cd $(LABEL_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "LABEL.ASM,LABEL.OBJ;"

$(LABEL_DIR)/LABELM.OBJ: $(LABEL_DIR)/LABELM.ASM $(LABEL_DIR)/LABL.CTL
	cd $(LABEL_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "LABELM.ASM,LABELM.OBJ;"

$(LABEL_DIR)/LABEL.EXE: $(LABEL_DIR)/LABEL.OBJ $(LABEL_DIR)/LABELM.OBJ
	cd $(LABEL_DIR) && $(LINK) "@LABEL.LNK"

$(LABEL_OUT): $(LABEL_DIR)/LABEL.EXE
	cd $(LABEL_DIR) && $(EXE2BIN) "LABEL.EXE LABEL.COM"

# ---------------------------------------------------------------------------
# FIND (find.exe) — 2 ASM files, stays EXE
# ---------------------------------------------------------------------------
$(FIND_DIR)/FIND.CTL: $(FIND_DIR)/FIND.SKL $(MESSAGES_OUT)
	cd $(FIND_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" FIND.SKL

$(FIND_DIR)/FIND.OBJ: $(FIND_DIR)/FIND.ASM $(FIND_DIR)/FIND.CTL
	cd $(FIND_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "FIND.ASM,FIND.OBJ;"

$(FIND_DIR)/FINDMES.OBJ: $(FIND_DIR)/FINDMES.ASM $(FIND_DIR)/FIND.CTL
	cd $(FIND_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "FINDMES.ASM,FINDMES.OBJ;"

$(FIND_OUT): $(FIND_DIR)/FIND.OBJ $(FIND_DIR)/FINDMES.OBJ
	cd $(FIND_DIR) && $(LINK) "FIND+FINDMES,FIND.EXE/EX;"

# ---------------------------------------------------------------------------
# TREE (tree.com) — 4 ASM files, EXE2BIN
# ---------------------------------------------------------------------------
$(TREE_DIR)/TREE.CTL: $(TREE_DIR)/TREE.SKL $(MESSAGES_OUT)
	cd $(TREE_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" TREE.SKL

$(TREE_DIR)/TREE.OBJ: $(TREE_DIR)/TREE.ASM $(TREE_DIR)/TREE.CTL
	cd $(TREE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "TREE.ASM,TREE.OBJ;"

$(TREE_DIR)/TREEPAR.OBJ: $(TREE_DIR)/TREEPAR.ASM
	cd $(TREE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "TREEPAR.ASM,TREEPAR.OBJ;"

$(TREE_DIR)/TREESYSP.OBJ: $(TREE_DIR)/TREESYSP.ASM $(TREE_DIR)/TREE.CTL
	cd $(TREE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "TREESYSP.ASM,TREESYSP.OBJ;"

$(TREE_DIR)/TREESYSM.OBJ: $(TREE_DIR)/TREESYSM.ASM $(TREE_DIR)/TREE.CTL
	cd $(TREE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "TREESYSM.ASM,TREESYSM.OBJ;"

$(TREE_DIR)/TREE.EXE: $(TREE_DIR)/TREE.OBJ $(TREE_DIR)/TREEPAR.OBJ \
    $(TREE_DIR)/TREESYSP.OBJ $(TREE_DIR)/TREESYSM.OBJ
	cd $(TREE_DIR) && $(LINK) "@TREE.LNK"

$(TREE_OUT): $(TREE_DIR)/TREE.EXE
	cd $(TREE_DIR) && $(EXE2BIN) "TREE.EXE TREE.COM"

# ---------------------------------------------------------------------------
# COMP (comp.com) — 5 ASM files, EXE2BIN
# ---------------------------------------------------------------------------
$(COMP_DIR)/COMP.CTL: $(COMP_DIR)/COMP.SKL $(MESSAGES_OUT)
	cd $(COMP_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" COMP.SKL

$(COMP_DIR)/COMP1.OBJ: $(COMP_DIR)/COMP1.ASM $(COMP_DIR)/COMP.CTL
	cd $(COMP_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "COMP1.ASM,COMP1.OBJ;"

$(COMP_DIR)/COMPPAR.OBJ: $(COMP_DIR)/COMPPAR.ASM
	cd $(COMP_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "COMPPAR.ASM,COMPPAR.OBJ;"

$(COMP_DIR)/COMPP.OBJ: $(COMP_DIR)/COMPP.ASM $(COMP_DIR)/COMP.CTL
	cd $(COMP_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "COMPP.ASM,COMPP.OBJ;"

$(COMP_DIR)/COMPSM.OBJ: $(COMP_DIR)/COMPSM.ASM $(COMP_DIR)/COMP.CTL
	cd $(COMP_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "COMPSM.ASM,COMPSM.OBJ;"

$(COMP_DIR)/COMP2.OBJ: $(COMP_DIR)/COMP2.ASM $(COMP_DIR)/COMP.CTL
	cd $(COMP_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "COMP2.ASM,COMP2.OBJ;"

$(COMP_DIR)/COMP.EXE: $(COMP_DIR)/COMP1.OBJ $(COMP_DIR)/COMPPAR.OBJ \
    $(COMP_DIR)/COMPP.OBJ $(COMP_DIR)/COMPSM.OBJ $(COMP_DIR)/COMP2.OBJ
	cd $(COMP_DIR) && $(LINK) "@COMP.LNK"

$(COMP_OUT): $(COMP_DIR)/COMP.EXE
	cd $(COMP_DIR) && $(EXE2BIN) "COMP.EXE COMP.COM"

# ---------------------------------------------------------------------------
# ATTRIB (attrib.exe) — C + 3 ASM files, stays EXE
# ---------------------------------------------------------------------------
$(ATTRIB_DIR)/ATTRIB.CTL: $(ATTRIB_DIR)/ATTRIB.SKL $(MESSAGES_OUT)
	cd $(ATTRIB_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" ATTRIB.SKL

$(ATTRIB_DIR)/ATTRIB.CL1 $(ATTRIB_DIR)/ATTRIB.CL2 \
$(ATTRIB_DIR)/ATTRIB.CLA $(ATTRIB_DIR)/ATTRIB.CLB: \
    $(ATTRIB_DIR)/ATTRIB.CTL

$(ATTRIB_DIR)/ATTRIBA.OBJ: $(ATTRIB_DIR)/ATTRIBA.ASM
	cd $(ATTRIB_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "ATTRIBA.ASM,ATTRIBA.OBJ;"

$(ATTRIB_DIR)/_MSGRET.OBJ: $(ATTRIB_DIR)/_MSGRET.ASM \
    $(ATTRIB_DIR)/ATTRIB.CTL \
    $(ATTRIB_DIR)/ATTRIB.CL1 $(ATTRIB_DIR)/ATTRIB.CL2 \
    $(ATTRIB_DIR)/ATTRIB.CLA $(ATTRIB_DIR)/ATTRIB.CLB
	cd $(ATTRIB_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "_MSGRET.ASM,_MSGRET.OBJ;"

$(ATTRIB_DIR)/_PARSE.OBJ: $(ATTRIB_DIR)/_PARSE.ASM
	cd $(ATTRIB_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "_PARSE.ASM,_PARSE.OBJ;"

$(ATTRIB_DIR)/ATTRIB.OBJ: $(ATTRIB_DIR)/ATTRIB.C $(ATTRIB_DIR)/ATTRIB.CTL
	cd $(ATTRIB_DIR) && $(CL) "-AS -Os -Zp -I. -I..\\..\\H -c -FoATTRIB.OBJ ATTRIB.C"

$(ATTRIB_OUT): $(ATTRIB_DIR)/ATTRIBA.OBJ $(ATTRIB_DIR)/ATTRIB.OBJ \
    $(ATTRIB_DIR)/_PARSE.OBJ $(ATTRIB_DIR)/_MSGRET.OBJ
	cd $(ATTRIB_DIR) && $(LINK) "@ATTRIB.LNK"

# ---------------------------------------------------------------------------
# EDLIN (edlin.com) — 5 ASM files, CONVERT
# ---------------------------------------------------------------------------
$(EDLIN_DIR)/EDLIN.CTL: $(EDLIN_DIR)/EDLIN.SKL $(MESSAGES_OUT)
	cd $(EDLIN_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" EDLIN.SKL

$(EDLIN_DIR)/EDLIN.CL1 $(EDLIN_DIR)/EDLIN.CL2 \
$(EDLIN_DIR)/EDLIN.CLA $(EDLIN_DIR)/EDLIN.CLB \
$(EDLIN_DIR)/EDLIN.CLC: $(EDLIN_DIR)/EDLIN.CTL

$(EDLIN_DIR)/EDLIN.OBJ: $(EDLIN_DIR)/EDLIN.ASM $(EDLIN_DIR)/EDLIN.CTL
	cd $(EDLIN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "EDLIN.ASM,EDLIN.OBJ;"

$(EDLIN_DIR)/EDLCMD1.OBJ: $(EDLIN_DIR)/EDLCMD1.ASM
	cd $(EDLIN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "EDLCMD1.ASM,EDLCMD1.OBJ;"

$(EDLIN_DIR)/EDLCMD2.OBJ: $(EDLIN_DIR)/EDLCMD2.ASM
	cd $(EDLIN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "EDLCMD2.ASM,EDLCMD2.OBJ;"

$(EDLIN_DIR)/EDLMES.OBJ: $(EDLIN_DIR)/EDLMES.ASM \
    $(EDLIN_DIR)/EDLIN.CTL \
    $(EDLIN_DIR)/EDLIN.CLA $(EDLIN_DIR)/EDLIN.CLB \
    $(EDLIN_DIR)/EDLIN.CL1 $(EDLIN_DIR)/EDLIN.CL2
	cd $(EDLIN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "EDLMES.ASM,EDLMES.OBJ;"

$(EDLIN_DIR)/EDLPARSE.OBJ: $(EDLIN_DIR)/EDLPARSE.ASM
	cd $(EDLIN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "EDLPARSE.ASM,EDLPARSE.OBJ;"

$(EDLIN_DIR)/EDLIN.EXE: $(EDLIN_DIR)/EDLIN.OBJ $(EDLIN_DIR)/EDLCMD1.OBJ \
    $(EDLIN_DIR)/EDLCMD2.OBJ $(EDLIN_DIR)/EDLMES.OBJ $(EDLIN_DIR)/EDLPARSE.OBJ
	cd $(EDLIN_DIR) && $(LINK) "@EDLIN.LNK"

$(EDLIN_OUT): $(EDLIN_DIR)/EDLIN.EXE
	cd $(EDLIN_DIR) && $(CONVERT) "EDLIN.EXE"

# ---------------------------------------------------------------------------
# FC (fc.exe) — 5 C files + 7 ASM files + INC/KSTRING.OBJ, stays EXE
# No SKL/BUILDMSG — uses its own MESSAGES.ASM.
# Requires INC/KSTRING.OBJ built from INC/KSTRING.C.
# ---------------------------------------------------------------------------
KSTRING_OBJ := $(SRC)/INC/KSTRING.OBJ

$(KSTRING_OBJ): $(SRC)/INC/KSTRING.C
	cd $(SRC)/INC && $(CL) "-AS -Os -Zp -I. -I..\\H -c -FoKSTRING.OBJ KSTRING.C"

$(FC_DIR)/FC.OBJ: $(FC_DIR)/FC.C
	cd $(FC_DIR) && $(CL) "-AS -Os -Zp -I. -I..\\..\\H -c -FoFC.OBJ FC.C"

$(FC_DIR)/ERROR.OBJ: $(FC_DIR)/ERROR.C
	cd $(FC_DIR) && $(CL) "-AS -Os -Zp -I. -I..\\..\\H -c -FoERROR.OBJ ERROR.C"

$(FC_DIR)/FGETL.OBJ: $(FC_DIR)/FGETL.C
	cd $(FC_DIR) && $(CL) "-AS -Os -Zp -I. -I..\\..\\H -c -FoFGETL.OBJ FGETL.C"

$(FC_DIR)/NTOI.OBJ: $(FC_DIR)/NTOI.C
	cd $(FC_DIR) && $(CL) "-AS -Os -Zp -I. -I..\\..\\H -c -FoNTOI.OBJ NTOI.C"

$(FC_DIR)/UPDATE.OBJ: $(FC_DIR)/UPDATE.C
	cd $(FC_DIR) && $(CL) "-AS -Os -Zp -I. -I..\\..\\H -c -FoUPDATE.OBJ UPDATE.C"

$(FC_DIR)/GETL.OBJ: $(FC_DIR)/GETL.ASM
	cd $(FC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GETL.ASM,GETL.OBJ;"

$(FC_DIR)/ITOUPPER.OBJ: $(FC_DIR)/ITOUPPER.ASM
	cd $(FC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "ITOUPPER.ASM,ITOUPPER.OBJ;"

$(FC_DIR)/MAXMIN.OBJ: $(FC_DIR)/MAXMIN.ASM
	cd $(FC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MAXMIN.ASM,MAXMIN.OBJ;"

$(FC_DIR)/MOVE.OBJ: $(FC_DIR)/MOVE.ASM
	cd $(FC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MOVE.ASM,MOVE.OBJ;"

$(FC_DIR)/STRING.OBJ: $(FC_DIR)/STRING.ASM
	cd $(FC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "STRING.ASM,STRING.OBJ;"

$(FC_DIR)/XTAB.OBJ: $(FC_DIR)/XTAB.ASM
	cd $(FC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "XTAB.ASM,XTAB.OBJ;"

$(FC_DIR)/MESSAGES.OBJ: $(FC_DIR)/MESSAGES.ASM
	cd $(FC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MESSAGES.ASM,MESSAGES.OBJ;"

FC_OBJS := $(addprefix $(FC_DIR)/,\
    FC.OBJ ERROR.OBJ FGETL.OBJ GETL.OBJ ITOUPPER.OBJ \
    MAXMIN.OBJ MOVE.OBJ NTOI.OBJ STRING.OBJ UPDATE.OBJ \
    XTAB.OBJ MESSAGES.OBJ)

$(FC_OUT): $(FC_OBJS) $(KSTRING_OBJ)
	cd $(FC_DIR) && $(LINK) "@FC.LNK"
