CMD_DIR  := $(SRC)/CMD
COMMAND_DIR := $(CMD_DIR)/COMMAND
COMMAND_OUT := $(COMMAND_DIR)/COMMAND.COM

SYS_DIR    := $(CMD_DIR)/SYS
SYS_OUT    := $(SYS_DIR)/SYS.COM

FORMAT_DIR := $(CMD_DIR)/FORMAT
FORMAT_OUT := $(FORMAT_DIR)/FORMAT.COM

CHKDSK_DIR := $(CMD_DIR)/CHKDSK
CHKDSK_OUT := $(CHKDSK_DIR)/CHKDSK.COM

DEBUG_DIR  := $(CMD_DIR)/DEBUG
DEBUG_OUT  := $(DEBUG_DIR)/DEBUG.COM

MEM_DIR    := $(CMD_DIR)/MEM
MEM_OUT    := $(MEM_DIR)/MEM.EXE

FDISK_DIR  := $(CMD_DIR)/FDISK
FDISK_OUT  := $(FDISK_DIR)/FDISK.EXE

MORE_DIR   := $(CMD_DIR)/MORE
MORE_OUT   := $(MORE_DIR)/MORE.COM

SORT_DIR   := $(CMD_DIR)/SORT
SORT_OUT   := $(SORT_DIR)/SORT.EXE

LABEL_DIR  := $(CMD_DIR)/LABEL
LABEL_OUT  := $(LABEL_DIR)/LABEL.COM

FIND_DIR   := $(CMD_DIR)/FIND
FIND_OUT   := $(FIND_DIR)/FIND.EXE

TREE_DIR   := $(CMD_DIR)/TREE
TREE_OUT   := $(TREE_DIR)/TREE.COM

COMP_DIR   := $(CMD_DIR)/COMP
COMP_OUT   := $(COMP_DIR)/COMP.COM

ATTRIB_DIR := $(CMD_DIR)/ATTRIB
ATTRIB_OUT := $(ATTRIB_DIR)/ATTRIB.EXE

EDLIN_DIR  := $(CMD_DIR)/EDLIN
EDLIN_OUT  := $(EDLIN_DIR)/EDLIN.COM

FC_DIR       := $(CMD_DIR)/FC
FC_OUT       := $(FC_DIR)/FC.EXE

NLSFUNC_DIR  := $(CMD_DIR)/NLSFUNC
NLSFUNC_OUT  := $(NLSFUNC_DIR)/NLSFUNC.EXE

ASSIGN_DIR   := $(CMD_DIR)/ASSIGN
ASSIGN_OUT   := $(ASSIGN_DIR)/ASSIGN.COM

XCOPY_DIR    := $(CMD_DIR)/XCOPY
XCOPY_OUT    := $(XCOPY_DIR)/XCOPY.EXE

DISKCOMP_DIR := $(CMD_DIR)/DISKCOMP
DISKCOMP_OUT := $(DISKCOMP_DIR)/DISKCOMP.COM

DISKCOPY_DIR := $(CMD_DIR)/DISKCOPY
DISKCOPY_OUT := $(DISKCOPY_DIR)/DISKCOPY.COM

APPEND_DIR   := $(CMD_DIR)/APPEND
APPEND_OUT   := $(APPEND_DIR)/APPEND.EXE

RECOVER_DIR  := $(CMD_DIR)/RECOVER
RECOVER_OUT  := $(RECOVER_DIR)/RECOVER.COM

FASTOPEN_DIR := $(CMD_DIR)/FASTOPEN
FASTOPEN_OUT := $(FASTOPEN_DIR)/FASTOPEN.EXE

PRINT_DIR    := $(CMD_DIR)/PRINT
PRINT_OUT    := $(PRINT_DIR)/PRINT.COM

FILESYS_DIR  := $(CMD_DIR)/FILESYS
FILESYS_OUT  := $(FILESYS_DIR)/FILESYS.EXE

REPLACE_DIR  := $(CMD_DIR)/REPLACE
REPLACE_OUT  := $(REPLACE_DIR)/REPLACE.EXE

JOIN_DIR     := $(CMD_DIR)/JOIN
JOIN_OUT     := $(JOIN_DIR)/JOIN.EXE

SUBST_DIR    := $(CMD_DIR)/SUBST
SUBST_OUT    := $(SUBST_DIR)/SUBST.EXE

BACKUP_DIR   := $(CMD_DIR)/BACKUP
BACKUP_OUT   := $(BACKUP_DIR)/BACKUP.COM

RESTORE_DIR  := $(CMD_DIR)/RESTORE
RESTORE_OUT  := $(RESTORE_DIR)/RESTORE.COM

GRAFTABL_DIR := $(CMD_DIR)/GRAFTABL
GRAFTABL_OUT := $(GRAFTABL_DIR)/GRAFTABL.COM

KEYB_DIR     := $(CMD_DIR)/KEYB
KEYB_OUT     := $(KEYB_DIR)/KEYB.COM

SHARE_DIR    := $(CMD_DIR)/SHARE
SHARE_OUT    := $(SHARE_DIR)/SHARE.EXE

EXE2BIN_DIR  := $(CMD_DIR)/EXE2BIN
EXE2BIN_SRC_OUT := $(EXE2BIN_DIR)/EXE2BIN.EXE

GRAPHICS_DIR := $(CMD_DIR)/GRAPHICS
GRAPHICS_OUT := $(GRAPHICS_DIR)/GRAPHICS.COM

IFSFUNC_DIR  := $(CMD_DIR)/IFSFUNC
IFSFUNC_OUT  := $(IFSFUNC_DIR)/IFSFUNC.EXE

MODE_DIR     := $(CMD_DIR)/MODE
MODE_OUT     := $(MODE_DIR)/MODE.COM

SETVER_DIR   := $(CMD_DIR)/SETVER
SETVER_OUT   := $(SETVER_DIR)/SETVER.COM
SETVER_DEVICE_OUT := $(SETVER_DIR)/SETVER.EXE

DOSKEY_DIR   := $(CMD_DIR)/DOSKEY
DOSKEY_OUT   := $(DOSKEY_DIR)/DOSKEY.COM

EXPAND_DIR   := $(CMD_DIR)/EXPAND
EXPAND_OUT   := $(EXPAND_DIR)/EXPAND.EXE

SETUP_DIR    := $(CMD_DIR)/SETUP
SETUP_OUT    := $(SETUP_DIR)/SETUP.EXE

HELP_DIR     := $(CMD_DIR)/HELP
HELP_OUT     := $(HELP_DIR)/HELP.COM
FASTHELP_OUT := $(HELP_DIR)/FASTHELP.COM
HELP_DB      := $(HELP_DIR)/HELP.HLP

MIRROR_DIR   := $(CMD_DIR)/MIRROR
MIRROR_OUT   := $(MIRROR_DIR)/MIRROR.COM

UNFORMAT_DIR := $(CMD_DIR)/UNFORMAT
UNFORMAT_OUT := $(UNFORMAT_DIR)/UNFORMAT.COM

UNDELETE_DIR := $(CMD_DIR)/UNDELETE
UNDELETE_OUT := $(UNDELETE_DIR)/UNDELETE.COM

CHOICE_DIR   := $(CMD_DIR)/CHOICE
CHOICE_OUT   := $(CHOICE_DIR)/CHOICE.COM

LOADFIX_DIR  := $(CMD_DIR)/LOADFIX
LOADFIX_OUT  := $(LOADFIX_DIR)/LOADFIX.COM

DELTREE_DIR  := $(CMD_DIR)/DELTREE
DELTREE_OUT  := $(DELTREE_DIR)/DELTREE.EXE

MOVE_DIR     := $(CMD_DIR)/MOVE
MOVE_OUT     := $(MOVE_DIR)/MOVE.EXE

MSD_DIR      := $(CMD_DIR)/MSD
MSD_OUT      := $(MSD_DIR)/MSD.EXE

SCANDISK_DIR := $(CMD_DIR)/SCANDISK
SCANDISK_OUT := $(SCANDISK_DIR)/SCANDISK.EXE

DEFRAG_DIR   := $(CMD_DIR)/DEFRAG
DEFRAG_OUT   := $(DEFRAG_DIR)/DEFRAG.EXE

MEMMAKER_DIR := $(CMD_DIR)/MEMMAKER
MEMMAKER_OUT := $(MEMMAKER_DIR)/MEMMAKER.EXE

POWER_DIR        := $(CMD_DIR)/POWER
POWER_OUT        := $(POWER_DIR)/POWER.EXE

cmd_command: $(COMMAND_OUT)

cmd: $(COMMAND_OUT) $(SYS_OUT) $(FORMAT_OUT) $(CHKDSK_OUT) $(DEBUG_OUT) \
     $(MEM_OUT) $(FDISK_OUT) \
     $(MORE_OUT) $(SORT_OUT) $(LABEL_OUT) $(FIND_OUT) $(TREE_OUT) $(COMP_OUT) \
     $(ATTRIB_OUT) $(EDLIN_OUT) $(FC_OUT) \
     $(NLSFUNC_OUT) $(ASSIGN_OUT) $(XCOPY_OUT) $(DISKCOMP_OUT) $(DISKCOPY_OUT) \
     $(APPEND_OUT) $(RECOVER_OUT) $(FASTOPEN_OUT) $(PRINT_OUT) \
     $(FILESYS_OUT) $(REPLACE_OUT) $(JOIN_OUT) $(SUBST_OUT) \
     $(BACKUP_OUT) $(RESTORE_OUT) $(GRAFTABL_OUT) $(KEYB_OUT) $(SHARE_OUT) \
     $(EXE2BIN_SRC_OUT) $(GRAPHICS_OUT) \
     $(IFSFUNC_OUT) $(MODE_OUT) $(SETVER_OUT) $(SETVER_DEVICE_OUT) $(DOSKEY_OUT) \
     $(EXPAND_OUT) $(SETUP_OUT) $(HELP_OUT) $(FASTHELP_OUT) $(MIRROR_OUT) $(UNFORMAT_OUT) \
     $(UNDELETE_OUT) $(CHOICE_OUT) $(LOADFIX_OUT) $(DELTREE_OUT) $(MOVE_OUT) \
     $(MSD_OUT) $(SCANDISK_OUT) $(DEFRAG_OUT) $(MEMMAKER_OUT) \
     $(POWER_OUT)

$(CHOICE_DIR)/CHOICE.OBJ: $(CHOICE_DIR)/CHOICE.C
	cd $(CHOICE_DIR) && $(WCC) "-AS -Os -Zp -c -FoCHOICE.OBJ CHOICE.C"

$(CHOICE_DIR)/CHOICE.EXE: $(CHOICE_DIR)/CHOICE.OBJ
	cd $(CHOICE_DIR) && $(WLINK) "CHOICE.OBJ,CHOICE.EXE,,clibs.lib;"

$(CHOICE_OUT): $(CHOICE_DIR)/CHOICE.EXE $(CONVERT) $(BIN)/convert-loader.asm
	cd $(CHOICE_DIR) && $(CONVERT) "CHOICE.EXE CHOICE.COM"

$(LOADFIX_DIR)/LOADFIX.OBJ: $(LOADFIX_DIR)/LOADFIX.C
	cd $(LOADFIX_DIR) && $(WCC) "-AS -Os -Zp -c -FoLOADFIX.OBJ LOADFIX.C"

$(LOADFIX_DIR)/LOADFIX.EXE: $(LOADFIX_DIR)/LOADFIX.OBJ
	cd $(LOADFIX_DIR) && $(WLINK) "LOADFIX.OBJ,LOADFIX.EXE,,clibs.lib;"

$(LOADFIX_OUT): $(LOADFIX_DIR)/LOADFIX.EXE $(CONVERT) $(BIN)/convert-loader.asm
	cd $(LOADFIX_DIR) && $(CONVERT) "LOADFIX.EXE LOADFIX.COM"

$(DELTREE_DIR)/DELTREE.OBJ: $(DELTREE_DIR)/DELTREE.C
	cd $(DELTREE_DIR) && $(WCC) "-AS -Os -Zp -c -FoDELTREE.OBJ DELTREE.C"

$(DELTREE_OUT): $(DELTREE_DIR)/DELTREE.OBJ
	cd $(DELTREE_DIR) && $(WLINK) "DELTREE.OBJ,DELTREE.EXE,,clibs.lib;"

$(MOVE_DIR)/MOVE.OBJ: $(MOVE_DIR)/MOVE.C
	cd $(MOVE_DIR) && $(WCC) "-AS -Os -Zp -c -FoMOVE.OBJ MOVE.C"

$(MOVE_OUT): $(MOVE_DIR)/MOVE.OBJ
	cd $(MOVE_DIR) && $(WLINK) "MOVE.OBJ,MOVE.EXE,,clibs.lib;"

$(MSD_DIR)/MSD.OBJ: $(MSD_DIR)/MSD.C
	cd $(MSD_DIR) && $(WCC) "-AS -Os -Zp -c -FoMSD.OBJ MSD.C"

$(MSD_OUT): $(MSD_DIR)/MSD.OBJ
	cd $(MSD_DIR) && $(WLINK) "MSD.OBJ,MSD.EXE,,clibs.lib;"

$(CMD_DIR)/RECOVERY/FATVOL.OBJ: $(CMD_DIR)/RECOVERY/FATVOL.C $(CMD_DIR)/RECOVERY/FATVOL.H
	cd $(CMD_DIR)/RECOVERY && $(WCC) "-AS -Os -Zp -I. -c -FoFATVOL.OBJ FATVOL.C"

$(SCANDISK_DIR)/SCANDISK.OBJ: $(SCANDISK_DIR)/SCANDISK.C $(CMD_DIR)/RECOVERY/FATVOL.H
	cd $(SCANDISK_DIR) && $(WCC) "-AS -Os -Zp -I. -I..\\RECOVERY -c -FoSCANDISK.OBJ SCANDISK.C"

$(SCANDISK_OUT): $(SCANDISK_DIR)/SCANDISK.OBJ $(CMD_DIR)/RECOVERY/FATVOL.OBJ $(CMD_DIR)/RECOVERY/RECIO.OBJ
	cd $(SCANDISK_DIR) && $(WLINK) "SCANDISK.OBJ+..\\RECOVERY\\FATVOL.OBJ+..\\RECOVERY\\RECIO.OBJ,SCANDISK.EXE,,clibs.lib;"

$(DEFRAG_DIR)/DEFRAG.OBJ: $(DEFRAG_DIR)/DEFRAG.C $(CMD_DIR)/RECOVERY/FATVOL.H
	cd $(DEFRAG_DIR) && $(WCC) "-AS -Os -Zp -I. -I..\\RECOVERY -c -FoDEFRAG.OBJ DEFRAG.C"

$(DEFRAG_OUT): $(DEFRAG_DIR)/DEFRAG.OBJ $(CMD_DIR)/RECOVERY/FATVOL.OBJ $(CMD_DIR)/RECOVERY/RECIO.OBJ
	cd $(DEFRAG_DIR) && $(WLINK) "DEFRAG.OBJ+..\\RECOVERY\\FATVOL.OBJ+..\\RECOVERY\\RECIO.OBJ,DEFRAG.EXE,,clibs.lib;"

$(MEMMAKER_DIR)/MEMMAKER.OBJ: $(MEMMAKER_DIR)/MEMMAKER.C
	cd $(MEMMAKER_DIR) && $(WCC) "-AS -Os -Zp -c -FoMEMMAKER.OBJ MEMMAKER.C"

$(MEMMAKER_OUT): $(MEMMAKER_DIR)/MEMMAKER.OBJ
	cd $(MEMMAKER_DIR) && $(WLINK) "MEMMAKER.OBJ,MEMMAKER.EXE,,clibs.lib;"

$(POWER_DIR)/POWER.OBJ: $(POWER_DIR)/POWER.ASM
	cd $(POWER_DIR) && $(MASM) "$(AFLAGS)" "POWER.ASM,POWER.OBJ;"

$(POWER_DIR)/POWERD.OBJ: $(POWER_DIR)/POWERD.ASM
	cd $(POWER_DIR) && $(MASM) "$(AFLAGS)" "POWERD.ASM,POWERD.OBJ;"

$(POWER_OUT): $(POWER_DIR)/POWERD.OBJ $(POWER_DIR)/POWER.OBJ
	cd $(POWER_DIR) && $(WLINK) "POWERD.OBJ+POWER.OBJ,POWER.EXE;"

$(MIRROR_DIR)/MIRROR.OBJ: $(MIRROR_DIR)/MIRROR.C $(CMD_DIR)/RECOVERY/RECOVERY.H
	cd $(MIRROR_DIR) && $(WCC) "-AS -Os -Zp -I. -c -FoMIRROR.OBJ MIRROR.C"

$(CMD_DIR)/RECOVERY/RECIO.OBJ: $(CMD_DIR)/RECOVERY/RECIO.ASM
	cd $(CMD_DIR)/RECOVERY && $(MASM) "$(AFLAGS)" "RECIO.ASM,RECIO.OBJ;"

$(MIRROR_DIR)/MIRROR.EXE: $(MIRROR_DIR)/MIRROR.OBJ $(CMD_DIR)/RECOVERY/RECIO.OBJ
	cd $(MIRROR_DIR) && $(WLINK) "MIRROR.OBJ+..\\RECOVERY\\RECIO.OBJ,MIRROR.EXE,,clibs.lib;"

$(MIRROR_OUT): $(MIRROR_DIR)/MIRROR.EXE $(CONVERT) $(BIN)/convert-loader.asm
	cd $(MIRROR_DIR) && $(CONVERT) "MIRROR.EXE MIRROR.COM"

$(UNFORMAT_DIR)/UNFORMAT.OBJ: $(UNFORMAT_DIR)/UNFORMAT.C $(CMD_DIR)/RECOVERY/RECOVERY.H
	cd $(UNFORMAT_DIR) && $(WCC) "-AS -Os -Zp -I. -c -FoUNFORMAT.OBJ UNFORMAT.C"

$(UNFORMAT_DIR)/UNFORMAT.EXE: $(UNFORMAT_DIR)/UNFORMAT.OBJ $(CMD_DIR)/RECOVERY/RECIO.OBJ
	cd $(UNFORMAT_DIR) && $(WLINK) "UNFORMAT.OBJ+..\\RECOVERY\\RECIO.OBJ,UNFORMAT.EXE,,clibs.lib;"

$(UNFORMAT_OUT): $(UNFORMAT_DIR)/UNFORMAT.EXE $(CONVERT) $(BIN)/convert-loader.asm
	cd $(UNFORMAT_DIR) && $(CONVERT) "UNFORMAT.EXE UNFORMAT.COM"

$(UNDELETE_DIR)/UNDELETE.OBJ: $(UNDELETE_DIR)/UNDELETE.C
	cd $(UNDELETE_DIR) && $(WCC) "-AS -Os -Zp -I. -c -FoUNDELETE.OBJ UNDELETE.C"

$(UNDELETE_DIR)/TRACKTSR.OBJ: $(UNDELETE_DIR)/TRACKTSR.ASM
	cd $(UNDELETE_DIR) && $(MASM) "$(AFLAGS)" "TRACKTSR.ASM,TRACKTSR.OBJ;"

$(UNDELETE_DIR)/UNDELETE.EXE: $(UNDELETE_DIR)/UNDELETE.OBJ $(UNDELETE_DIR)/TRACKTSR.OBJ $(CMD_DIR)/RECOVERY/RECIO.OBJ
	cd $(UNDELETE_DIR) && $(WLINK) "UNDELETE.OBJ+TRACKTSR.OBJ+..\\RECOVERY\\RECIO.OBJ,UNDELETE.EXE,,clibs.lib;"

$(UNDELETE_OUT): $(UNDELETE_DIR)/UNDELETE.EXE $(CONVERT) $(BIN)/convert-loader.asm
	cd $(UNDELETE_DIR) && $(CONVERT) "UNDELETE.EXE UNDELETE.COM"

$(HELP_DIR)/HELP.OBJ: $(HELP_DIR)/HELP.ASM
	cd $(HELP_DIR) && $(MASM) "$(AFLAGS)" "HELP.ASM,HELP.OBJ;"

$(HELP_DIR)/HELPU.EXE: $(HELP_DIR)/HELP.OBJ
	cd $(HELP_DIR) && $(WLINK) "HELP.OBJ,HELPU.EXE;"

$(HELP_OUT): $(HELP_DIR)/HELPU.EXE
	cd $(HELP_DIR) && $(EXE2BIN) "HELPU.EXE HELP.COM"

# DOS 6 FASTHELP is the compact text-help entry point.  The lean HELP engine
# already implements that interface, so ship the same program under both names.
$(FASTHELP_OUT): $(HELP_OUT)
	cp $(HELP_OUT) $(FASTHELP_OUT)

$(EXPAND_DIR)/EXPAND.OBJ: $(EXPAND_DIR)/EXPAND.ASM
	cd $(EXPAND_DIR) && $(MASM) "$(AFLAGS)" "EXPAND.ASM,EXPAND.OBJ;"

$(EXPAND_OUT): $(EXPAND_DIR)/EXPAND.OBJ
	cd $(EXPAND_DIR) && $(WLINK) "EXPAND.OBJ,EXPAND.EXE;"

$(SETUP_DIR)/SETUP.OBJ: $(SETUP_DIR)/SETUP.ASM
	cd $(SETUP_DIR) && $(MASM) "$(AFLAGS)" "SETUP.ASM,SETUP.OBJ;"

$(SETUP_OUT): $(SETUP_DIR)/SETUP.OBJ
	cd $(SETUP_DIR) && $(WLINK) "SETUP.OBJ,SETUP.EXE;"

$(SETVER_DIR)/SETVER.OBJ: $(SETVER_DIR)/SETVER.ASM
	cd $(SETVER_DIR) && $(MASM) "$(AFLAGS)" "SETVER.ASM,SETVER.OBJ;"

$(SETVER_DIR)/SETVERU.EXE: $(SETVER_DIR)/SETVER.OBJ
	cd $(SETVER_DIR) && $(WLINK) "SETVER.OBJ,SETVERU.EXE;"

$(SETVER_OUT): $(SETVER_DIR)/SETVERU.EXE
	cd $(SETVER_DIR) && $(EXE2BIN) "SETVERU.EXE SETVER.COM"

$(SETVER_DIR)/SETVERD.OBJ: $(SETVER_DIR)/SETVERD.ASM $(INC_DIR)/SETVER62.INC
	cd $(SETVER_DIR) && $(MASM) "$(AFLAGS)" "SETVERD.ASM,SETVERD.OBJ;"

$(SETVER_DIR)/SETVERD.EXE: $(SETVER_DIR)/SETVERD.OBJ
	cd $(SETVER_DIR) && $(WLINK) "SETVERD.OBJ,SETVERD.EXE;"

$(SETVER_DEVICE_OUT): $(SETVER_DIR)/SETVERD.EXE
	cd $(SETVER_DIR) && $(EXE2BIN) "SETVERD.EXE SETVER.EXE"

$(DOSKEY_DIR)/DOSKEY.OBJ: $(DOSKEY_DIR)/DOSKEY.ASM
	cd $(DOSKEY_DIR) && $(MASM) "$(AFLAGS)" "DOSKEY.ASM,DOSKEY.OBJ;"

$(DOSKEY_DIR)/DOSKEY.EXE: $(DOSKEY_DIR)/DOSKEY.OBJ
	cd $(DOSKEY_DIR) && $(WLINK) "DOSKEY.OBJ,DOSKEY.EXE;"

$(DOSKEY_OUT): $(DOSKEY_DIR)/DOSKEY.EXE
	cd $(DOSKEY_DIR) && $(EXE2BIN) "DOSKEY.EXE DOSKEY.COM"

COMMAND_AINC := -I. -ID:\\TOOLS\\INC -I..\\..\\INC -I..\\..\\DOS

$(COMMAND_DIR)/COMMAND.CTL: $(COMMAND_DIR)/COMMAND.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(COMMAND_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" COMMAND.SKL

$(COMMAND_DIR)/COMMAND.CL1 $(COMMAND_DIR)/COMMAND.CL2 \
$(COMMAND_DIR)/COMMAND.CL3 $(COMMAND_DIR)/COMMAND.CL4 \
$(COMMAND_DIR)/COMMAND.CLA $(COMMAND_DIR)/COMMAND.CLB \
$(COMMAND_DIR)/COMMAND.CLC $(COMMAND_DIR)/COMMAND.CLD \
$(COMMAND_DIR)/COMMAND.CLE $(COMMAND_DIR)/COMMAND.CLF: \
    $(COMMAND_DIR)/COMMAND.CTL

$(COMMAND_DIR)/COMMAND1.OBJ: $(COMMAND_DIR)/COMMAND1.ASM \
    $(COMMAND_DIR)/COMMAND.CTL
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "COMMAND1.ASM,COMMAND1.OBJ;"

$(COMMAND_DIR)/COMMAND2.OBJ: $(COMMAND_DIR)/COMMAND2.ASM \
    $(COMMAND_DIR)/COMMAND.CTL
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "COMMAND2.ASM,COMMAND2.OBJ;"

$(COMMAND_DIR)/RUCODE.OBJ: $(COMMAND_DIR)/RUCODE.ASM \
    $(COMMAND_DIR)/COMMAND.CTL
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "RUCODE.ASM,RUCODE.OBJ;"

$(COMMAND_DIR)/RDATA.OBJ: $(COMMAND_DIR)/RDATA.ASM \
    $(COMMAND_DIR)/COMMAND.CLA $(COMMAND_DIR)/COMMAND.CL3 \
    $(COMMAND_DIR)/COMMAND.CL4 $(COMMAND_DIR)/COMMAND.CLD \
    $(COMMAND_DIR)/COMMAND.CLC $(COMMAND_DIR)/COMMAND.CLE \
    $(COMMAND_DIR)/COMMAND.CTL
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "RDATA.ASM,RDATA.OBJ;"

$(COMMAND_DIR)/INIT.OBJ: $(COMMAND_DIR)/INIT.ASM \
    $(COMMAND_DIR)/COMMAND.CTL
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "INIT.ASM,INIT.OBJ;"

$(COMMAND_DIR)/IPARSE.OBJ: $(COMMAND_DIR)/IPARSE.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "IPARSE.ASM,IPARSE.OBJ;"

$(COMMAND_DIR)/UINIT.OBJ: $(COMMAND_DIR)/UINIT.ASM \
    $(COMMAND_DIR)/COMMAND.CLB $(COMMAND_DIR)/COMMAND.CTL
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "UINIT.ASM,UINIT.OBJ;"

$(COMMAND_DIR)/TCODE.OBJ: $(COMMAND_DIR)/TCODE.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TCODE.ASM,TCODE.OBJ;"

$(COMMAND_DIR)/TBATCH.OBJ: $(COMMAND_DIR)/TBATCH.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TBATCH.ASM,TBATCH.OBJ;"

$(COMMAND_DIR)/TBATCH2.OBJ: $(COMMAND_DIR)/TBATCH2.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TBATCH2.ASM,TBATCH2.OBJ;"

$(COMMAND_DIR)/TFOR.OBJ: $(COMMAND_DIR)/TFOR.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TFOR.ASM,TFOR.OBJ;"

$(COMMAND_DIR)/TCMD1A.OBJ: $(COMMAND_DIR)/TCMD1A.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TCMD1A.ASM,TCMD1A.OBJ;"

$(COMMAND_DIR)/TCMD1B.OBJ: $(COMMAND_DIR)/TCMD1B.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TCMD1B.ASM,TCMD1B.OBJ;"

$(COMMAND_DIR)/TCMD2A.OBJ: $(COMMAND_DIR)/TCMD2A.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TCMD2A.ASM,TCMD2A.OBJ;"

$(COMMAND_DIR)/TCMD2B.OBJ: $(COMMAND_DIR)/TCMD2B.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TCMD2B.ASM,TCMD2B.OBJ;"

$(COMMAND_DIR)/TENV.OBJ: $(COMMAND_DIR)/TENV.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TENV.ASM,TENV.OBJ;"

$(COMMAND_DIR)/TENV2.OBJ: $(COMMAND_DIR)/TENV2.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TENV2.ASM,TENV2.OBJ;"

$(COMMAND_DIR)/TMISC1.OBJ: $(COMMAND_DIR)/TMISC1.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TMISC1.ASM,TMISC1.OBJ;"

$(COMMAND_DIR)/TMISC2.OBJ: $(COMMAND_DIR)/TMISC2.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TMISC2.ASM,TMISC2.OBJ;"

$(COMMAND_DIR)/TPIPE.OBJ: $(COMMAND_DIR)/TPIPE.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TPIPE.ASM,TPIPE.OBJ;"

$(COMMAND_DIR)/PARSE2.OBJ: $(COMMAND_DIR)/PARSE2.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "PARSE2.ASM,PARSE2.OBJ;"

$(COMMAND_DIR)/PATH1.OBJ: $(COMMAND_DIR)/PATH1.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "PATH1.ASM,PATH1.OBJ;"

$(COMMAND_DIR)/PATH2.OBJ: $(COMMAND_DIR)/PATH2.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "PATH2.ASM,PATH2.OBJ;"

$(COMMAND_DIR)/TUCODE.OBJ: $(COMMAND_DIR)/TUCODE.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TUCODE.ASM,TUCODE.OBJ;"

$(COMMAND_DIR)/COPY.OBJ: $(COMMAND_DIR)/COPY.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "COPY.ASM,COPY.OBJ;"

$(COMMAND_DIR)/COPYPR1.OBJ: $(COMMAND_DIR)/COPYPR1.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "COPYPR1.ASM,COPYPR1.OBJ;"

$(COMMAND_DIR)/COPYPR2.OBJ: $(COMMAND_DIR)/COPYPR2.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "COPYPR2.ASM,COPYPR2.OBJ;"

$(COMMAND_DIR)/CPARSE.OBJ: $(COMMAND_DIR)/CPARSE.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "CPARSE.ASM,CPARSE.OBJ;"

$(COMMAND_DIR)/TPARSE.OBJ: $(COMMAND_DIR)/TPARSE.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TPARSE.ASM,TPARSE.OBJ;"

$(COMMAND_DIR)/TPRINTF.OBJ: $(COMMAND_DIR)/TPRINTF.ASM \
    $(COMMAND_DIR)/COMMAND.CTL
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TPRINTF.ASM,TPRINTF.OBJ;"

$(COMMAND_DIR)/TDATA.OBJ: $(COMMAND_DIR)/TDATA.ASM \
    $(COMMAND_DIR)/COMMAND.CLF $(COMMAND_DIR)/COMMAND.CL1 \
    $(COMMAND_DIR)/COMMAND.CL2 $(COMMAND_DIR)/COMMAND.CTL
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TDATA.ASM,TDATA.OBJ;"

$(COMMAND_DIR)/TSPC.OBJ: $(COMMAND_DIR)/TSPC.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "TSPC.ASM,TSPC.OBJ;"

$(COMMAND_DIR)/DIR5EXT.OBJ: $(COMMAND_DIR)/DIR5EXT.ASM
	cd $(COMMAND_DIR) && $(MASM) "$(AFLAGS) $(COMMAND_AINC)" "DIR5EXT.ASM,DIR5EXT.OBJ;"

COMMAND_OBJS := COMMAND1.OBJ COMMAND2.OBJ RUCODE.OBJ RDATA.OBJ INIT.OBJ \
    IPARSE.OBJ UINIT.OBJ TCODE.OBJ TBATCH.OBJ TBATCH2.OBJ TFOR.OBJ \
    TCMD1A.OBJ TCMD1B.OBJ TCMD2A.OBJ TCMD2B.OBJ TENV.OBJ TENV2.OBJ \
    TMISC1.OBJ TMISC2.OBJ TPIPE.OBJ PARSE2.OBJ PATH1.OBJ PATH2.OBJ \
    TUCODE.OBJ COPY.OBJ COPYPR1.OBJ COPYPR2.OBJ CPARSE.OBJ \
    TPARSE.OBJ TPRINTF.OBJ TDATA.OBJ TSPC.OBJ DIR5EXT.OBJ

COMMAND_OBJ_PATHS := $(addprefix $(COMMAND_DIR)/,$(COMMAND_OBJS))

$(COMMAND_OBJ_PATHS): $(INC_DIR)/VERSIONA.INC

$(COMMAND_DIR)/COMMAND.EXE: $(COMMAND_OBJ_PATHS)
	cd $(COMMAND_DIR) && $(WLINK) "@COMMAND.LNK"

$(COMMAND_OUT): $(COMMAND_DIR)/COMMAND.EXE
	cd $(COMMAND_DIR) && $(EXE2BIN) "COMMAND.EXE COMMAND.COM"

SYS_AINC := -I. -ID:\\TOOLS\\INC -I..\\..\\INC

$(SYS_DIR)/SYS.CTL: $(SYS_DIR)/SYS.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(SYS_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" SYS.SKL

$(SYS_DIR)/SYS.CL1 $(SYS_DIR)/SYS.CL2 \
$(SYS_DIR)/SYS.CLA $(SYS_DIR)/SYS.CLB \
$(SYS_DIR)/SYS.CLC $(SYS_DIR)/SYS.CLD: \
    $(SYS_DIR)/SYS.CTL

$(SYS_DIR)/SYS1.OBJ: $(SYS_DIR)/SYS1.ASM $(SYS_DIR)/SYS.CTL $(BOOT_INC)
	cd $(SYS_DIR) && $(MASM) "$(AFLAGS) $(SYS_AINC)" "SYS1.ASM,SYS1.OBJ;"

$(SYS_DIR)/SYS2.OBJ: $(SYS_DIR)/SYS2.ASM $(SYS_DIR)/SYS.CTL
	cd $(SYS_DIR) && $(MASM) "$(AFLAGS) $(SYS_AINC)" "SYS2.ASM,SYS2.OBJ;"

$(SYS_DIR)/SYSSR.OBJ: $(SYS_DIR)/SYSSR.ASM \
    $(SYS_DIR)/SYS.CTL $(SYS_DIR)/SYS.CL1 $(SYS_DIR)/SYS.CL2 \
    $(SYS_DIR)/SYS.CLA $(SYS_DIR)/SYS.CLB \
    $(SYS_DIR)/SYS.CLC $(SYS_DIR)/SYS.CLD
	cd $(SYS_DIR) && $(MASM) "$(AFLAGS) $(SYS_AINC)" "SYSSR.ASM,SYSSR.OBJ;"

$(SYS_DIR)/SYS.EXE: $(SYS_DIR)/SYS1.OBJ $(SYS_DIR)/SYS2.OBJ $(SYS_DIR)/SYSSR.OBJ
	cd $(SYS_DIR) && $(WLINK) "@SYS.LNK"

$(SYS_OUT): $(SYS_DIR)/SYS.EXE
	cd $(SYS_DIR) && $(EXE2BIN) "SYS.EXE SYS.COM"

FORMAT_AINC := -I. -ID:\\TOOLS\\INC -I..\\..\\INC

$(FORMAT_DIR)/FORMAT.CTL: $(FORMAT_DIR)/FORMAT.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(FORMAT_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" FORMAT.SKL

$(FORMAT_DIR)/FORMAT.CL1 $(FORMAT_DIR)/FORMAT.CLA \
$(FORMAT_DIR)/FORMAT.CLB $(FORMAT_DIR)/FORMAT.CLC: \
    $(FORMAT_DIR)/FORMAT.CTL

$(FORMAT_DIR)/BOOT.CL1: $(SRC)/BOOT/BOOT.CL1
	cp $< $@

$(FORMAT_DIR)/DISPLAY.OBJ: $(FORMAT_DIR)/DISPLAY.ASM $(FORMAT_DIR)/FORMAT.CTL
	cd $(FORMAT_DIR) && $(MASM) "$(AFLAGS) $(FORMAT_AINC)" "DISPLAY.ASM,DISPLAY.OBJ;"

$(FORMAT_DIR)/FORINIT.OBJ: $(FORMAT_DIR)/FORINIT.ASM $(FORMAT_DIR)/FORMAT.CTL
	cd $(FORMAT_DIR) && $(MASM) "$(AFLAGS) $(FORMAT_AINC)" "FORINIT.ASM,FORINIT.OBJ;"

$(FORMAT_DIR)/FORLABEL.OBJ: $(FORMAT_DIR)/FORLABEL.ASM $(FORMAT_DIR)/FORMAT.CTL
	cd $(FORMAT_DIR) && $(MASM) "$(AFLAGS) $(FORMAT_AINC)" "FORLABEL.ASM,FORLABEL.OBJ;"

$(FORMAT_DIR)/FORMAT.OBJ: $(FORMAT_DIR)/FORMAT.ASM $(FORMAT_DIR)/FORMAT.CTL
	cd $(FORMAT_DIR) && $(MASM) "$(AFLAGS) $(FORMAT_AINC)" "FORMAT.ASM,FORMAT.OBJ;"

$(FORMAT_DIR)/FORPROC.OBJ: $(FORMAT_DIR)/FORPROC.ASM $(FORMAT_DIR)/FORMAT.CTL
	cd $(FORMAT_DIR) && $(MASM) "$(AFLAGS) $(FORMAT_AINC)" "FORPROC.ASM,FORPROC.OBJ;"

$(FORMAT_DIR)/MSFOR.OBJ: $(FORMAT_DIR)/MSFOR.ASM $(FORMAT_DIR)/FORMAT.CTL \
    $(FORMAT_DIR)/BOOT.CL1
	cd $(FORMAT_DIR) && $(MASM) "$(AFLAGS) $(FORMAT_AINC)" "MSFOR.ASM,MSFOR.OBJ;"

$(FORMAT_DIR)/FORSAVE.OBJ: $(FORMAT_DIR)/FORSAVE.ASM
	cd $(FORMAT_DIR) && $(MASM) "$(AFLAGS) $(FORMAT_AINC)" "FORSAVE.ASM,FORSAVE.OBJ;"

$(FORMAT_DIR)/FOREXEC.OBJ: $(FORMAT_DIR)/FOREXEC.ASM
	cd $(FORMAT_DIR) && $(MASM) "$(AFLAGS) $(FORMAT_AINC)" "FOREXEC.ASM,FOREXEC.OBJ;"

FORMAT_OBJS := $(addprefix $(FORMAT_DIR)/,\
    DISPLAY.OBJ FORINIT.OBJ FORLABEL.OBJ FORMAT.OBJ \
    FORPROC.OBJ MSFOR.OBJ FORSAVE.OBJ FOREXEC.OBJ)

# These utilities compile the expected DOS identity from VERSIONA.INC, either
# directly or through their symbol includes.
$(SYS_DIR)/SYS1.OBJ $(SYS_DIR)/SYS2.OBJ $(SYS_DIR)/SYSSR.OBJ \
    $(FORMAT_OBJS): $(INC_DIR)/VERSIONA.INC

$(FORMAT_DIR)/FORMAT.EXE: $(FORMAT_OBJS)
	cd $(FORMAT_DIR) && $(WLINK) "@FORMAT.LNK"

$(FORMAT_OUT): $(FORMAT_DIR)/FORMAT.EXE $(CONVERT) $(BIN)/convert-loader.asm
	cd $(FORMAT_DIR) && $(CONVERT) "FORMAT.EXE"

CHKDSK_AINC := -I. -ID:\\TOOLS\\INC -I..\\..\\INC

$(CHKDSK_DIR)/CHKDSK.CTL: $(CHKDSK_DIR)/CHKDSK.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(CHKDSK_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" CHKDSK.SKL
	# Msg_Services includes CL1 and CL2 although CHKDSK.SKL defines neither class.
	touch $(CHKDSK_DIR)/CHKDSK.CL1 $(CHKDSK_DIR)/CHKDSK.CL2

$(CHKDSK_DIR)/CHKDSK.CLA $(CHKDSK_DIR)/CHKDSK.CLB \
$(CHKDSK_DIR)/CHKDSK.CLC $(CHKDSK_DIR)/CHKDSK.CLD \
$(CHKDSK_DIR)/CHKDSK.CL1 $(CHKDSK_DIR)/CHKDSK.CL2: \
    $(CHKDSK_DIR)/CHKDSK.CTL

$(CHKDSK_DIR)/CHKDISK.OBJ: $(CHKDSK_DIR)/CHKDISK.ASM
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKDISK.ASM,CHKDISK.OBJ;"

$(CHKDSK_DIR)/CHKDISP.OBJ: $(CHKDSK_DIR)/CHKDISP.ASM \
    $(CHKDSK_DIR)/CHKDSK.CTL \
    $(CHKDSK_DIR)/CHKDSK.CLA $(CHKDSK_DIR)/CHKDSK.CLB \
    $(CHKDSK_DIR)/CHKDSK.CLC $(CHKDSK_DIR)/CHKDSK.CLD \
    $(CHKDSK_DIR)/CHKDSK.CL1 $(CHKDSK_DIR)/CHKDSK.CL2
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKDISP.ASM,CHKDISP.OBJ;"

$(CHKDSK_DIR)/CHKDSK1.OBJ: $(CHKDSK_DIR)/CHKDSK1.ASM
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKDSK1.ASM,CHKDSK1.OBJ;"

$(CHKDSK_DIR)/CHKDSK2.OBJ: $(CHKDSK_DIR)/CHKDSK2.ASM
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKDSK2.ASM,CHKDSK2.OBJ;"

$(CHKDSK_DIR)/CHKFAT.OBJ: $(CHKDSK_DIR)/CHKFAT.ASM
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKFAT.ASM,CHKFAT.OBJ;"

$(CHKDSK_DIR)/CHKINIT.OBJ: $(CHKDSK_DIR)/CHKINIT.ASM
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKINIT.ASM,CHKINIT.OBJ;"

$(CHKDSK_DIR)/CHKPRMT.OBJ: $(CHKDSK_DIR)/CHKPRMT.ASM
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKPRMT.ASM,CHKPRMT.OBJ;"

$(CHKDSK_DIR)/CHKPROC2.OBJ: $(CHKDSK_DIR)/CHKPROC2.ASM
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKPROC2.ASM,CHKPROC2.OBJ;"

$(CHKDSK_DIR)/CHKPROC.OBJ: $(CHKDSK_DIR)/CHKPROC.ASM
	cd $(CHKDSK_DIR) && $(MASM) "$(AFLAGS) $(CHKDSK_AINC)" "CHKPROC.ASM,CHKPROC.OBJ;"

CHKDSK_OBJS := $(addprefix $(CHKDSK_DIR)/,\
    CHKDISK.OBJ CHKDISP.OBJ CHKDSK1.OBJ CHKDSK2.OBJ \
    CHKFAT.OBJ CHKINIT.OBJ CHKPRMT.OBJ CHKPROC2.OBJ CHKPROC.OBJ)

$(CHKDSK_DIR)/CHKDSK.EXE: $(CHKDSK_OBJS)
	cd $(CHKDSK_DIR) && $(WLINK) "@CHKDSK.LNK"

$(CHKDSK_OUT): $(CHKDSK_DIR)/CHKDSK.EXE $(CONVERT) $(BIN)/convert-loader.asm
	cd $(CHKDSK_DIR) && $(CONVERT) "CHKDSK.EXE"

DEBUG_AINC := -I. -ID:\\TOOLS\\INC -I..\\..\\INC

$(DEBUG_DIR)/DEBUG.CTL: $(DEBUG_DIR)/DEBUG.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(DEBUG_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" DEBUG.SKL

$(DEBUG_DIR)/DEBUG.CL1 $(DEBUG_DIR)/DEBUG.CL2 \
$(DEBUG_DIR)/DEBUG.CLA $(DEBUG_DIR)/DEBUG.CLB \
$(DEBUG_DIR)/DEBUG.CLC $(DEBUG_DIR)/DEBUG.CLD: \
    $(DEBUG_DIR)/DEBUG.CTL

$(DEBUG_DIR)/DEBUG.OBJ: $(DEBUG_DIR)/DEBUG.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBUG.ASM,DEBUG.OBJ;"

$(DEBUG_DIR)/DEBCOM1.OBJ: $(DEBUG_DIR)/DEBCOM1.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBCOM1.ASM,DEBCOM1.OBJ;"

$(DEBUG_DIR)/DEBCOM2.OBJ: $(DEBUG_DIR)/DEBCOM2.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBCOM2.ASM,DEBCOM2.OBJ;"

$(DEBUG_DIR)/DEBCOM3.OBJ: $(DEBUG_DIR)/DEBCOM3.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBCOM3.ASM,DEBCOM3.OBJ;"

$(DEBUG_DIR)/DEBASM.OBJ: $(DEBUG_DIR)/DEBASM.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBASM.ASM,DEBASM.OBJ;"

$(DEBUG_DIR)/DEBUASM.OBJ: $(DEBUG_DIR)/DEBUASM.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBUASM.ASM,DEBUASM.OBJ;"

$(DEBUG_DIR)/DEBERR.OBJ: $(DEBUG_DIR)/DEBERR.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBERR.ASM,DEBERR.OBJ;"

$(DEBUG_DIR)/DEBCONST.OBJ: $(DEBUG_DIR)/DEBCONST.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBCONST.ASM,DEBCONST.OBJ;"

$(DEBUG_DIR)/DEBMES.OBJ: $(DEBUG_DIR)/DEBMES.ASM \
    $(DEBUG_DIR)/DEBUG.CTL \
    $(DEBUG_DIR)/DEBUG.CLA $(DEBUG_DIR)/DEBUG.CLB \
    $(DEBUG_DIR)/DEBUG.CLC $(DEBUG_DIR)/DEBUG.CLD \
    $(DEBUG_DIR)/DEBUG.CL1 $(DEBUG_DIR)/DEBUG.CL2
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBMES.ASM,DEBMES.OBJ;"

$(DEBUG_DIR)/DEBEMS.OBJ: $(DEBUG_DIR)/DEBEMS.ASM
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBEMS.ASM,DEBEMS.OBJ;"

$(DEBUG_DIR)/DEBDATA.OBJ: $(DEBUG_DIR)/DEBDATA.ASM $(DEBUG_DIR)/DEBUG.CTL
	cd $(DEBUG_DIR) && $(MASM) "$(AFLAGS) $(DEBUG_AINC)" "DEBDATA.ASM,DEBDATA.OBJ;"

DEBUG_OBJS := $(addprefix $(DEBUG_DIR)/,\
    DEBUG.OBJ DEBCOM1.OBJ DEBCOM2.OBJ DEBCOM3.OBJ \
    DEBASM.OBJ DEBUASM.OBJ DEBERR.OBJ DEBCONST.OBJ \
    DEBMES.OBJ DEBEMS.OBJ DEBDATA.OBJ)

$(DEBUG_DIR)/DEBUG.EXE: $(DEBUG_OBJS)
	cd $(DEBUG_DIR) && $(WLINK) "@DEBUG.LNK"

$(DEBUG_OUT): $(DEBUG_DIR)/DEBUG.EXE $(CONVERT) $(BIN)/convert-loader.asm
	cd $(DEBUG_DIR) && $(CONVERT) "DEBUG.EXE"

MEM_AINC := -I. -ID:\\TOOLS\\INC -I..\\..\\INC

$(MEM_DIR)/MEM.CTL: $(MEM_DIR)/MEM.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(MEM_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" MEM.SKL

$(MEM_DIR)/MEM.CL1 $(MEM_DIR)/MEM.CL2 \
$(MEM_DIR)/MEM.CLA $(MEM_DIR)/MEM.CLB: \
    $(MEM_DIR)/MEM.CTL

$(MEM_DIR)/_MSGRET.OBJ: $(MEM_DIR)/_MSGRET.ASM \
    $(MEM_DIR)/MEM.CTL \
    $(MEM_DIR)/MEM.CLA $(MEM_DIR)/MEM.CLB \
    $(MEM_DIR)/MEM.CL1 $(MEM_DIR)/MEM.CL2
	cd $(MEM_DIR) && $(MASM) "$(AFLAGS) $(MEM_AINC)" "_MSGRET.ASM,_MSGRET.OBJ;"

$(MEM_DIR)/_PARSE.OBJ: $(MEM_DIR)/_PARSE.ASM
	cd $(MEM_DIR) && $(MASM) "$(AFLAGS) $(MEM_AINC)" "_PARSE.ASM,_PARSE.OBJ;"

$(MEM_DIR)/MEM.OBJ: $(MEM_DIR)/MEM.C $(MEM_DIR)/MEM.CTL
	cd $(MEM_DIR) && $(WCC) "-AS -Os -Zp -I. -I..\\..\\H -c -FoMEM.OBJ MEM.C"

$(MEM_DIR)/XMSINFO.OBJ: $(MEM_DIR)/XMSINFO.ASM
	cd $(MEM_DIR) && $(MASM) "$(AFLAGS)" "XMSINFO.ASM,XMSINFO.OBJ;"

$(MEM_OUT): $(MEM_DIR)/MEM.OBJ $(MEM_DIR)/XMSINFO.OBJ $(MEM_DIR)/_MSGRET.OBJ $(MEM_DIR)/_PARSE.OBJ
	cd $(MEM_DIR) && $(WLINK) "MEM.OBJ+XMSINFO.OBJ+_MSGRET.OBJ+_PARSE.OBJ,MEM.EXE,,clibs.lib;"

FDISK_AINC := -I. -ID:\\TOOLS\\INC -I..\\..\\INC
FDISK_CFLAGS := -AS -Os -s -Zp -I. -I..\\..\\H -c

$(FDISK_DIR)/FDISK.CTL: $(FDISK_DIR)/FDISK.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(FDISK_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" FDISK.SKL

$(FDISK_DIR)/FDISK.CL1 $(FDISK_DIR)/FDISK.CL2 \
$(FDISK_DIR)/FDISK.CLA $(FDISK_DIR)/FDISK.CLB: \
    $(FDISK_DIR)/FDISK.CTL

$(FDISK_DIR)/FDISKM.C: $(FDISK_DIR)/FDISK.MSG $(MESSAGES_OUT) $(MENUBLD) $(MESSAGE_CATALOG)
	cd $(FDISK_DIR) && $(MENUBLD) "FDISK.MSG ..\\..\\MESSAGES\\USA-MS.MSG"

$(FDISK_DIR)/MAIN.OBJ: $(FDISK_DIR)/MAIN.C $(FDISK_DIR)/FDISK.CTL
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoMAIN.OBJ MAIN.C"

$(FDISK_DIR)/FDISK.OBJ: $(FDISK_DIR)/FDISK.C $(FDISK_DIR)/FDISK.CTL
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoFDISK.OBJ FDISK.C"

$(FDISK_DIR)/MAINMENU.OBJ: $(FDISK_DIR)/MAINMENU.C
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoMAINMENU.OBJ MAINMENU.C"

$(FDISK_DIR)/DISPLAY.OBJ: $(FDISK_DIR)/DISPLAY.C
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoDISPLAY.OBJ DISPLAY.C"

$(FDISK_DIR)/D_MENUS.OBJ: $(FDISK_DIR)/D_MENUS.C
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoD_MENUS.OBJ D_MENUS.C"

$(FDISK_DIR)/C_MENUS.OBJ: $(FDISK_DIR)/C_MENUS.C
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoC_MENUS.OBJ C_MENUS.C"

$(FDISK_DIR)/INPUT.OBJ: $(FDISK_DIR)/INPUT.C
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoINPUT.OBJ INPUT.C"

$(FDISK_DIR)/TDISPLAY.OBJ: $(FDISK_DIR)/TDISPLAY.C
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoTDISPLAY.OBJ TDISPLAY.C"

$(FDISK_DIR)/VDISPLAY.OBJ: $(FDISK_DIR)/VDISPLAY.C
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoVDISPLAY.OBJ VDISPLAY.C"

$(FDISK_DIR)/SPACE.OBJ: $(FDISK_DIR)/SPACE.C
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoSPACE.OBJ SPACE.C"

$(FDISK_DIR)/PARTINFO.OBJ: $(FDISK_DIR)/PARTINFO.C
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoPARTINFO.OBJ PARTINFO.C"

$(FDISK_DIR)/VIDEO.OBJ: $(FDISK_DIR)/VIDEO.C
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoVIDEO.OBJ VIDEO.C"

$(FDISK_DIR)/MAKEPART.OBJ: $(FDISK_DIR)/MAKEPART.C
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoMAKEPART.OBJ MAKEPART.C"

$(FDISK_DIR)/INT13.OBJ: $(FDISK_DIR)/INT13.C
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoINT13.OBJ INT13.C"

$(FDISK_DIR)/DISKOUT.OBJ: $(FDISK_DIR)/DISKOUT.C
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoDISKOUT.OBJ DISKOUT.C"

$(FDISK_DIR)/MESSAGES.OBJ: $(FDISK_DIR)/MESSAGES.C $(FDISK_DIR)/FDISK.CTL
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoMESSAGES.OBJ MESSAGES.C"

$(FDISK_DIR)/FDPARSE.OBJ: $(FDISK_DIR)/FDPARSE.C
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoFDPARSE.OBJ FDPARSE.C"

$(FDISK_DIR)/CONVERT.OBJ: $(FDISK_DIR)/CONVERT.C
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoCONVERT.OBJ CONVERT.C"

$(FDISK_DIR)/GLOBAL.OBJ: $(FDISK_DIR)/GLOBAL.C
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoGLOBAL.OBJ GLOBAL.C"

$(FDISK_DIR)/FDISKM.OBJ: $(FDISK_DIR)/FDISKM.C
	cd $(FDISK_DIR) && $(WCC) "$(FDISK_CFLAGS) -FoFDISKM.OBJ FDISKM.C"

$(FDISK_DIR)/_MSGRET.OBJ: $(FDISK_DIR)/_MSGRET.ASM \
    $(FDISK_DIR)/FDISK.CTL \
    $(FDISK_DIR)/FDISK.CLA $(FDISK_DIR)/FDISK.CLB \
    $(FDISK_DIR)/FDISK.CL1 $(FDISK_DIR)/FDISK.CL2
	cd $(FDISK_DIR) && $(MASM) "$(AFLAGS) $(FDISK_AINC)" "_MSGRET.ASM,_MSGRET.OBJ;"

$(FDISK_DIR)/_PARSE.OBJ: $(FDISK_DIR)/_PARSE.ASM
	cd $(FDISK_DIR) && $(MASM) "$(AFLAGS) $(FDISK_AINC)" "_PARSE.ASM,_PARSE.OBJ;"

$(FDISK_DIR)/BOOTREC.OBJ: $(FDISK_DIR)/BOOTREC.ASM $(FDISK_DIR)/FDBOOT.INC
	cd $(FDISK_DIR) && $(MASM) "$(AFLAGS) $(FDISK_AINC)" "BOOTREC.ASM,BOOTREC.OBJ;"

$(FDISK_DIR)/REBOOT.OBJ: $(FDISK_DIR)/REBOOT.ASM
	cd $(FDISK_DIR) && $(MASM) "$(AFLAGS) $(FDISK_AINC)" "REBOOT.ASM,REBOOT.OBJ;"

FDISK_C_OBJS := $(addprefix $(FDISK_DIR)/,\
    MAIN.OBJ MAINMENU.OBJ D_MENUS.OBJ C_MENUS.OBJ FDISK.OBJ \
    DISPLAY.OBJ INPUT.OBJ TDISPLAY.OBJ VDISPLAY.OBJ SPACE.OBJ \
    PARTINFO.OBJ VIDEO.OBJ MAKEPART.OBJ INT13.OBJ DISKOUT.OBJ \
    MESSAGES.OBJ FDPARSE.OBJ CONVERT.OBJ GLOBAL.OBJ FDISKM.OBJ)
FDISK_ASM_OBJS := $(addprefix $(FDISK_DIR)/,\
    REBOOT.OBJ BOOTREC.OBJ FDBOOT.OBJ _PARSE.OBJ _MSGRET.OBJ)

$(FDISK_OUT): $(FDISK_C_OBJS) $(FDISK_ASM_OBJS) $(MAPPER_LIB)
	cd $(FDISK_DIR) && $(WLINK) "/DOSSEG /MAP /CPA:1000 /SEG:1024 MAIN.OBJ+MAINMENU.OBJ+D_MENUS.OBJ+C_MENUS.OBJ+FDISK.OBJ+REBOOT.OBJ+BOOTREC.OBJ+FDBOOT.OBJ+DISPLAY.OBJ+INPUT.OBJ+TDISPLAY.OBJ+VDISPLAY.OBJ+SPACE.OBJ+PARTINFO.OBJ+VIDEO.OBJ+MAKEPART.OBJ+INT13.OBJ+DISKOUT.OBJ+MESSAGES.OBJ+FDPARSE.OBJ+CONVERT.OBJ+GLOBAL.OBJ+_PARSE.OBJ+_MSGRET.OBJ+FDISKM.OBJ,FDISK.EXE,FDISK.MAP,..\\..\\MAPPER\\MAPPER.LIB+clibs.lib;"

$(MORE_DIR)/MORE.CTL: $(MORE_DIR)/MORE.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(MORE_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" MORE.SKL

$(MORE_DIR)/MORE.OBJ: $(MORE_DIR)/MORE.ASM $(MORE_DIR)/MORE.CTL
	cd $(MORE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MORE.ASM,MORE.OBJ;"

$(MORE_DIR)/MORE.EXE: $(MORE_DIR)/MORE.OBJ
	cd $(MORE_DIR) && $(WLINK) "@MORE.LNK"

$(MORE_OUT): $(MORE_DIR)/MORE.EXE
	cd $(MORE_DIR) && $(EXE2BIN) "MORE.EXE MORE.COM"

$(SORT_DIR)/SORT.CTL: $(SORT_DIR)/SORT.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(SORT_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" SORT.SKL

$(SORT_DIR)/SORT.OBJ: $(SORT_DIR)/SORT.ASM $(SORT_DIR)/SORT.CTL
	cd $(SORT_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "SORT.ASM,SORT.OBJ;"

$(SORT_DIR)/SORTMES.OBJ: $(SORT_DIR)/SORTMES.ASM $(SORT_DIR)/SORT.CTL
	cd $(SORT_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "SORTMES.ASM,SORTMES.OBJ;"

$(SORT_OUT): $(SORT_DIR)/SORT.OBJ $(SORT_DIR)/SORTMES.OBJ
	cd $(SORT_DIR) && $(WLINK) "SORT+SORTMES,SORT.EXE;"
	$(BIN)/exefix $(SORT_OUT) 1 1

$(LABEL_DIR)/LABL.CTL: $(LABEL_DIR)/LABL.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(LABEL_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" LABL.SKL

$(LABEL_DIR)/LABEL.OBJ: $(LABEL_DIR)/LABEL.ASM $(LABEL_DIR)/LABL.CTL
	cd $(LABEL_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "LABEL.ASM,LABEL.OBJ;"

$(LABEL_DIR)/LABELM.OBJ: $(LABEL_DIR)/LABELM.ASM $(LABEL_DIR)/LABL.CTL
	cd $(LABEL_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "LABELM.ASM,LABELM.OBJ;"

$(LABEL_DIR)/LABEL.EXE: $(LABEL_DIR)/LABEL.OBJ $(LABEL_DIR)/LABELM.OBJ
	cd $(LABEL_DIR) && $(WLINK) "@LABEL.LNK"

$(LABEL_OUT): $(LABEL_DIR)/LABEL.EXE
	cd $(LABEL_DIR) && $(EXE2BIN) "LABEL.EXE LABEL.COM"

$(FIND_DIR)/FIND.CTL: $(FIND_DIR)/FIND.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(FIND_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" FIND.SKL

$(FIND_DIR)/FIND.OBJ: $(FIND_DIR)/FIND.ASM $(FIND_DIR)/FIND.CTL
	cd $(FIND_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "FIND.ASM,FIND.OBJ;"

$(FIND_DIR)/FINDMES.OBJ: $(FIND_DIR)/FINDMES.ASM $(FIND_DIR)/FIND.CTL
	cd $(FIND_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "FINDMES.ASM,FINDMES.OBJ;"

$(FIND_OUT): $(FIND_DIR)/FIND.OBJ $(FIND_DIR)/FINDMES.OBJ
	cd $(FIND_DIR) && $(WLINK) "FIND+FINDMES,FIND.EXE/EX;"
	$(BIN)/fix-exepack $(FIND_OUT)

$(TREE_DIR)/TREE.CTL: $(TREE_DIR)/TREE.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(TREE_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" TREE.SKL

$(TREE_DIR)/TREE.OBJ: $(TREE_DIR)/TREE.ASM $(TREE_DIR)/TREE.CTL
	cd $(TREE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "TREE.ASM,TREE.OBJ;"

$(TREE_DIR)/TREEPAR.OBJ: $(TREE_DIR)/TREEPAR.ASM
	cd $(TREE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "TREEPAR.ASM,TREEPAR.OBJ;"

$(TREE_DIR)/TREESYSP.OBJ: $(TREE_DIR)/TREESYSP.ASM $(TREE_DIR)/TREE.CTL
	cd $(TREE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "TREESYSP.ASM,TREESYSP.OBJ;"

$(TREE_DIR)/TREESYSM.OBJ: $(TREE_DIR)/TREESYSM.ASM $(TREE_DIR)/TREE.CTL \
    $(INC_DIR)/VERSIONA.INC
	cd $(TREE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "TREESYSM.ASM,TREESYSM.OBJ;"

$(TREE_DIR)/TREE.EXE: $(TREE_DIR)/TREE.OBJ $(TREE_DIR)/TREEPAR.OBJ \
    $(TREE_DIR)/TREESYSP.OBJ $(TREE_DIR)/TREESYSM.OBJ
	cd $(TREE_DIR) && $(WLINK) "@TREE.LNK"

$(TREE_OUT): $(TREE_DIR)/TREE.EXE
	cd $(TREE_DIR) && $(EXE2BIN) "TREE.EXE TREE.COM"

$(COMP_DIR)/COMP.CTL: $(COMP_DIR)/COMP.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(COMP_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" COMP.SKL

$(COMP_DIR)/COMP1.OBJ: $(COMP_DIR)/COMP1.ASM $(COMP_DIR)/COMP.CTL
	cd $(COMP_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "COMP1.ASM,COMP1.OBJ;"

$(COMP_DIR)/COMPPAR.OBJ: $(COMP_DIR)/COMPPAR.ASM
	cd $(COMP_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "COMPPAR.ASM,COMPPAR.OBJ;"

$(COMP_DIR)/COMPP.OBJ: $(COMP_DIR)/COMPP.ASM $(COMP_DIR)/COMP.CTL
	cd $(COMP_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "COMPP.ASM,COMPP.OBJ;"

$(COMP_DIR)/COMPSM.OBJ: $(COMP_DIR)/COMPSM.ASM $(COMP_DIR)/COMP.CTL
	cd $(COMP_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "COMPSM.ASM,COMPSM.OBJ;"

$(COMP_DIR)/COMP2.OBJ: $(COMP_DIR)/COMP2.ASM $(COMP_DIR)/COMP.CTL
	cd $(COMP_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "COMP2.ASM,COMP2.OBJ;"

$(COMP_DIR)/COMP.EXE: $(COMP_DIR)/COMP1.OBJ $(COMP_DIR)/COMPPAR.OBJ \
    $(COMP_DIR)/COMPP.OBJ $(COMP_DIR)/COMPSM.OBJ $(COMP_DIR)/COMP2.OBJ
	cd $(COMP_DIR) && $(WLINK) "@COMP.LNK"

$(COMP_OUT): $(COMP_DIR)/COMP.EXE
	cd $(COMP_DIR) && $(EXE2BIN) "COMP.EXE COMP.COM"

$(ATTRIB_DIR)/ATTRIB.CTL: $(ATTRIB_DIR)/ATTRIB.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(ATTRIB_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" ATTRIB.SKL

$(ATTRIB_DIR)/ATTRIB.CL1 $(ATTRIB_DIR)/ATTRIB.CL2 \
$(ATTRIB_DIR)/ATTRIB.CLA $(ATTRIB_DIR)/ATTRIB.CLB: \
    $(ATTRIB_DIR)/ATTRIB.CTL

$(ATTRIB_DIR)/_MSGRET.OBJ: $(ATTRIB_DIR)/_MSGRET.ASM \
    $(ATTRIB_DIR)/ATTRIB.CTL \
    $(ATTRIB_DIR)/ATTRIB.CL1 $(ATTRIB_DIR)/ATTRIB.CL2 \
    $(ATTRIB_DIR)/ATTRIB.CLA $(ATTRIB_DIR)/ATTRIB.CLB
	cd $(ATTRIB_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "_MSGRET.ASM,_MSGRET.OBJ;"

$(ATTRIB_DIR)/_PARSE.OBJ: $(ATTRIB_DIR)/_PARSE.ASM
	cd $(ATTRIB_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "_PARSE.ASM,_PARSE.OBJ;"

$(ATTRIB_DIR)/ATTRIB.OBJ: $(ATTRIB_DIR)/ATTRIB.C $(ATTRIB_DIR)/ATTRIB.CTL
	cd $(ATTRIB_DIR) && $(WCC) "-AS -Os -Zp -I. -I..\\..\\H -c -FoATTRIB.OBJ ATTRIB.C"

$(ATTRIB_DIR)/PSPBYTE.OBJ: $(ATTRIB_DIR)/pspbyte.c
	cd $(ATTRIB_DIR) && $(WCC) "-AS -Os -Zp -I. -c -FoPSPBYTE.OBJ pspbyte.c"

$(ATTRIB_DIR)/CRITERR.OBJ: $(ATTRIB_DIR)/criterr.asm
	cd $(ATTRIB_DIR) && $(MASM) "$(AFLAGS) -I." "criterr.asm,CRITERR.OBJ;"

$(ATTRIB_OUT): $(ATTRIB_DIR)/ATTRIB.OBJ $(ATTRIB_DIR)/PSPBYTE.OBJ \
    $(ATTRIB_DIR)/CRITERR.OBJ $(ATTRIB_DIR)/_PARSE.OBJ $(ATTRIB_DIR)/_MSGRET.OBJ
	cd $(ATTRIB_DIR) && $(WLINK) "ATTRIB.OBJ+PSPBYTE.OBJ+CRITERR.OBJ+_PARSE.OBJ+_MSGRET.OBJ,ATTRIB.EXE,,;"

$(EDLIN_DIR)/EDLIN.CTL: $(EDLIN_DIR)/EDLIN.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(EDLIN_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" EDLIN.SKL

$(EDLIN_DIR)/EDLIN.CL1 $(EDLIN_DIR)/EDLIN.CL2 \
$(EDLIN_DIR)/EDLIN.CLA $(EDLIN_DIR)/EDLIN.CLB \
$(EDLIN_DIR)/EDLIN.CLC: $(EDLIN_DIR)/EDLIN.CTL

$(EDLIN_DIR)/EDLIN.OBJ: $(EDLIN_DIR)/EDLIN.ASM $(EDLIN_DIR)/EDLIN.CTL
	cd $(EDLIN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "EDLIN.ASM,EDLIN.OBJ;"

$(EDLIN_DIR)/EDLCMD1.OBJ: $(EDLIN_DIR)/EDLCMD1.ASM
	cd $(EDLIN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "EDLCMD1.ASM,EDLCMD1.OBJ;"

$(EDLIN_DIR)/EDLCMD2.OBJ: $(EDLIN_DIR)/EDLCMD2.ASM
	cd $(EDLIN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "EDLCMD2.ASM,EDLCMD2.OBJ;"

$(EDLIN_DIR)/EDLMES.OBJ: $(EDLIN_DIR)/EDLMES.ASM \
    $(EDLIN_DIR)/EDLIN.CTL \
    $(EDLIN_DIR)/EDLIN.CLA $(EDLIN_DIR)/EDLIN.CLB \
    $(EDLIN_DIR)/EDLIN.CL1 $(EDLIN_DIR)/EDLIN.CL2
	cd $(EDLIN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "EDLMES.ASM,EDLMES.OBJ;"

$(EDLIN_DIR)/EDLPARSE.OBJ: $(EDLIN_DIR)/EDLPARSE.ASM
	cd $(EDLIN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "EDLPARSE.ASM,EDLPARSE.OBJ;"

$(EDLIN_DIR)/EDLIN.EXE: $(EDLIN_DIR)/EDLIN.OBJ $(EDLIN_DIR)/EDLCMD1.OBJ \
    $(EDLIN_DIR)/EDLCMD2.OBJ $(EDLIN_DIR)/EDLMES.OBJ $(EDLIN_DIR)/EDLPARSE.OBJ
	cd $(EDLIN_DIR) && $(WLINK) "@EDLIN.LNK"

$(EDLIN_OUT): $(EDLIN_DIR)/EDLIN.EXE $(CONVERT) $(BIN)/convert-loader.asm
	cd $(EDLIN_DIR) && $(CONVERT) "EDLIN.EXE"

FC_KSTRING_OBJ := $(SRC)/INC/KSTRING.OW.OBJ

$(FC_KSTRING_OBJ): $(SRC)/INC/KSTRING.C
	cd $(SRC)/INC && $(WCC) "-AS -Os -Zp -I. -I..\\H -c -FoKSTRING.OW.OBJ KSTRING.C"

$(FC_DIR)/FC.OBJ: $(FC_DIR)/FC.C $(FC_DIR)/FC.H
	cd $(FC_DIR) && $(WCC) "-AS -Os -Zp -I. -I..\\..\\H -c -FoFC.OBJ FC.C"

$(FC_DIR)/ERROR.OBJ: $(FC_DIR)/ERROR.C
	cd $(FC_DIR) && $(WCC) "-AS -Os -Zp -I. -I..\\..\\H -c -FoERROR.OBJ ERROR.C"

$(FC_DIR)/FGETL.OBJ: $(FC_DIR)/FGETL.C
	cd $(FC_DIR) && $(WCC) "-AS -Os -Zp -I. -I..\\..\\H -c -FoFGETL.OBJ FGETL.C"

$(FC_DIR)/NTOI.OBJ: $(FC_DIR)/NTOI.C
	cd $(FC_DIR) && $(WCC) "-AS -Os -Zp -I. -I..\\..\\H -c -FoNTOI.OBJ NTOI.C"

$(FC_DIR)/UPDATE.OBJ: $(FC_DIR)/UPDATE.C
	cd $(FC_DIR) && $(WCC) "-AS -Os -Zp -I. -I..\\..\\H -c -FoUPDATE.OBJ UPDATE.C"

$(FC_DIR)/COMPAT.OBJ: $(FC_DIR)/COMPAT.C
	cd $(FC_DIR) && $(WCC) "-AS -Os -Zp -I. -c -FoCOMPAT.OBJ COMPAT.C"

$(FC_DIR)/GETL.OBJ: $(FC_DIR)/GETL.ASM
	cd $(FC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GETL.ASM,GETL.OBJ;"

$(FC_DIR)/ITOUPPER.OBJ: $(FC_DIR)/ITOUPPER.ASM
	cd $(FC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "ITOUPPER.ASM,ITOUPPER.OBJ;"

$(FC_DIR)/MAXMIN.OBJ: $(FC_DIR)/MAXMIN.ASM
	cd $(FC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MAXMIN.ASM,MAXMIN.OBJ;"

$(FC_DIR)/MOVE.OBJ: $(FC_DIR)/MOVE.ASM
	cd $(FC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MOVE.ASM,MOVE.OBJ;"

$(FC_DIR)/STRING.OBJ: $(FC_DIR)/STRING.ASM
	cd $(FC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "STRING.ASM,STRING.OBJ;"

$(FC_DIR)/XTAB.OBJ: $(FC_DIR)/XTAB.ASM
	cd $(FC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "XTAB.ASM,XTAB.OBJ;"

$(FC_DIR)/MESSAGES.OBJ: $(FC_DIR)/MESSAGES.ASM
	cd $(FC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MESSAGES.ASM,MESSAGES.OBJ;"

FC_OBJS := $(addprefix $(FC_DIR)/,\
    FC.OBJ ERROR.OBJ FGETL.OBJ GETL.OBJ ITOUPPER.OBJ \
    MAXMIN.OBJ MOVE.OBJ NTOI.OBJ STRING.OBJ UPDATE.OBJ \
    XTAB.OBJ MESSAGES.OBJ COMPAT.OBJ)

$(FC_OUT): $(FC_OBJS) $(FC_KSTRING_OBJ)
	cd $(FC_DIR) && $(WLINK) "FC.OBJ+ERROR.OBJ+FGETL.OBJ+GETL.OBJ+ITOUPPER.OBJ+..\\..\\INC\\KSTRING.OW.OBJ+MAXMIN.OBJ+MOVE.OBJ+NTOI.OBJ+STRING.OBJ+UPDATE.OBJ+XTAB.OBJ+MESSAGES.OBJ+COMPAT.OBJ,FC.EXE,,;"

$(NLSFUNC_DIR)/NLSFUNC.CTL: $(NLSFUNC_DIR)/NLSFUNC.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(NLSFUNC_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" NLSFUNC.SKL

$(NLSFUNC_DIR)/NLSFUNC.OBJ: $(NLSFUNC_DIR)/NLSFUNC.ASM $(NLSFUNC_DIR)/NLSFUNC.CTL
	cd $(NLSFUNC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "NLSFUNC.ASM,NLSFUNC.OBJ;"

$(NLSFUNC_DIR)/NLSPARM.OBJ: $(NLSFUNC_DIR)/NLSPARM.ASM
	cd $(NLSFUNC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "NLSPARM.ASM,NLSPARM.OBJ;"

$(NLSFUNC_OUT): $(NLSFUNC_DIR)/NLSFUNC.OBJ $(NLSFUNC_DIR)/NLSPARM.OBJ
	cd $(NLSFUNC_DIR) && $(WLINK) "NLSFUNC+NLSPARM;"

$(ASSIGN_DIR)/ASSIGN.CTL: $(ASSIGN_DIR)/ASSIGN.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(ASSIGN_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" ASSIGN.SKL

$(ASSIGN_DIR)/ASSGMAIN.OBJ: $(ASSIGN_DIR)/ASSGMAIN.ASM $(ASSIGN_DIR)/ASSIGN.CTL
	cd $(ASSIGN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "ASSGMAIN.ASM,ASSGMAIN.OBJ;"

$(ASSIGN_DIR)/ASSGPARM.OBJ: $(ASSIGN_DIR)/ASSGPARM.ASM
	cd $(ASSIGN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "ASSGPARM.ASM,ASSGPARM.OBJ;"

$(ASSIGN_DIR)/ASSIGN.EXE: $(ASSIGN_DIR)/ASSGMAIN.OBJ $(ASSIGN_DIR)/ASSGPARM.OBJ
	cd $(ASSIGN_DIR) && $(WLINK) "ASSGMAIN.OBJ+ASSGPARM.OBJ,ASSIGN,,;"

$(ASSIGN_OUT): $(ASSIGN_DIR)/ASSIGN.EXE
	cd $(ASSIGN_DIR) && $(EXE2BIN) "ASSIGN.EXE ASSIGN.COM"

$(XCOPY_DIR)/XCOPY.CTL: $(XCOPY_DIR)/XCOPY.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(XCOPY_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" XCOPY.SKL

$(XCOPY_DIR)/XCOPY.OBJ: $(XCOPY_DIR)/XCOPY.ASM $(XCOPY_DIR)/XCOPY.CTL
	cd $(XCOPY_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "XCOPY.ASM,XCOPY.OBJ;"

$(XCOPY_DIR)/XCPYINIT.OBJ: $(XCOPY_DIR)/XCPYINIT.ASM $(XCOPY_DIR)/XCOPY.CTL
	cd $(XCOPY_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "XCPYINIT.ASM,XCPYINIT.OBJ;"

$(XCOPY_DIR)/XCOPYPAR.OBJ: $(XCOPY_DIR)/XCOPYPAR.ASM
	cd $(XCOPY_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "XCOPYPAR.ASM,XCOPYPAR.OBJ;"

$(XCOPY_OUT): $(XCOPY_DIR)/XCOPY.OBJ $(XCOPY_DIR)/XCPYINIT.OBJ $(XCOPY_DIR)/XCOPYPAR.OBJ
	cd $(XCOPY_DIR) && $(WLINK) "@XCOPY.LNK"

$(DISKCOMP_DIR)/DISKCOMP.CTL: $(DISKCOMP_DIR)/DISKCOMP.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(DISKCOMP_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" DISKCOMP.SKL

$(DISKCOMP_DIR)/DISKCOMP.OBJ: $(DISKCOMP_DIR)/DISKCOMP.ASM $(DISKCOMP_DIR)/DISKCOMP.CTL
	cd $(DISKCOMP_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "DISKCOMP.ASM,DISKCOMP.OBJ;"

$(DISKCOMP_DIR)/DCOMPSM.OBJ: $(DISKCOMP_DIR)/DCOMPSM.ASM $(DISKCOMP_DIR)/DISKCOMP.CTL
	cd $(DISKCOMP_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "DCOMPSM.ASM,DCOMPSM.OBJ;"

$(DISKCOMP_DIR)/DCOMPP.OBJ: $(DISKCOMP_DIR)/DCOMPP.ASM $(DISKCOMP_DIR)/DISKCOMP.CTL
	cd $(DISKCOMP_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "DCOMPP.ASM,DCOMPP.OBJ;"

$(DISKCOMP_DIR)/DCOMPPAR.OBJ: $(DISKCOMP_DIR)/DCOMPPAR.ASM
	cd $(DISKCOMP_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "DCOMPPAR.ASM,DCOMPPAR.OBJ;"

$(DISKCOMP_DIR)/COMPINIT.OBJ: $(DISKCOMP_DIR)/COMPINIT.ASM
	cd $(DISKCOMP_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "COMPINIT.ASM,COMPINIT.OBJ;"

$(DISKCOMP_DIR)/DISKCOMP.EXE: $(DISKCOMP_DIR)/DISKCOMP.OBJ $(DISKCOMP_DIR)/DCOMPSM.OBJ \
    $(DISKCOMP_DIR)/DCOMPP.OBJ $(DISKCOMP_DIR)/DCOMPPAR.OBJ $(DISKCOMP_DIR)/COMPINIT.OBJ
	cd $(DISKCOMP_DIR) && $(WLINK) "@DISKCOMP.LNK"

$(DISKCOMP_OUT): $(DISKCOMP_DIR)/DISKCOMP.EXE
	cd $(DISKCOMP_DIR) && $(EXE2BIN) "DISKCOMP.EXE DISKCOMP.COM"

$(DISKCOPY_DIR)/DISKCOPY.CTL: $(DISKCOPY_DIR)/DISKCOPY.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(DISKCOPY_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" DISKCOPY.SKL

$(DISKCOPY_DIR)/DISKCOPY.OBJ: $(DISKCOPY_DIR)/DISKCOPY.ASM $(DISKCOPY_DIR)/DISKCOPY.CTL
	cd $(DISKCOPY_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "DISKCOPY.ASM,DISKCOPY.OBJ;"

$(DISKCOPY_DIR)/DCOPYSM.OBJ: $(DISKCOPY_DIR)/DCOPYSM.ASM $(DISKCOPY_DIR)/DISKCOPY.CTL
	cd $(DISKCOPY_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "DCOPYSM.ASM,DCOPYSM.OBJ;"

$(DISKCOPY_DIR)/DCOPYP.OBJ: $(DISKCOPY_DIR)/DCOPYP.ASM $(DISKCOPY_DIR)/DISKCOPY.CTL
	cd $(DISKCOPY_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "DCOPYP.ASM,DCOPYP.OBJ;"

$(DISKCOPY_DIR)/DCOPYPAR.OBJ: $(DISKCOPY_DIR)/DCOPYPAR.ASM
	cd $(DISKCOPY_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "DCOPYPAR.ASM,DCOPYPAR.OBJ;"

$(DISKCOPY_DIR)/COPYINIT.OBJ: $(DISKCOPY_DIR)/COPYINIT.ASM
	cd $(DISKCOPY_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "COPYINIT.ASM,COPYINIT.OBJ;"

$(DISKCOPY_DIR)/DISKCOPY.EXE: $(DISKCOPY_DIR)/DISKCOPY.OBJ $(DISKCOPY_DIR)/DCOPYSM.OBJ \
    $(DISKCOPY_DIR)/DCOPYP.OBJ $(DISKCOPY_DIR)/DCOPYPAR.OBJ $(DISKCOPY_DIR)/COPYINIT.OBJ
	cd $(DISKCOPY_DIR) && $(WLINK) "@DISKCOPY.LNK"

$(DISKCOPY_OUT): $(DISKCOPY_DIR)/DISKCOPY.EXE
	cd $(DISKCOPY_DIR) && $(EXE2BIN) "DISKCOPY.EXE DISKCOPY.COM"

$(APPEND_DIR)/APPEND.CTL: $(APPEND_DIR)/APPEND.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(APPEND_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" APPEND.SKL

$(APPEND_DIR)/APPEND.OBJ: $(APPEND_DIR)/APPEND.ASM $(APPEND_DIR)/APPEND.CTL
	cd $(APPEND_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "APPEND.ASM,APPEND.OBJ;"

$(APPEND_OUT): $(APPEND_DIR)/APPEND.OBJ
	cd $(APPEND_DIR) && $(WLINK) "APPEND;"

$(RECOVER_DIR)/RECOVER.CTL: $(RECOVER_DIR)/RECOVER.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(RECOVER_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" RECOVER.SKL

$(RECOVER_DIR)/RECDISP.OBJ: $(RECOVER_DIR)/RECDISP.ASM $(RECOVER_DIR)/RECOVER.CTL
	cd $(RECOVER_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "RECDISP.ASM,RECDISP.OBJ;"

$(RECOVER_DIR)/RECINIT.OBJ: $(RECOVER_DIR)/RECINIT.ASM $(RECOVER_DIR)/RECOVER.CTL
	cd $(RECOVER_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "RECINIT.ASM,RECINIT.OBJ;"

$(RECOVER_DIR)/RECPROC.OBJ: $(RECOVER_DIR)/RECPROC.ASM $(RECOVER_DIR)/RECOVER.CTL
	cd $(RECOVER_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "RECPROC.ASM,RECPROC.OBJ;"

$(RECOVER_DIR)/RECOVER.OBJ: $(RECOVER_DIR)/RECOVER.ASM $(RECOVER_DIR)/RECOVER.CTL
	cd $(RECOVER_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "RECOVER.ASM,RECOVER.OBJ;"

$(RECOVER_DIR)/RECOVER.EXE: $(RECOVER_DIR)/RECDISP.OBJ $(RECOVER_DIR)/RECINIT.OBJ \
    $(RECOVER_DIR)/RECPROC.OBJ $(RECOVER_DIR)/RECOVER.OBJ
	cd $(RECOVER_DIR) && $(WLINK) "@RECOVER.LNK"

$(RECOVER_OUT): $(RECOVER_DIR)/RECOVER.EXE $(CONVERT) $(BIN)/convert-loader.asm
	cd $(RECOVER_DIR) && $(CONVERT) "RECOVER.EXE"

$(FASTOPEN_DIR)/FASTOPEN.CTL: $(FASTOPEN_DIR)/FASTOPEN.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(FASTOPEN_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" FASTOPEN.SKL

$(FASTOPEN_DIR)/FASTOPEN.OBJ: $(FASTOPEN_DIR)/FASTOPEN.ASM $(FASTOPEN_DIR)/FASTOPEN.CTL
	cd $(FASTOPEN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "FASTOPEN.ASM,FASTOPEN.OBJ;"

$(FASTOPEN_DIR)/FASTSEEK.OBJ: $(FASTOPEN_DIR)/FASTSEEK.ASM
	cd $(FASTOPEN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "FASTSEEK.ASM,FASTSEEK.OBJ;"

$(FASTOPEN_DIR)/FASTINIT.OBJ: $(FASTOPEN_DIR)/FASTINIT.ASM $(FASTOPEN_DIR)/FASTOPEN.CTL
	cd $(FASTOPEN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "FASTINIT.ASM,FASTINIT.OBJ;"

$(FASTOPEN_DIR)/FASTP.OBJ: $(FASTOPEN_DIR)/FASTP.ASM
	cd $(FASTOPEN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "FASTP.ASM,FASTP.OBJ;"

$(FASTOPEN_DIR)/FASTSM.OBJ: $(FASTOPEN_DIR)/FASTSM.ASM $(FASTOPEN_DIR)/FASTOPEN.CTL
	cd $(FASTOPEN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "FASTSM.ASM,FASTSM.OBJ;"

$(FASTOPEN_OUT): $(FASTOPEN_DIR)/FASTOPEN.OBJ $(FASTOPEN_DIR)/FASTSEEK.OBJ \
    $(FASTOPEN_DIR)/FASTINIT.OBJ $(FASTOPEN_DIR)/FASTP.OBJ $(FASTOPEN_DIR)/FASTSM.OBJ
	cd $(FASTOPEN_DIR) && $(WLINK) "@FASTOPEN.LNK"

$(PRINT_DIR)/PRINT.CTL: $(PRINT_DIR)/PRINT.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(PRINT_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" PRINT.SKL

$(PRINT_DIR)/PRINT_RM.OBJ: $(PRINT_DIR)/PRINT_RM.ASM $(PRINT_DIR)/PRINT.CTL
	cd $(PRINT_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "PRINT_RM.ASM,PRINT_RM.OBJ;"

$(PRINT_DIR)/PRINT_R.OBJ: $(PRINT_DIR)/PRINT_R.ASM $(PRINT_DIR)/PRINT.CTL
	cd $(PRINT_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "PRINT_R.ASM,PRINT_R.OBJ;"

$(PRINT_DIR)/PRINT_T.OBJ: $(PRINT_DIR)/PRINT_T.ASM $(PRINT_DIR)/PRINT.CTL
	cd $(PRINT_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "PRINT_T.ASM,PRINT_T.OBJ;"

$(PRINT_DIR)/PRINT_TM.OBJ: $(PRINT_DIR)/PRINT_TM.ASM $(PRINT_DIR)/PRINT.CTL
	cd $(PRINT_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "PRINT_TM.ASM,PRINT_TM.OBJ;"

$(PRINT_DIR)/PRINT.EXE: $(PRINT_DIR)/PRINT_RM.OBJ $(PRINT_DIR)/PRINT_R.OBJ \
    $(PRINT_DIR)/PRINT_T.OBJ $(PRINT_DIR)/PRINT_TM.OBJ
	cd $(PRINT_DIR) && $(WLINK) "@PRINT.LNK"

$(PRINT_OUT): $(PRINT_DIR)/PRINT.EXE $(CONVERT) $(BIN)/convert-loader.asm
	cd $(PRINT_DIR) && $(CONVERT) "PRINT.EXE"

$(FILESYS_DIR)/FILESYS.CTL: $(FILESYS_DIR)/FILESYS.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(FILESYS_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" FILESYS.SKL

$(FILESYS_DIR)/_MSGRET.OBJ: $(FILESYS_DIR)/_MSGRET.ASM $(FILESYS_DIR)/FILESYS.CTL
	cd $(FILESYS_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "_MSGRET.ASM,_MSGRET.OBJ;"

$(FILESYS_DIR)/_PARSE.OBJ: $(FILESYS_DIR)/_PARSE.ASM
	cd $(FILESYS_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "_PARSE.ASM,_PARSE.OBJ;"

$(FILESYS_DIR)/FILESYS.OBJ: $(FILESYS_DIR)/FILESYS.C $(FILESYS_DIR)/FILESYS.CTL
	cd $(FILESYS_DIR) && $(WCC) "-AS -Os -Zp -I. -I..\\..\\H -c -FoFILESYS.OBJ FILESYS.C"

$(FILESYS_OUT): $(FILESYS_DIR)/FILESYS.OBJ $(FILESYS_DIR)/_PARSE.OBJ $(FILESYS_DIR)/_MSGRET.OBJ
	cd $(FILESYS_DIR) && $(WLINK) "FILESYS.OBJ+_PARSE.OBJ+_MSGRET.OBJ,FILESYS.EXE,,; /NOI"

$(REPLACE_DIR)/REPLACE.CTL: $(REPLACE_DIR)/REPLACE.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(REPLACE_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" REPLACE.SKL

$(REPLACE_DIR)/REPLACE.OBJ: $(REPLACE_DIR)/REPLACE.C $(REPLACE_DIR)/REPLACE.CTL
	cd $(REPLACE_DIR) && $(WCC) "-AS -Os -Zp -I. -I..\\..\\H -c -FoREPLACE.OBJ REPLACE.C"

$(REPLACE_DIR)/OWCOMSUB.OBJ: $(SRC)/INC/OWCOMSUB.C
	cd $(REPLACE_DIR) && $(WCC) "-AS -Os -Zp -I. -c -FoOWCOMSUB.OBJ ..\\..\\INC\\OWCOMSUB.C"

$(REPLACE_DIR)/_REPLACE.OBJ: $(REPLACE_DIR)/_REPLACE.ASM $(REPLACE_DIR)/REPLACE.CTL
	cd $(REPLACE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "_REPLACE.ASM,_REPLACE.OBJ;"

$(REPLACE_DIR)/_MSGRET.OBJ: $(REPLACE_DIR)/_MSGRET.ASM $(REPLACE_DIR)/REPLACE.CTL
	cd $(REPLACE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "_MSGRET.ASM,_MSGRET.OBJ;"

$(REPLACE_DIR)/_PARSE.OBJ: $(REPLACE_DIR)/_PARSE.ASM
	cd $(REPLACE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "_PARSE.ASM,_PARSE.OBJ;"

$(REPLACE_OUT): $(REPLACE_DIR)/REPLACE.OBJ $(REPLACE_DIR)/OWCOMSUB.OBJ $(REPLACE_DIR)/_REPLACE.OBJ \
    $(REPLACE_DIR)/_MSGRET.OBJ $(REPLACE_DIR)/_PARSE.OBJ $(MAPPER_LIB)
	cd $(REPLACE_DIR) && $(WLINK) "REPLACE.OBJ+OWCOMSUB.OBJ+_REPLACE.OBJ+_MSGRET.OBJ+_PARSE.OBJ,REPLACE.EXE,,..\\..\\MAPPER\\MAPPER.LIB;"

$(JOIN_DIR)/JOIN.CTL: $(JOIN_DIR)/JOIN.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(JOIN_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" JOIN.SKL

$(JOIN_DIR)/JOIN.OBJ: $(JOIN_DIR)/JOIN.C $(JOIN_DIR)/JOIN.CTL
	cd $(JOIN_DIR) && $(WCC) "-AS -Os -Zp -I. -I..\\..\\H -c -FoJOIN.OBJ JOIN.C"

$(JOIN_DIR)/OWCOMSUB.OBJ: $(SRC)/INC/OWCOMSUB.C
	cd $(JOIN_DIR) && $(WCC) "-AS -Os -Zp -I. -c -FoOWCOMSUB.OBJ ..\\..\\INC\\OWCOMSUB.C"

$(JOIN_DIR)/_MSGRET.OBJ: $(JOIN_DIR)/_MSGRET.ASM $(JOIN_DIR)/JOIN.CTL
	cd $(JOIN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "_MSGRET.ASM,_MSGRET.OBJ;"

$(JOIN_DIR)/_PARSE.OBJ: $(JOIN_DIR)/_PARSE.ASM
	cd $(JOIN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "_PARSE.ASM,_PARSE.OBJ;"

$(JOIN_OUT): $(JOIN_DIR)/JOIN.OBJ $(JOIN_DIR)/OWCOMSUB.OBJ \
    $(JOIN_DIR)/_MSGRET.OBJ $(JOIN_DIR)/_PARSE.OBJ $(OW_INC_C_OBJ_PATHS) $(MAPPER_LIB)
	cd $(JOIN_DIR) && $(WLINK) "JOIN.OBJ+OWCOMSUB.OBJ+..\\..\\INC\\OWERRTST.OBJ+..\\..\\INC\\OWSYSVAR.OBJ+..\\..\\INC\\OWCDS.OBJ+..\\..\\INC\\OWDPB.OBJ+_MSGRET.OBJ+_PARSE.OBJ,JOIN.EXE,,..\\..\\MAPPER\\MAPPER.LIB+clibs.lib;"

$(SUBST_DIR)/SUBST.CTL: $(SUBST_DIR)/SUBST.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(SUBST_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" SUBST.SKL

$(SUBST_DIR)/SUBST.OBJ: $(SUBST_DIR)/SUBST.C $(SUBST_DIR)/SUBST.CTL
	cd $(SUBST_DIR) && $(WCC) "-AS -Os -Zp -I. -I..\\..\\H -c -FoSUBST.OBJ SUBST.C"

$(SUBST_DIR)/OWCOMSUB.OBJ: $(SRC)/INC/OWCOMSUB.C
	cd $(SUBST_DIR) && $(WCC) "-AS -Os -Zp -I. -c -FoOWCOMSUB.OBJ ..\\..\\INC\\OWCOMSUB.C"

$(SUBST_DIR)/_MSGRET.OBJ: $(SUBST_DIR)/_MSGRET.ASM $(SUBST_DIR)/SUBST.CTL
	cd $(SUBST_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "_MSGRET.ASM,_MSGRET.OBJ;"

$(SUBST_DIR)/_PARSE.OBJ: $(SUBST_DIR)/_PARSE.ASM
	cd $(SUBST_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "_PARSE.ASM,_PARSE.OBJ;"

$(SUBST_OUT): $(SUBST_DIR)/SUBST.OBJ $(SUBST_DIR)/OWCOMSUB.OBJ \
    $(SUBST_DIR)/_MSGRET.OBJ $(SUBST_DIR)/_PARSE.OBJ $(OW_INC_C_OBJ_PATHS) $(MAPPER_LIB)
	cd $(SUBST_DIR) && $(WLINK) "SUBST.OBJ+OWCOMSUB.OBJ+..\\..\\INC\\OWERRTST.OBJ+..\\..\\INC\\OWSYSVAR.OBJ+..\\..\\INC\\OWCDS.OBJ+..\\..\\INC\\OWDPB.OBJ+_MSGRET.OBJ+_PARSE.OBJ,SUBST.EXE,,..\\..\\MAPPER\\MAPPER.LIB+clibs.lib;"

$(BACKUP_DIR)/BACKUP.CTL: $(BACKUP_DIR)/BACKUP.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(BACKUP_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" BACKUP.SKL

$(BACKUP_DIR)/BACKUP.OBJ: $(BACKUP_DIR)/BACKUP.C $(BACKUP_DIR)/BACKUP.CTL
	cd $(BACKUP_DIR) && $(WCC) "-AS -Od -Zp -I. -I..\\..\\H -c -FoBACKUP.OBJ BACKUP.C"

$(BACKUP_DIR)/OWCOMSUB.OBJ: $(SRC)/INC/OWCOMSUB.C
	cd $(BACKUP_DIR) && $(WCC) "-AS -Os -Zp -I. -c -FoOWCOMSUB.OBJ ..\\..\\INC\\OWCOMSUB.C"

$(BACKUP_DIR)/_MSGRET.OBJ: $(BACKUP_DIR)/_MSGRET.ASM $(BACKUP_DIR)/BACKUP.CTL
	cd $(BACKUP_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "_MSGRET.ASM,_MSGRET.OBJ;"

$(BACKUP_DIR)/_PARSE.OBJ: $(BACKUP_DIR)/_PARSE.ASM
	cd $(BACKUP_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "_PARSE.ASM,_PARSE.OBJ;"

$(BACKUP_OUT): $(BACKUP_DIR)/BACKUP.OBJ $(BACKUP_DIR)/OWCOMSUB.OBJ $(BACKUP_DIR)/_PARSE.OBJ \
    $(BACKUP_DIR)/_MSGRET.OBJ $(MAPPER_LIB) $(CONVERT) $(BIN)/convert-loader.asm
	cd $(BACKUP_DIR) && $(WLINK) "BACKUP.OBJ+OWCOMSUB.OBJ+_PARSE.OBJ+_MSGRET.OBJ,BACKUP.EXE,,..\\..\\MAPPER\\MAPPER.LIB;"
	cd $(BACKUP_DIR) && $(CONVERT) "BACKUP.EXE BACKUP.COM"

RESTORE_HEADERS := $(wildcard $(RESTORE_DIR)/*.H)

$(RESTORE_DIR)/RESTORE.CTL: $(RESTORE_DIR)/RESTORE.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(RESTORE_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" RESTORE.SKL

$(RESTORE_DIR)/RESTORE.OBJ: $(RESTORE_DIR)/RESTORE.C $(RESTORE_DIR)/RESTORE.CTL
	cd $(RESTORE_DIR) && $(WCC) "-AS -Od -Zp -I. -I..\\..\\H -c -FoRESTORE.OBJ RESTORE.C"

$(RESTORE_DIR)/RESTPARS.OBJ: $(RESTORE_DIR)/RESTPARS.C $(RESTORE_DIR)/RESTORE.CTL
	cd $(RESTORE_DIR) && $(WCC) "-AS -Od -Zp -I. -I..\\..\\H -c -FoRESTPARS.OBJ RESTPARS.C"

$(RESTORE_DIR)/RTT1.OBJ: $(RESTORE_DIR)/RTT1.C
	cd $(RESTORE_DIR) && $(WCC) "-AS -Od -Zp -I. -I..\\..\\H -c -FoRTT1.OBJ RTT1.C"

$(RESTORE_DIR)/RTT3.OBJ: $(RESTORE_DIR)/RTT3.C
	cd $(RESTORE_DIR) && $(WCC) "-AS -Od -Zp -I. -I..\\..\\H -c -FoRTT3.OBJ RTT3.C"

$(RESTORE_DIR)/RTDO.OBJ: $(RESTORE_DIR)/RTDO.C
	cd $(RESTORE_DIR) && $(WCC) "-AS -Od -Zp -I. -I..\\..\\H -c -FoRTDO.OBJ RTDO.C"

$(RESTORE_DIR)/RTDO1.OBJ: $(RESTORE_DIR)/RTDO1.C
	cd $(RESTORE_DIR) && $(WCC) "-AS -Od -Zp -I. -I..\\..\\H -c -FoRTDO1.OBJ RTDO1.C"

$(RESTORE_DIR)/RTOLD.OBJ: $(RESTORE_DIR)/RTOLD.C
	cd $(RESTORE_DIR) && $(WCC) "-AS -Od -Zp -I. -I..\\..\\H -c -FoRTOLD.OBJ RTOLD.C"

$(RESTORE_DIR)/RTOLD1.OBJ: $(RESTORE_DIR)/RTOLD1.C
	cd $(RESTORE_DIR) && $(WCC) "-AS -Od -Zp -I. -I..\\..\\H -c -FoRTOLD1.OBJ RTOLD1.C"

$(RESTORE_DIR)/RTNEW.OBJ: $(RESTORE_DIR)/RTNEW.C
	cd $(RESTORE_DIR) && $(WCC) "-AS -Od -Zp -I. -I..\\..\\H -c -FoRTNEW.OBJ RTNEW.C"

$(RESTORE_DIR)/RTNEW1.OBJ: $(RESTORE_DIR)/RTNEW1.C
	cd $(RESTORE_DIR) && $(WCC) "-AS -Od -Zp -I. -I..\\..\\H -c -FoRTNEW1.OBJ RTNEW1.C"

$(RESTORE_DIR)/RTFILE.OBJ: $(RESTORE_DIR)/RTFILE.C
	cd $(RESTORE_DIR) && $(WCC) "-AS -Od -Zp -I. -I..\\..\\H -c -FoRTFILE.OBJ RTFILE.C"

$(RESTORE_DIR)/RTFILE1.OBJ: $(RESTORE_DIR)/RTFILE1.C
	cd $(RESTORE_DIR) && $(WCC) "-AS -Od -Zp -I. -I..\\..\\H -c -FoRTFILE1.OBJ RTFILE1.C"

$(RESTORE_DIR)/RESTORE.OBJ $(RESTORE_DIR)/RESTPARS.OBJ \
    $(RESTORE_DIR)/RTT1.OBJ $(RESTORE_DIR)/RTT3.OBJ \
    $(RESTORE_DIR)/RTDO.OBJ $(RESTORE_DIR)/RTDO1.OBJ \
    $(RESTORE_DIR)/RTOLD.OBJ $(RESTORE_DIR)/RTOLD1.OBJ \
    $(RESTORE_DIR)/RTNEW.OBJ $(RESTORE_DIR)/RTNEW1.OBJ \
    $(RESTORE_DIR)/RTFILE.OBJ $(RESTORE_DIR)/RTFILE1.OBJ: $(RESTORE_HEADERS)

$(RESTORE_DIR)/OWCOMSUB.OBJ: $(SRC)/INC/OWCOMSUB.C
	cd $(RESTORE_DIR) && $(WCC) "-AS -Os -Zp -I. -c -FoOWCOMSUB.OBJ ..\\..\\INC\\OWCOMSUB.C"

$(RESTORE_DIR)/OWDOSFS.OBJ: $(SRC)/INC/OWDOSFS.C
	cd $(RESTORE_DIR) && $(WCC) "-AS -Os -Zp -I. -c -FoOWDOSFS.OBJ ..\\..\\INC\\OWDOSFS.C"

$(RESTORE_DIR)/_MSGRET.OBJ: $(RESTORE_DIR)/_MSGRET.ASM $(RESTORE_DIR)/RESTORE.CTL
	cd $(RESTORE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "_MSGRET.ASM,_MSGRET.OBJ;"

$(RESTORE_DIR)/_PARSE.OBJ: $(RESTORE_DIR)/_PARSE.ASM
	cd $(RESTORE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "_PARSE.ASM,_PARSE.OBJ;"

$(RESTORE_OUT): $(RESTORE_DIR)/RESTORE.OBJ $(RESTORE_DIR)/RESTPARS.OBJ \
    $(RESTORE_DIR)/RTT1.OBJ $(RESTORE_DIR)/RTT3.OBJ \
    $(RESTORE_DIR)/RTDO.OBJ $(RESTORE_DIR)/RTDO1.OBJ \
    $(RESTORE_DIR)/RTOLD.OBJ $(RESTORE_DIR)/RTOLD1.OBJ \
    $(RESTORE_DIR)/RTNEW.OBJ $(RESTORE_DIR)/RTNEW1.OBJ \
    $(RESTORE_DIR)/RTFILE.OBJ $(RESTORE_DIR)/RTFILE1.OBJ $(RESTORE_DIR)/OWCOMSUB.OBJ $(RESTORE_DIR)/OWDOSFS.OBJ \
    $(RESTORE_DIR)/_PARSE.OBJ $(RESTORE_DIR)/_MSGRET.OBJ $(MAPPER_LIB) \
    $(CONVERT) $(BIN)/convert-loader.asm
	cd $(RESTORE_DIR) && $(WLINK) "/STACK:50000 RESTORE.OBJ+RESTPARS.OBJ+RTT1.OBJ+RTT3.OBJ+RTDO.OBJ+RTDO1.OBJ+RTOLD.OBJ+RTOLD1.OBJ+RTNEW.OBJ+RTNEW1.OBJ+RTFILE.OBJ+RTFILE1.OBJ+OWCOMSUB.OBJ+OWDOSFS.OBJ+_PARSE.OBJ+_MSGRET.OBJ,RESTORE.EXE,,..\\..\\MAPPER\\MAPPER.LIB;"
	cd $(RESTORE_DIR) && $(CONVERT) "RESTORE.EXE RESTORE.COM"

$(GRAFTABL_DIR)/GRAFTABL.CTL: $(GRAFTABL_DIR)/GRAFTABL.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(GRAFTABL_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" GRAFTABL.SKL

$(GRAFTABL_DIR)/GRTABHAN.OBJ: $(GRAFTABL_DIR)/GRTABHAN.ASM
	cd $(GRAFTABL_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRTABHAN.ASM,GRTABHAN.OBJ;"

$(GRAFTABL_DIR)/GRTABUS.OBJ: $(GRAFTABL_DIR)/GRTABUS.ASM
	cd $(GRAFTABL_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRTABUS.ASM,GRTABUS.OBJ;"

$(GRAFTABL_DIR)/GRTABML.OBJ: $(GRAFTABL_DIR)/GRTABML.ASM
	cd $(GRAFTABL_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRTABML.ASM,GRTABML.OBJ;"

$(GRAFTABL_DIR)/GRTABPO.OBJ: $(GRAFTABL_DIR)/GRTABPO.ASM
	cd $(GRAFTABL_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRTABPO.ASM,GRTABPO.OBJ;"

$(GRAFTABL_DIR)/GRTABCF.OBJ: $(GRAFTABL_DIR)/GRTABCF.ASM
	cd $(GRAFTABL_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRTABCF.ASM,GRTABCF.OBJ;"

$(GRAFTABL_DIR)/GRTABNO.OBJ: $(GRAFTABL_DIR)/GRTABNO.ASM
	cd $(GRAFTABL_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRTABNO.ASM,GRTABNO.OBJ;"

$(GRAFTABL_DIR)/GRTABSM.OBJ: $(GRAFTABL_DIR)/GRTABSM.ASM $(GRAFTABL_DIR)/GRAFTABL.CTL \
    $(INC_DIR)/VERSIONA.INC
	cd $(GRAFTABL_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRTABSM.ASM,GRTABSM.OBJ;"

$(GRAFTABL_DIR)/GRTABPAR.OBJ: $(GRAFTABL_DIR)/GRTABPAR.ASM
	cd $(GRAFTABL_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRTABPAR.ASM,GRTABPAR.OBJ;"

$(GRAFTABL_DIR)/GRTABP.OBJ: $(GRAFTABL_DIR)/GRTABP.ASM
	cd $(GRAFTABL_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRTABP.ASM,GRTABP.OBJ;"

$(GRAFTABL_DIR)/GRTAB.OBJ: $(GRAFTABL_DIR)/GRTAB.ASM
	cd $(GRAFTABL_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRTAB.ASM,GRTAB.OBJ;"

$(GRAFTABL_OUT): $(GRAFTABL_DIR)/GRTABHAN.OBJ $(GRAFTABL_DIR)/GRTABUS.OBJ \
    $(GRAFTABL_DIR)/GRTABML.OBJ $(GRAFTABL_DIR)/GRTABPO.OBJ \
    $(GRAFTABL_DIR)/GRTABCF.OBJ $(GRAFTABL_DIR)/GRTABNO.OBJ \
    $(GRAFTABL_DIR)/GRTABSM.OBJ $(GRAFTABL_DIR)/GRTABPAR.OBJ \
    $(GRAFTABL_DIR)/GRTABP.OBJ $(GRAFTABL_DIR)/GRTAB.OBJ
	cd $(GRAFTABL_DIR) && $(WLINK) "@GRAFTABL.LNK"
	cd $(GRAFTABL_DIR) && $(EXE2BIN) "GRAFTABL.EXE GRAFTABL.COM"

$(KEYB_DIR)/KEYB.CTL: $(KEYB_DIR)/KEYB.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(KEYB_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" KEYB.SKL

$(KEYB_DIR)/KEYB.OBJ: $(KEYB_DIR)/KEYB.ASM
	cd $(KEYB_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "KEYB.ASM,KEYB.OBJ;"

$(KEYB_DIR)/KEYBCMD.OBJ: $(KEYB_DIR)/KEYBCMD.ASM $(KEYB_DIR)/KEYB.CTL
	cd $(KEYB_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "KEYBCMD.ASM,KEYBCMD.OBJ;"

$(KEYB_DIR)/KEYBTBBL.OBJ: $(KEYB_DIR)/KEYBTBBL.ASM
	cd $(KEYB_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "KEYBTBBL.ASM,KEYBTBBL.OBJ;"

$(KEYB_DIR)/COMMSUBS.OBJ: $(KEYB_DIR)/COMMSUBS.ASM
	cd $(KEYB_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "COMMSUBS.ASM,COMMSUBS.OBJ;"

$(KEYB_DIR)/KEYBI2F.OBJ: $(KEYB_DIR)/KEYBI2F.ASM
	cd $(KEYB_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "KEYBI2F.ASM,KEYBI2F.OBJ;"

$(KEYB_DIR)/KEYBI48.OBJ: $(KEYB_DIR)/KEYBI48.ASM
	cd $(KEYB_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "KEYBI48.ASM,KEYBI48.OBJ;"

$(KEYB_DIR)/KEYBCPSD.OBJ: $(KEYB_DIR)/KEYBCPSD.ASM
	cd $(KEYB_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "KEYBCPSD.ASM,KEYBCPSD.OBJ;"

$(KEYB_DIR)/KEYBI9.OBJ: $(KEYB_DIR)/KEYBI9.ASM
	cd $(KEYB_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "KEYBI9.ASM,KEYBI9.OBJ;"

$(KEYB_DIR)/KEYBI9C.OBJ: $(KEYB_DIR)/KEYBI9C.ASM
	cd $(KEYB_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "KEYBI9C.ASM,KEYBI9C.OBJ;"

$(KEYB_DIR)/PARSER.OBJ: $(KEYB_DIR)/PARSER.ASM
	cd $(KEYB_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "PARSER.ASM,PARSER.OBJ;"

$(KEYB_OUT): $(KEYB_DIR)/KEYB.OBJ $(KEYB_DIR)/KEYBI9.OBJ $(KEYB_DIR)/KEYBI9C.OBJ \
    $(KEYB_DIR)/KEYBI2F.OBJ $(KEYB_DIR)/KEYBI48.OBJ $(KEYB_DIR)/KEYBCPSD.OBJ \
    $(KEYB_DIR)/COMMSUBS.OBJ $(KEYB_DIR)/KEYBTBBL.OBJ \
    $(KEYB_DIR)/PARSER.OBJ $(KEYB_DIR)/KEYBCMD.OBJ
	cd $(KEYB_DIR) && $(WLINK) "@KEYB.LNK"
	cd $(KEYB_DIR) && $(EXE2BIN) "KEYB.EXE KEYB.COM"

$(SHARE_DIR)/SHARE.CTL: $(SHARE_DIR)/SHARE.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(SHARE_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" SHARE.SKL

$(SHARE_DIR)/GSHARE.OBJ: $(SHARE_DIR)/GSHARE.ASM $(SHARE_DIR)/SHARE.CTL
	cd $(SHARE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GSHARE.ASM,GSHARE.OBJ;"

$(SHARE_DIR)/GSHARE2.OBJ: $(SHARE_DIR)/GSHARE2.ASM $(SHARE_DIR)/SHARE.CTL
	cd $(SHARE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GSHARE2.ASM,GSHARE2.OBJ;"

$(SHARE_DIR)/SHARESR.OBJ: $(SHARE_DIR)/SHARESR.ASM $(SHARE_DIR)/SHARE.CTL
	cd $(SHARE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "SHARESR.ASM,SHARESR.OBJ;"

$(SHARE_DIR)/SHARELNK.OBJ: $(SHARE_DIR)/SHARELNK.ASM
	cd $(SHARE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "SHARELNK.ASM,SHARELNK.OBJ;"

$(SHARE_OUT): $(SHARE_DIR)/GSHARE.OBJ $(SHARE_DIR)/GSHARE2.OBJ \
    $(SHARE_DIR)/SHARESR.OBJ $(SHARE_DIR)/SHARELNK.OBJ $(INC_ASM_OBJ_PATHS)
	cd $(SHARE_DIR) && $(WLINK) "@SHARE.LNK"

$(EXE2BIN_DIR)/EXE2BIN.CTL: $(EXE2BIN_DIR)/EXE2BIN.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(EXE2BIN_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" EXE2BIN.SKL

$(EXE2BIN_DIR)/E2BINIT.OBJ: $(EXE2BIN_DIR)/E2BINIT.ASM $(EXE2BIN_DIR)/EXE2BIN.CTL
	cd $(EXE2BIN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "E2BINIT.ASM,E2BINIT.OBJ;"

$(EXE2BIN_DIR)/DISPLAY.OBJ: $(EXE2BIN_DIR)/DISPLAY.ASM
	cd $(EXE2BIN_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "DISPLAY.ASM,DISPLAY.OBJ;"

$(EXE2BIN_SRC_OUT): $(EXE2BIN_DIR)/E2BINIT.OBJ $(EXE2BIN_DIR)/DISPLAY.OBJ
	cd $(EXE2BIN_DIR) && $(WLINK) "@EXE2BIN.LNK"
	$(BIN)/fix-exepack $(EXE2BIN_SRC_OUT)

$(GRAPHICS_DIR)/GRAPHICS.CTL: $(GRAPHICS_DIR)/GRAPHICS.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(GRAPHICS_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" GRAPHICS.SKL

$(GRAPHICS_DIR)/GRAPHICS.OBJ: $(GRAPHICS_DIR)/GRAPHICS.ASM
	cd $(GRAPHICS_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRAPHICS.ASM,GRAPHICS.OBJ;"

$(GRAPHICS_DIR)/GRINT2FH.OBJ: $(GRAPHICS_DIR)/GRINT2FH.ASM
	cd $(GRAPHICS_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRINT2FH.ASM,GRINT2FH.OBJ;"

$(GRAPHICS_DIR)/GRPATTRN.OBJ: $(GRAPHICS_DIR)/GRPATTRN.ASM
	cd $(GRAPHICS_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRPATTRN.ASM,GRPATTRN.OBJ;"

$(GRAPHICS_DIR)/GRCTRL.OBJ: $(GRAPHICS_DIR)/GRCTRL.ASM
	cd $(GRAPHICS_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRCTRL.ASM,GRCTRL.OBJ;"

$(GRAPHICS_DIR)/GRCPSD.OBJ: $(GRAPHICS_DIR)/GRPARSE.ASM $(GRAPHICS_DIR)/GRAPHICS.CTL
	cd $(GRAPHICS_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRPARSE.ASM,GRCPSD.OBJ;"

$(GRAPHICS_DIR)/GRPARSE.OBJ: $(GRAPHICS_DIR)/GRCPSD.ASM
	cd $(GRAPHICS_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRCPSD.ASM,GRPARSE.OBJ;"

$(GRAPHICS_DIR)/GRCOLPRT.OBJ: $(GRAPHICS_DIR)/GRCOLPRT.ASM
	cd $(GRAPHICS_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRCOLPRT.ASM,GRCOLPRT.OBJ;"

$(GRAPHICS_DIR)/GRBWPRT.OBJ: $(GRAPHICS_DIR)/GRBWPRT.ASM
	cd $(GRAPHICS_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRBWPRT.ASM,GRBWPRT.OBJ;"

$(GRAPHICS_DIR)/GRINST.OBJ: $(GRAPHICS_DIR)/GRINST.ASM $(GRAPHICS_DIR)/GRAPHICS.CTL
	cd $(GRAPHICS_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRINST.ASM,GRINST.OBJ;"

$(GRAPHICS_DIR)/GRPARMS.OBJ: $(GRAPHICS_DIR)/GRPARMS.ASM
	cd $(GRAPHICS_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRPARMS.ASM,GRPARMS.OBJ;"

$(GRAPHICS_DIR)/GRLOAD.OBJ: $(GRAPHICS_DIR)/GRLOAD.ASM
	cd $(GRAPHICS_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRLOAD.ASM,GRLOAD.OBJ;"

$(GRAPHICS_DIR)/GRLOAD2.OBJ: $(GRAPHICS_DIR)/GRLOAD2.ASM
	cd $(GRAPHICS_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRLOAD2.ASM,GRLOAD2.OBJ;"

$(GRAPHICS_DIR)/GRLOAD3.OBJ: $(GRAPHICS_DIR)/GRLOAD3.ASM
	cd $(GRAPHICS_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "GRLOAD3.ASM,GRLOAD3.OBJ;"

$(GRAPHICS_OUT): $(GRAPHICS_DIR)/GRAPHICS.OBJ $(GRAPHICS_DIR)/GRINT2FH.OBJ \
    $(GRAPHICS_DIR)/GRPATTRN.OBJ $(GRAPHICS_DIR)/GRCTRL.OBJ \
    $(GRAPHICS_DIR)/GRCPSD.OBJ $(GRAPHICS_DIR)/GRCOLPRT.OBJ \
    $(GRAPHICS_DIR)/GRBWPRT.OBJ $(GRAPHICS_DIR)/GRINST.OBJ \
    $(GRAPHICS_DIR)/GRPARSE.OBJ $(GRAPHICS_DIR)/GRPARMS.OBJ \
    $(GRAPHICS_DIR)/GRLOAD.OBJ $(GRAPHICS_DIR)/GRLOAD2.OBJ \
    $(GRAPHICS_DIR)/GRLOAD3.OBJ
	cd $(GRAPHICS_DIR) && $(WLINK) "@GRAPHICS.LNK"
	cd $(GRAPHICS_DIR) && $(EXE2BIN) "GRAPHICS.EXE GRAPHICS.COM"

$(IFSFUNC_DIR)/IFSFUNC.CTL: $(IFSFUNC_DIR)/IFSFUNC.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(IFSFUNC_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" IFSFUNC.SKL

$(IFSFUNC_DIR)/IFSSESS.OBJ: $(IFSFUNC_DIR)/IFSSESS.ASM
	cd $(IFSFUNC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "IFSSESS.ASM,IFSSESS.OBJ;"

$(IFSFUNC_DIR)/IFSDIR.OBJ: $(IFSFUNC_DIR)/IFSDIR.ASM
	cd $(IFSFUNC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "IFSDIR.ASM,IFSDIR.OBJ;"

$(IFSFUNC_DIR)/IFSFILE.OBJ: $(IFSFUNC_DIR)/IFSFILE.ASM
	cd $(IFSFUNC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "IFSFILE.ASM,IFSFILE.OBJ;"

$(IFSFUNC_DIR)/IFSHAND.OBJ: $(IFSFUNC_DIR)/IFSHAND.ASM
	cd $(IFSFUNC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "IFSHAND.ASM,IFSHAND.OBJ;"

$(IFSFUNC_DIR)/IFSDEV.OBJ: $(IFSFUNC_DIR)/IFSDEV.ASM
	cd $(IFSFUNC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "IFSDEV.ASM,IFSDEV.OBJ;"

$(IFSFUNC_DIR)/IFSUTIL.OBJ: $(IFSFUNC_DIR)/IFSUTIL.ASM
	cd $(IFSFUNC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "IFSUTIL.ASM,IFSUTIL.OBJ;"

$(IFSFUNC_DIR)/IFSERROR.OBJ: $(IFSFUNC_DIR)/IFSERROR.ASM $(IFSFUNC_DIR)/IFSFUNC.CTL
	cd $(IFSFUNC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "IFSERROR.ASM,IFSERROR.OBJ;"

$(IFSFUNC_DIR)/IFSFDOS.OBJ: $(IFSFUNC_DIR)/IFSFDOS.ASM $(IFSFUNC_DIR)/IFSFUNC.CTL
	cd $(IFSFUNC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "IFSFDOS.ASM,IFSFDOS.OBJ;"

$(IFSFUNC_DIR)/IFSINIT.OBJ: $(IFSFUNC_DIR)/IFSINIT.ASM $(IFSFUNC_DIR)/IFSFUNC.CTL
	cd $(IFSFUNC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "IFSINIT.ASM,IFSINIT.OBJ;"

$(IFSFUNC_DIR)/IFSFLINK.OBJ: $(IFSFUNC_DIR)/IFSFLINK.ASM
	cd $(IFSFUNC_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "IFSFLINK.ASM,IFSFLINK.OBJ;"

$(IFSFUNC_OUT): $(IFSFUNC_DIR)/IFSSESS.OBJ $(IFSFUNC_DIR)/IFSDIR.OBJ \
    $(IFSFUNC_DIR)/IFSFILE.OBJ $(IFSFUNC_DIR)/IFSHAND.OBJ \
    $(IFSFUNC_DIR)/IFSDEV.OBJ $(IFSFUNC_DIR)/IFSUTIL.OBJ \
    $(IFSFUNC_DIR)/IFSERROR.OBJ $(IFSFUNC_DIR)/IFSFDOS.OBJ \
    $(IFSFUNC_DIR)/IFSINIT.OBJ $(IFSFUNC_DIR)/IFSFLINK.OBJ \
    $(INC_ASM_OBJ_PATHS) $(DOS_DIR)/MSDISP.OBJ $(DOS_DIR)/MSCODE.OBJ
	cd $(IFSFUNC_DIR) && $(WLINK) "@IFSFUNC.LNK"
	$(BIN)/fix-exepack $(IFSFUNC_OUT)

$(MODE_DIR)/MODE.CTL: $(MODE_DIR)/MODE.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(MODE_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" MODE.SKL

$(MODE_DIR)/MAIN.OBJ: $(MODE_DIR)/MAIN.ASM $(MODE_DIR)/MODE.CTL
	cd $(MODE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MAIN.ASM,MAIN.OBJ;"

$(MODE_DIR)/SCRNTAB.OBJ: $(MODE_DIR)/SCRNTAB.ASM
	cd $(MODE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "SCRNTAB.ASM,SCRNTAB.OBJ;"

$(MODE_DIR)/MODESCRN.OBJ: $(MODE_DIR)/MODESCRN.ASM
	cd $(MODE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MODESCRN.ASM,MODESCRN.OBJ;"

$(MODE_DIR)/RESCODE.OBJ: $(MODE_DIR)/RESCODE.ASM
	cd $(MODE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "RESCODE.ASM,RESCODE.OBJ;"

$(MODE_DIR)/MODECOM.OBJ: $(MODE_DIR)/MODECOM.ASM
	cd $(MODE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MODECOM.ASM,MODECOM.OBJ;"

$(MODE_DIR)/MODEPRIN.OBJ: $(MODE_DIR)/MODEPRIN.ASM
	cd $(MODE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MODEPRIN.ASM,MODEPRIN.OBJ;"

$(MODE_DIR)/MODEVID.OBJ: $(MODE_DIR)/MODEVID.ASM
	cd $(MODE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MODEVID.ASM,MODEVID.OBJ;"

$(MODE_DIR)/MODEECHO.OBJ: $(MODE_DIR)/MODEECHO.ASM
	cd $(MODE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MODEECHO.ASM,MODEECHO.OBJ;"

$(MODE_DIR)/MODELENG.OBJ: $(MODE_DIR)/MODELENG.ASM
	cd $(MODE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MODELENG.ASM,MODELENG.OBJ;"

$(MODE_DIR)/MODECP.OBJ: $(MODE_DIR)/MODECP.ASM
	cd $(MODE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MODECP.ASM,MODECP.OBJ;"

$(MODE_DIR)/DISPLAY.OBJ: $(MODE_DIR)/DISPLAY.ASM
	cd $(MODE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "DISPLAY.ASM,DISPLAY.OBJ;"

$(MODE_DIR)/TYPAMAT.OBJ: $(MODE_DIR)/TYPAMAT.ASM
	cd $(MODE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "TYPAMAT.ASM,TYPAMAT.OBJ;"

$(MODE_DIR)/INVOKE.OBJ: $(MODE_DIR)/INVOKE.ASM
	cd $(MODE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "INVOKE.ASM,INVOKE.OBJ;"

$(MODE_DIR)/PARSHELL.OBJ: $(MODE_DIR)/PARSHELL.ASM
	cd $(MODE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "PARSHELL.ASM,PARSHELL.OBJ;"

$(MODE_DIR)/MODEPARS.OBJ: $(MODE_DIR)/MODEPARS.ASM
	cd $(MODE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MODEPARS.ASM,MODEPARS.OBJ;"

$(MODE_DIR)/MODEMES.OBJ: $(MODE_DIR)/MODEMES.ASM $(MODE_DIR)/MODE.CTL
	cd $(MODE_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "MODEMES.ASM,MODEMES.OBJ;"

$(MODE_OUT): $(MODE_DIR)/MAIN.OBJ $(MODE_DIR)/SCRNTAB.OBJ \
    $(MODE_DIR)/MODESCRN.OBJ $(MODE_DIR)/RESCODE.OBJ \
    $(MODE_DIR)/MODECOM.OBJ $(MODE_DIR)/MODEPRIN.OBJ \
    $(MODE_DIR)/MODEVID.OBJ $(MODE_DIR)/MODEECHO.OBJ \
    $(MODE_DIR)/MODELENG.OBJ $(MODE_DIR)/MODECP.OBJ \
    $(MODE_DIR)/DISPLAY.OBJ $(MODE_DIR)/TYPAMAT.OBJ \
    $(MODE_DIR)/INVOKE.OBJ $(MODE_DIR)/PARSHELL.OBJ \
    $(MODE_DIR)/MODEPARS.OBJ $(MODE_DIR)/MODEMES.OBJ
	cd $(MODE_DIR) && $(WLINK) "@MODE.LNK"
	cd $(MODE_DIR) && $(EXE2BIN) "MODE.EXE MODE.COM"
