DEV_DIR  := $(SRC)/DEV
DEV_AINC := -I. -ID:\\TOOLS\\INC -I..\\..\\INC -I..\\..\\DOS

dev: \
    $(DEV_DIR)/HIMEM/HIMEM.SYS \
    $(DEV_DIR)/EGA/EGA.SYS \
    $(DEV_DIR)/DRIVER/DRIVER.SYS \
    $(DEV_DIR)/ANSI/ANSI.SYS \
    $(DEV_DIR)/VDISK/VDISK.SYS \
    $(DEV_DIR)/COUNTRY/COUNTRY.SYS \
    $(DEV_DIR)/RAMDRIVE/RAMDRIVE.SYS \
    $(DEV_DIR)/KEYBOARD/KEYBOARD.SYS \
    $(DEV_DIR)/PRINTER/PRINTER.SYS \
    $(DEV_DIR)/DISPLAY/DISPLAY.SYS \
    $(DEV_DIR)/SMARTDRV/SMARTDRV.EXE \
    $(DEV_DIR)/SMARTDRV/FLUSH13.EXE \
    $(DEV_DIR)/XMA2EMS/XMA2EMS.SYS \
    $(DEV_DIR)/XMAEM/XMAEM.SYS \
    $(DEV_DIR)/DISPLAY/EGA/EGA.CPI \
    $(DEV_DIR)/DISPLAY/LCD/LCD.CPI \
    $(DEV_DIR)/PRINTER/5202/5202.CPI

HIMEM_DIR := $(DEV_DIR)/HIMEM

$(HIMEM_DIR)/HIMEM.SYS: $(HIMEM_DIR)/HIMEM.ASM \
    $(HIMEM_DIR)/XMSALLOC.INC $(HIMEM_DIR)/XMSHANDLE.INC $(HIMEM_DIR)/XMSAUTH.INC \
    $(HIMEM_DIR)/XMSUMB.INC $(HIMEM_DIR)/XMSUMBPEER.INC $(HIMEM_DIR)/XMSUMBFRONT.INC \
    $(HIMEM_DIR)/XMSMOVEFRONT.INC $(HIMEM_DIR)/BOOTCOPY.INC \
    $(HIMEM_DIR)/XMSRECORD.INC $(HIMEM_DIR)/XMSERROR.INC $(BIN)/jwasm-bin
	$(BIN)/jwasm-bin -Fo$@ $<

EGA_SYS_DIR := $(DEV_DIR)/EGA

$(EGA_SYS_DIR)/EGA.SYS: $(EGA_SYS_DIR)/EGA.ASM $(BIN)/jwasm-bin
	$(BIN)/jwasm-bin -Fo$@ $<

DRIVER_DIR := $(DEV_DIR)/DRIVER

$(DRIVER_DIR)/DRIVER.CTL: $(DRIVER_DIR)/DRIVER.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(DRIVER_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" DRIVER.SKL

$(DRIVER_DIR)/DRIVER.OBJ: $(DRIVER_DIR)/DRIVER.ASM $(DRIVER_DIR)/DRIVER.CTL
	cd $(DRIVER_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "DRIVER.ASM,DRIVER.OBJ;"

$(DRIVER_DIR)/DRIVER.EXE: $(DRIVER_DIR)/DRIVER.OBJ
	cd $(DRIVER_DIR) && $(WLINK) "@DRIVER.LNK"

$(DRIVER_DIR)/DRIVER.SYS: $(DRIVER_DIR)/DRIVER.EXE
	cd $(DRIVER_DIR) && $(EXE2BIN) "DRIVER.EXE DRIVER.SYS"

ANSI_DIR := $(DEV_DIR)/ANSI

$(ANSI_DIR)/ANSI.CTL: $(ANSI_DIR)/ANSI.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(ANSI_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" ANSI.SKL

$(ANSI_DIR)/ANSI.OBJ: $(ANSI_DIR)/ANSI.ASM
	cd $(ANSI_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "ANSI.ASM,ANSI.OBJ;"

$(ANSI_DIR)/IOCTL.OBJ: $(ANSI_DIR)/IOCTL.ASM
	cd $(ANSI_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "IOCTL.ASM,IOCTL.OBJ;"

$(ANSI_DIR)/ANSIINIT.OBJ: $(ANSI_DIR)/ANSIINIT.ASM
	cd $(ANSI_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "ANSIINIT.ASM,ANSIINIT.OBJ;"

$(ANSI_DIR)/PARSER.OBJ: $(ANSI_DIR)/PARSER.ASM $(ANSI_DIR)/ANSI.CTL
	cd $(ANSI_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "PARSER.ASM,PARSER.OBJ;"

$(ANSI_DIR)/ANSI.EXE: \
    $(ANSI_DIR)/ANSI.OBJ $(ANSI_DIR)/IOCTL.OBJ \
    $(ANSI_DIR)/ANSIINIT.OBJ $(ANSI_DIR)/PARSER.OBJ
	cd $(ANSI_DIR) && $(WLINK) "@ANSI.LNK"

$(ANSI_DIR)/ANSI.SYS: $(ANSI_DIR)/ANSI.EXE
	cd $(ANSI_DIR) && $(EXE2BIN) "ANSI.EXE ANSI.SYS"

VDISK_DIR := $(DEV_DIR)/VDISK

$(VDISK_DIR)/VDISK.CTL: $(VDISK_DIR)/VDISK.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(VDISK_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" VDISK.SKL

$(VDISK_DIR)/VDISKSYS.OBJ: $(VDISK_DIR)/VDISKSYS.ASM $(VDISK_DIR)/VDISK.CTL
	cd $(VDISK_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "VDISKSYS.ASM,VDISKSYS.OBJ;"

$(VDISK_DIR)/VDISK.EXE: $(VDISK_DIR)/VDISKSYS.OBJ
	cd $(VDISK_DIR) && $(WLINK) "@VDISK.LNK"

$(VDISK_DIR)/VDISK.SYS: $(VDISK_DIR)/VDISK.EXE
	cd $(VDISK_DIR) && $(EXE2BIN) "VDISK.EXE VDISK.SYS"

COUNTRY_DIR := $(DEV_DIR)/COUNTRY

$(COUNTRY_DIR)/MKCNTRY.OBJ: $(COUNTRY_DIR)/MKCNTRY.ASM \
    $(COUNTRY_DIR)/MKCNTRY.INC $(COUNTRY_DIR)/D5CNTRY.INC \
    $(COUNTRY_DIR)/D5C850.INC
	cd $(COUNTRY_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "MKCNTRY.ASM,MKCNTRY.OBJ;"

$(COUNTRY_DIR)/MKCNTRY.EXE: $(COUNTRY_DIR)/MKCNTRY.OBJ
	cd $(COUNTRY_DIR) && $(WLINK) "MKCNTRY;"

$(COUNTRY_DIR)/COUNTRY.SYS: $(COUNTRY_DIR)/MKCNTRY.EXE $(MKCNTRY)
	cd $(COUNTRY_DIR) && $(MKCNTRY) MKCNTRY.EXE COUNTRY.SYS

RAMDRIVE_DIR := $(DEV_DIR)/RAMDRIVE

$(RAMDRIVE_DIR)/RAMDRIVE.OBJ: $(RAMDRIVE_DIR)/RAMDRIVE.ASM
	cd $(RAMDRIVE_DIR) && $(MASM) "$(AFLAGS) -I. -I..\\..\\INC" "RAMDRIVE.ASM,RAMDRIVE.OBJ;"

$(RAMDRIVE_DIR)/MESSAGES.OBJ: $(RAMDRIVE_DIR)/MESSAGES.ASM
	cd $(RAMDRIVE_DIR) && $(MASM) "$(AFLAGS) -I. -I..\\..\\INC" "MESSAGES.ASM,MESSAGES.OBJ;"

$(RAMDRIVE_DIR)/RAMDRIVE.EXE: \
    $(RAMDRIVE_DIR)/RAMDRIVE.OBJ $(RAMDRIVE_DIR)/MESSAGES.OBJ
	cd $(RAMDRIVE_DIR) && $(WLINK) "@RAMDRIVE.LNK"

$(RAMDRIVE_DIR)/RAMDRIVE.SYS: $(RAMDRIVE_DIR)/RAMDRIVE.EXE
	cd $(RAMDRIVE_DIR) && $(EXE2BIN) "RAMDRIVE.EXE RAMDRIVE.SYS"

KEYBOARD_DIR := $(DEV_DIR)/KEYBOARD
KB_AINC := -I. -I..\\..\\INC

KEYBOARD_OBJS := KDFNOW.OBJ KDFFR120.OBJ KDFFR189.OBJ KDFEOF.OBJ \
    KDFUK166.OBJ KDFUK168.OBJ KDFIT141.OBJ KDFIT142.OBJ \
    KDFGE.OBJ KDFSP.OBJ KDFNL.OBJ KDFNO.OBJ KDFDK.OBJ \
    KDFSG.OBJ KDFSF.OBJ KDFPO.OBJ KDFBE.OBJ KDFCF.OBJ \
    KDFLA.OBJ KDFSV.OBJ KDFD5X.OBJ

KEYBOARD_OBJ_PATHS := $(addprefix $(KEYBOARD_DIR)/,$(KEYBOARD_OBJS))

$(KEYBOARD_DIR)/%.OBJ: $(KEYBOARD_DIR)/%.ASM
	cd $(KEYBOARD_DIR) && $(MASM) "$(AFLAGS) $(KB_AINC)" "$*.ASM,$*.OBJ;"

$(KEYBOARD_DIR)/KEYBOARD.EXE: $(KEYBOARD_OBJ_PATHS)
	cd $(KEYBOARD_DIR) && $(WLINK) "@KEYBOARD.LNK"

$(KEYBOARD_DIR)/KEYBOARD.SYS: $(KEYBOARD_DIR)/KEYBOARD.EXE
	cd $(KEYBOARD_DIR) && $(EXE2BIN) "KEYBOARD.EXE KEYBOARD.SYS"

PRINTER_DIR := $(DEV_DIR)/PRINTER

$(PRINTER_DIR)/PRINTER.CTL: $(PRINTER_DIR)/PRINTER.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(PRINTER_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" PRINTER.SKL

$(PRINTER_DIR)/CPSPM10.OBJ: $(PRINTER_DIR)/CPSPM10.ASM
	cd $(PRINTER_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "CPSPM10.ASM,CPSPM10.OBJ;"

$(PRINTER_DIR)/CPSFONT3.OBJ: $(PRINTER_DIR)/CPSFONT3.ASM
	cd $(PRINTER_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "CPSFONT3.ASM,CPSFONT3.OBJ;"

$(PRINTER_DIR)/PRTINT2F.OBJ: $(PRINTER_DIR)/PRTINT2F.ASM
	cd $(PRINTER_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "PRTINT2F.ASM,PRTINT2F.OBJ;"

$(PRINTER_DIR)/CPSPI07.OBJ: $(PRINTER_DIR)/CPSPI07.ASM $(PRINTER_DIR)/PRINTER.CTL
	cd $(PRINTER_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "CPSPI07.ASM,CPSPI07.OBJ;"

$(PRINTER_DIR)/PARSER.OBJ: $(PRINTER_DIR)/PARSER.ASM
	cd $(PRINTER_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "PARSER.ASM,PARSER.OBJ;"

$(PRINTER_DIR)/PRINTER.EXE: \
    $(PRINTER_DIR)/CPSPM10.OBJ $(PRINTER_DIR)/CPSFONT3.OBJ \
    $(PRINTER_DIR)/PRTINT2F.OBJ $(PRINTER_DIR)/CPSPI07.OBJ \
    $(PRINTER_DIR)/PARSER.OBJ
	cd $(PRINTER_DIR) && $(WLINK) "@PRINTER.LNK"

$(PRINTER_DIR)/PRINTER.SYS: $(PRINTER_DIR)/PRINTER.EXE
	cd $(PRINTER_DIR) && $(EXE2BIN) "PRINTER.EXE PRINTER.SYS" <ZERO.DAT

DISPLAY_DIR := $(DEV_DIR)/DISPLAY

$(DISPLAY_DIR)/DISPLAY.CTL: $(DISPLAY_DIR)/DISPLAY.SKL $(MESSAGES_OUT) $(BUILDMSG) $(MESSAGE_CATALOG)
	cd $(DISPLAY_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" DISPLAY.SKL

$(DISPLAY_DIR)/DISPLAY.OBJ: $(DISPLAY_DIR)/DISPLAY.ASM $(DISPLAY_DIR)/MACROS.INC
	cd $(DISPLAY_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "DISPLAY.ASM,DISPLAY.OBJ;"

$(DISPLAY_DIR)/INIT.OBJ: $(DISPLAY_DIR)/INIT.ASM $(DISPLAY_DIR)/DISPLAY.CTL
	cd $(DISPLAY_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "INIT.ASM,INIT.OBJ;"

$(DISPLAY_DIR)/PARSER.OBJ: $(DISPLAY_DIR)/PARSER.ASM
	cd $(DISPLAY_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "PARSER.ASM,PARSER.OBJ;"

$(DISPLAY_DIR)/DISPLAY.EXE: \
    $(DISPLAY_DIR)/DISPLAY.OBJ $(DISPLAY_DIR)/INIT.OBJ \
    $(DISPLAY_DIR)/PARSER.OBJ
	cd $(DISPLAY_DIR) && $(WLINK) "@DISPLAY.LNK"

$(DISPLAY_DIR)/DISPLAY.SYS: $(DISPLAY_DIR)/DISPLAY.EXE
	cd $(DISPLAY_DIR) && $(EXE2BIN) "DISPLAY.EXE DISPLAY.SYS" <ZERO.DAT

EGA_DIR  := $(DISPLAY_DIR)/EGA
EGA_AINC := -I. -I..\\..\\..\\INC

EGA_OBJS := \
    $(EGA_DIR)/CPI-HEAD.OBJ $(EGA_DIR)/437-CPI.OBJ $(EGA_DIR)/850-CPI.OBJ \
    $(EGA_DIR)/860-CPI.OBJ $(EGA_DIR)/863-CPI.OBJ $(EGA_DIR)/865-CPI.OBJ \
    $(EGA_DIR)/COPYRIGH.OBJ

$(EGA_DIR)/CPI-HEAD.OBJ: $(EGA_DIR)/CPI-HEAD.ASM
	cd $(EGA_DIR) && $(MASM) "$(AFLAGS) $(EGA_AINC)" "CPI-HEAD.ASM,CPI-HEAD.OBJ;"

$(EGA_DIR)/437-CPI.OBJ: $(EGA_DIR)/437-CPI.ASM $(EGA_DIR)/437-8X16.ASM $(EGA_DIR)/437-8X14.ASM $(EGA_DIR)/437-8X8.ASM
	cd $(EGA_DIR) && $(MASM) "$(AFLAGS) $(EGA_AINC)" "437-CPI.ASM,437-CPI.OBJ;"

$(EGA_DIR)/850-CPI.OBJ: $(EGA_DIR)/850-CPI.ASM $(EGA_DIR)/850-8X16.ASM $(EGA_DIR)/850-8X14.ASM $(EGA_DIR)/850-8X8.ASM
	cd $(EGA_DIR) && $(MASM) "$(AFLAGS) $(EGA_AINC)" "850-CPI.ASM,850-CPI.OBJ;"

$(EGA_DIR)/860-CPI.OBJ: $(EGA_DIR)/860-CPI.ASM $(EGA_DIR)/860-8X16.ASM $(EGA_DIR)/860-8X14.ASM $(EGA_DIR)/860-8X8.ASM
	cd $(EGA_DIR) && $(MASM) "$(AFLAGS) $(EGA_AINC)" "860-CPI.ASM,860-CPI.OBJ;"

$(EGA_DIR)/863-CPI.OBJ: $(EGA_DIR)/863-CPI.ASM $(EGA_DIR)/863-8X16.ASM $(EGA_DIR)/863-8X14.ASM $(EGA_DIR)/863-8X8.ASM
	cd $(EGA_DIR) && $(MASM) "$(AFLAGS) $(EGA_AINC)" "863-CPI.ASM,863-CPI.OBJ;"

$(EGA_DIR)/865-CPI.OBJ: $(EGA_DIR)/865-CPI.ASM $(EGA_DIR)/865-8X16.ASM $(EGA_DIR)/865-8X14.ASM $(EGA_DIR)/865-8X8.ASM
	cd $(EGA_DIR) && $(MASM) "$(AFLAGS) $(EGA_AINC)" "865-CPI.ASM,865-CPI.OBJ;"

$(EGA_DIR)/COPYRIGH.OBJ: $(EGA_DIR)/COPYRIGH.ASM
	cd $(EGA_DIR) && $(MASM) "$(AFLAGS) $(EGA_AINC)" "COPYRIGH.ASM,COPYRIGH.OBJ;"

$(EGA_DIR)/CPI-HEAD.EXE: $(EGA_OBJS)
	cd $(EGA_DIR) && $(WLINK) "@EGA.LNK"

$(EGA_DIR)/EGA.CPI: $(EGA_DIR)/CPI-HEAD.EXE
	cd $(EGA_DIR) && $(EXE2BIN) "CPI-HEAD.EXE EGA.CPI"

LCD_DIR  := $(DISPLAY_DIR)/LCD
LCD_AINC := -I. -I..\\..\\..\\INC
LCD_OBJS := \
    $(LCD_DIR)/FONT-R3.OBJ $(LCD_DIR)/437-CPI.OBJ $(LCD_DIR)/850-CPI.OBJ \
    $(LCD_DIR)/860-CPI.OBJ $(LCD_DIR)/863-CPI.OBJ $(LCD_DIR)/865-CPI.OBJ \
    $(LCD_DIR)/COPYRIGH.OBJ

$(LCD_DIR)/%.OBJ: $(LCD_DIR)/%.ASM
	cd $(LCD_DIR) && $(MASM) "$(AFLAGS) $(LCD_AINC)" "$*.ASM,$*.OBJ;"

$(LCD_DIR)/FONT-R3.EXE: $(LCD_OBJS)
	cd $(LCD_DIR) && $(WLINK) "@LCD.LNK"

$(LCD_DIR)/LCD.CPI: $(LCD_DIR)/FONT-R3.EXE
	cd $(LCD_DIR) && $(EXE2BIN) "FONT-R3.EXE LCD.CPI"

PRINTER_5202_DIR := $(DEV_DIR)/PRINTER/5202

$(PRINTER_5202_DIR)/5202.OBJ: $(PRINTER_5202_DIR)/5202.ASM
	cd $(PRINTER_5202_DIR) && $(MASM) "$(AFLAGS) -I. -I..\\..\\..\\INC" "5202.ASM,5202.OBJ;"

$(PRINTER_5202_DIR)/5202.EXE: $(PRINTER_5202_DIR)/5202.OBJ
	cd $(PRINTER_5202_DIR) && $(WLINK) "5202;"

$(PRINTER_5202_DIR)/5202.CPI: $(PRINTER_5202_DIR)/5202.EXE
	cd $(PRINTER_5202_DIR) && $(EXE2BIN) "5202.EXE 5202.CPI"

SMARTDRV_DIR := $(DEV_DIR)/SMARTDRV

$(SMARTDRV_DIR)/SMARTDRV.OBJ: $(SMARTDRV_DIR)/SMARTDRV.ASM
	cd $(SMARTDRV_DIR) && $(MASM) "$(AFLAGS) -I." "SMARTDRV.ASM,SMARTDRV.OBJ;"

$(SMARTDRV_DIR)/SMARTCTL.OBJ: $(SMARTDRV_DIR)/SMARTCTL.C
	cd $(SMARTDRV_DIR) && $(WCC) "-AS -Os -Zp -I. -I..\\..\\H -c -FoSMARTCTL.OBJ SMARTCTL.C"

$(SMARTDRV_DIR)/SMARTLOAD.OBJ: $(SMARTDRV_DIR)/SMARTLOAD.ASM
	cd $(SMARTDRV_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "SMARTLOAD.ASM,SMARTLOAD.OBJ;"

$(SMARTDRV_DIR)/SMARTDRV.EXE: $(SMARTDRV_DIR)/SMARTDRV.OBJ $(SMARTDRV_DIR)/SMARTCTL.OBJ $(SMARTDRV_DIR)/FL13.OBJ $(SMARTDRV_DIR)/SMARTLOAD.OBJ
	cd $(SMARTDRV_DIR) && $(WLINK) "SMARTDRV.OBJ+SMARTCTL.OBJ+FL13.OBJ+SMARTLOAD.OBJ,SMARTDRV.EXE,SMARTDRV.MAP,clibs.lib;"

$(SMARTDRV_DIR)/FLUSH13.OBJ: $(SMARTDRV_DIR)/FLUSH13.C
	cd $(SMARTDRV_DIR) && $(WCC) "-AS -Os -Zp -I. -I..\\..\\H -c -FoFLUSH13.OBJ FLUSH13.C"

$(SMARTDRV_DIR)/FL13.OBJ: $(SMARTDRV_DIR)/FL13.ASM
	cd $(SMARTDRV_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "FL13.ASM,FL13.OBJ;"

$(SMARTDRV_DIR)/FLMES.OBJ: $(SMARTDRV_DIR)/FLMES.ASM
	cd $(SMARTDRV_DIR) && $(MASM) "$(AFLAGS) -I. -ID:\\TOOLS\\INC -I..\\..\\INC" "FLMES.ASM,FLMES.OBJ;"

$(SMARTDRV_DIR)/FLUSH13.EXE: $(SMARTDRV_DIR)/FLUSH13.OBJ $(SMARTDRV_DIR)/FL13.OBJ $(SMARTDRV_DIR)/FLMES.OBJ
	cd $(SMARTDRV_DIR) && $(WLINK) "FLUSH13.OBJ+FL13.OBJ+FLMES.OBJ,FLUSH13.EXE,FLUSH13.MAP,clibs.lib;"

XMA2EMS_DIR := $(DEV_DIR)/XMA2EMS

$(XMA2EMS_DIR)/XMA2EMS.CL1: $(XMA2EMS_DIR)/XMA2EMS.SKL $(MESSAGES_OUT) $(NOSRVBLD) $(MESSAGE_CATALOG)
	cd $(XMA2EMS_DIR) && $(NOSRVBLD) XMA2EMS.SKL "..\\..\\MESSAGES\\USA-MS.MSG"

$(XMA2EMS_DIR)/XMA2EMS.OBJ: $(XMA2EMS_DIR)/XMA2EMS.ASM $(XMA2EMS_DIR)/XMA2EMS.CL1
	cd $(XMA2EMS_DIR) && $(MASM) "$(AFLAGS) -I. -I..\\..\\INC" "XMA2EMS.ASM,XMA2EMS.OBJ;"

$(XMA2EMS_DIR)/XMA2EMS.EXE: $(XMA2EMS_DIR)/XMA2EMS.OBJ
	cd $(XMA2EMS_DIR) && $(WLINK) "XMA2EMS;"

$(XMA2EMS_DIR)/XMA2EMS.SYS: $(XMA2EMS_DIR)/XMA2EMS.EXE
	cd $(XMA2EMS_DIR) && $(EXE2BIN) "XMA2EMS.EXE XMA2EMS.SYS"

XMAEM_DIR := $(DEV_DIR)/XMAEM

$(XMAEM_DIR)/XMAEM.CL1: $(XMAEM_DIR)/XMAEM.SKL $(MESSAGES_OUT) $(NOSRVBLD) $(MESSAGE_CATALOG)
	cd $(XMAEM_DIR) && $(NOSRVBLD) XMAEM.SKL "..\\..\\MESSAGES\\USA-MS.MSG"

$(XMAEM_DIR)/INDEINI.OBJ: $(XMAEM_DIR)/INDEINI.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEINI.ASM,INDEINI.OBJ;"

$(XMAEM_DIR)/INDEEMU.OBJ: $(XMAEM_DIR)/INDEEMU.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEEMU.ASM,INDEEMU.OBJ;"

$(XMAEM_DIR)/INDEEXC.OBJ: $(XMAEM_DIR)/INDEEXC.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEEXC.ASM,INDEEXC.OBJ;"

$(XMAEM_DIR)/INDEXMA.OBJ: $(XMAEM_DIR)/INDEXMA.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEXMA.ASM,INDEXMA.OBJ;"

$(XMAEM_DIR)/INDEDMA.OBJ: $(XMAEM_DIR)/INDEDMA.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEDMA.ASM,INDEDMA.OBJ;"

$(XMAEM_DIR)/INDEIDT.OBJ: $(XMAEM_DIR)/INDEIDT.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEIDT.ASM,INDEIDT.OBJ;"

$(XMAEM_DIR)/INDEGDT.OBJ: $(XMAEM_DIR)/INDEGDT.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEGDT.ASM,INDEGDT.OBJ;"

$(XMAEM_DIR)/INDEI15.OBJ: $(XMAEM_DIR)/INDEI15.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEI15.ASM,INDEI15.OBJ;"

$(XMAEM_DIR)/INDEMSG.OBJ: $(XMAEM_DIR)/INDEMSG.ASM $(XMAEM_DIR)/XMAEM.CL1
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEMSG.ASM,INDEMSG.OBJ;"

$(XMAEM_DIR)/INDEPAT.OBJ: $(XMAEM_DIR)/INDEPAT.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEPAT.ASM,INDEPAT.OBJ;"

$(XMAEM_DIR)/XMAEM.SYS: \
    $(XMAEM_DIR)/INDEINI.OBJ $(XMAEM_DIR)/INDEEXC.OBJ \
    $(XMAEM_DIR)/INDEEMU.OBJ $(XMAEM_DIR)/INDEXMA.OBJ \
    $(XMAEM_DIR)/INDEDMA.OBJ $(XMAEM_DIR)/INDEI15.OBJ \
    $(XMAEM_DIR)/INDEIDT.OBJ $(XMAEM_DIR)/INDEGDT.OBJ \
    $(XMAEM_DIR)/INDEMSG.OBJ $(XMAEM_DIR)/INDEPAT.OBJ
	cd $(XMAEM_DIR) && $(WLINK) "@XMAEM.LNK"
