# ---------------------------------------------------------------------------
# DEV (device drivers)
# Built sub-modules: DRIVER, ANSI, VDISK, COUNTRY, RAMDRIVE, KEYBOARD,
#                    PRINTER, DISPLAY, SMARTDRV, XMA2EMS, XMAEM
# Include path for all DEV sub-dirs (2 levels deep: DEV/SUBDIR/)
# ---------------------------------------------------------------------------
DEV_DIR  := $(SRC)/DEV
DEV_AINC := -I. -ID:\\TOOLS\\INC -I..\\..\\INC -I..\\..\\DOS

dev: \
    $(DEV_DIR)/DRIVER/DRIVER.SYS \
    $(DEV_DIR)/ANSI/ANSI.SYS \
    $(DEV_DIR)/VDISK/VDISK.SYS \
    $(DEV_DIR)/COUNTRY/COUNTRY.SYS \
    $(DEV_DIR)/RAMDRIVE/RAMDRIVE.SYS \
    $(DEV_DIR)/KEYBOARD/KEYBOARD.SYS \
    $(DEV_DIR)/PRINTER/PRINTER.SYS \
    $(DEV_DIR)/DISPLAY/DISPLAY.SYS \
    $(DEV_DIR)/SMARTDRV/SMARTDRV.SYS \
    $(DEV_DIR)/XMA2EMS/XMA2EMS.SYS \
    $(DEV_DIR)/XMAEM/XMAEM.SYS

# ---------------------------------------------------------------------------
# DEV/DRIVER
# ---------------------------------------------------------------------------
DRIVER_DIR := $(DEV_DIR)/DRIVER

$(DRIVER_DIR)/DRIVER.CTL: $(DRIVER_DIR)/DRIVER.SKL $(MESSAGES_OUT)
	cd $(DRIVER_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" DRIVER.SKL

$(DRIVER_DIR)/DRIVER.OBJ: $(DRIVER_DIR)/DRIVER.ASM $(DRIVER_DIR)/DRIVER.CTL
	cd $(DRIVER_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "DRIVER.ASM,DRIVER.OBJ;"

$(DRIVER_DIR)/DRIVER.EXE: $(DRIVER_DIR)/DRIVER.OBJ
	cd $(DRIVER_DIR) && $(LINK) "@DRIVER.LNK"

$(DRIVER_DIR)/DRIVER.SYS: $(DRIVER_DIR)/DRIVER.EXE
	cd $(DRIVER_DIR) && $(EXE2BIN) "DRIVER.EXE DRIVER.SYS"

# ---------------------------------------------------------------------------
# DEV/ANSI
# ---------------------------------------------------------------------------
ANSI_DIR := $(DEV_DIR)/ANSI

$(ANSI_DIR)/ANSI.CTL: $(ANSI_DIR)/ANSI.SKL $(MESSAGES_OUT)
	cd $(ANSI_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" ANSI.SKL

$(ANSI_DIR)/ANSI.OBJ: $(ANSI_DIR)/ANSI.ASM
	cd $(ANSI_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "ANSI.ASM,ANSI.OBJ;"

$(ANSI_DIR)/IOCTL.OBJ: $(ANSI_DIR)/IOCTL.ASM
	cd $(ANSI_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "IOCTL.ASM,IOCTL.OBJ;"

$(ANSI_DIR)/ANSIINIT.OBJ: $(ANSI_DIR)/ANSIINIT.ASM
	cd $(ANSI_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "ANSIINIT.ASM,ANSIINIT.OBJ;"

$(ANSI_DIR)/PARSER.OBJ: $(ANSI_DIR)/PARSER.ASM $(ANSI_DIR)/ANSI.CTL
	cd $(ANSI_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "PARSER.ASM,PARSER.OBJ;"

$(ANSI_DIR)/ANSI.EXE: \
    $(ANSI_DIR)/ANSI.OBJ $(ANSI_DIR)/IOCTL.OBJ \
    $(ANSI_DIR)/ANSIINIT.OBJ $(ANSI_DIR)/PARSER.OBJ
	cd $(ANSI_DIR) && $(LINK) "@ANSI.LNK"

$(ANSI_DIR)/ANSI.SYS: $(ANSI_DIR)/ANSI.EXE
	cd $(ANSI_DIR) && $(EXE2BIN) "ANSI.EXE ANSI.SYS"

# ---------------------------------------------------------------------------
# DEV/VDISK
# ---------------------------------------------------------------------------
VDISK_DIR := $(DEV_DIR)/VDISK

$(VDISK_DIR)/VDISK.CTL: $(VDISK_DIR)/VDISK.SKL $(MESSAGES_OUT)
	cd $(VDISK_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" VDISK.SKL

$(VDISK_DIR)/VDISKSYS.OBJ: $(VDISK_DIR)/VDISKSYS.ASM $(VDISK_DIR)/VDISK.CTL
	cd $(VDISK_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "VDISKSYS.ASM,VDISKSYS.OBJ;"

$(VDISK_DIR)/VDISK.EXE: $(VDISK_DIR)/VDISKSYS.OBJ
	cd $(VDISK_DIR) && $(LINK) "@VDISK.LNK"

$(VDISK_DIR)/VDISK.SYS: $(VDISK_DIR)/VDISK.EXE
	cd $(VDISK_DIR) && $(EXE2BIN) "VDISK.EXE VDISK.SYS"

# ---------------------------------------------------------------------------
# DEV/COUNTRY  (runs the built MKCNTRY.EXE tool to generate COUNTRY.SYS)
# ---------------------------------------------------------------------------
COUNTRY_DIR := $(DEV_DIR)/COUNTRY

$(COUNTRY_DIR)/MKCNTRY.OBJ: $(COUNTRY_DIR)/MKCNTRY.ASM
	cd $(COUNTRY_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "MKCNTRY.ASM,MKCNTRY.OBJ;"

$(COUNTRY_DIR)/MKCNTRY.EXE: $(COUNTRY_DIR)/MKCNTRY.OBJ
	cd $(COUNTRY_DIR) && $(LINK) "MKCNTRY;"

$(COUNTRY_DIR)/COUNTRY.SYS: $(COUNTRY_DIR)/MKCNTRY.EXE
	cd $(COUNTRY_DIR) && $(BIN)/dos-run $(COUNTRY_DIR)/MKCNTRY.EXE

# ---------------------------------------------------------------------------
# DEV/RAMDRIVE (uses -I../../inc forward-slash style; no DOS dir needed)
# ---------------------------------------------------------------------------
RAMDRIVE_DIR := $(DEV_DIR)/RAMDRIVE

$(RAMDRIVE_DIR)/RAMDRIVE.OBJ: $(RAMDRIVE_DIR)/RAMDRIVE.ASM
	cd $(RAMDRIVE_DIR) && $(MASM) "$(AFLAGS) -I. -I..\\..\\INC" "RAMDRIVE.ASM,RAMDRIVE.OBJ;"

$(RAMDRIVE_DIR)/MESSAGES.OBJ: $(RAMDRIVE_DIR)/MESSAGES.ASM
	cd $(RAMDRIVE_DIR) && $(MASM) "$(AFLAGS) -I. -I..\\..\\INC" "MESSAGES.ASM,MESSAGES.OBJ;"

$(RAMDRIVE_DIR)/RAMDRIVE.EXE: \
    $(RAMDRIVE_DIR)/RAMDRIVE.OBJ $(RAMDRIVE_DIR)/MESSAGES.OBJ
	cd $(RAMDRIVE_DIR) && $(LINK) "@RAMDRIVE.LNK"

$(RAMDRIVE_DIR)/RAMDRIVE.SYS: $(RAMDRIVE_DIR)/RAMDRIVE.EXE
	cd $(RAMDRIVE_DIR) && $(EXE2BIN) "RAMDRIVE.EXE RAMDRIVE.SYS"

# ---------------------------------------------------------------------------
# DEV/KEYBOARD (20 KDF files)
# ---------------------------------------------------------------------------
KEYBOARD_DIR := $(DEV_DIR)/KEYBOARD
KB_AINC := -I. -I..\\..\\INC

KEYBOARD_OBJS := KDFNOW.OBJ KDFFR120.OBJ KDFFR189.OBJ KDFEOF.OBJ \
    KDFUK166.OBJ KDFUK168.OBJ KDFIT141.OBJ KDFIT142.OBJ \
    KDFGE.OBJ KDFSP.OBJ KDFNL.OBJ KDFNO.OBJ KDFDK.OBJ \
    KDFSG.OBJ KDFSF.OBJ KDFPO.OBJ KDFBE.OBJ KDFCF.OBJ \
    KDFLA.OBJ KDFSV.OBJ

KEYBOARD_OBJ_PATHS := $(addprefix $(KEYBOARD_DIR)/,$(KEYBOARD_OBJS))

$(KEYBOARD_DIR)/%.OBJ: $(KEYBOARD_DIR)/%.ASM
	cd $(KEYBOARD_DIR) && $(MASM) "$(AFLAGS) $(KB_AINC)" "$*.ASM,$*.OBJ;"

$(KEYBOARD_DIR)/KEYBOARD.EXE: $(KEYBOARD_OBJ_PATHS)
	cd $(KEYBOARD_DIR) && $(LINK) "@KEYBOARD.LNK"

$(KEYBOARD_DIR)/KEYBOARD.SYS: $(KEYBOARD_DIR)/KEYBOARD.EXE
	cd $(KEYBOARD_DIR) && $(EXE2BIN) "KEYBOARD.EXE KEYBOARD.SYS"

# ---------------------------------------------------------------------------
# DEV/PRINTER (printer.sys; 5202.cpi subdir skipped)
# ---------------------------------------------------------------------------
PRINTER_DIR := $(DEV_DIR)/PRINTER

$(PRINTER_DIR)/PRINTER.CTL: $(PRINTER_DIR)/PRINTER.SKL $(MESSAGES_OUT)
	cd $(PRINTER_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" PRINTER.SKL

$(PRINTER_DIR)/CPSPM10.OBJ: $(PRINTER_DIR)/CPSPM10.ASM
	cd $(PRINTER_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "CPSPM10.ASM,CPSPM10.OBJ;"

$(PRINTER_DIR)/CPSFONT3.OBJ: $(PRINTER_DIR)/CPSFONT3.ASM
	cd $(PRINTER_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "CPSFONT3.ASM,CPSFONT3.OBJ;"

$(PRINTER_DIR)/PRTINT2F.OBJ: $(PRINTER_DIR)/PRTINT2F.ASM
	cd $(PRINTER_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "PRTINT2F.ASM,PRTINT2F.OBJ;"

$(PRINTER_DIR)/CPSPI07.OBJ: $(PRINTER_DIR)/CPSPI07.ASM $(PRINTER_DIR)/PRINTER.CTL
	cd $(PRINTER_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "CPSPI07.ASM,CPSPI07.OBJ;"

$(PRINTER_DIR)/PARSER.OBJ: $(PRINTER_DIR)/PARSER.ASM
	cd $(PRINTER_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "PARSER.ASM,PARSER.OBJ;"

$(PRINTER_DIR)/PRINTER.EXE: \
    $(PRINTER_DIR)/CPSPM10.OBJ $(PRINTER_DIR)/CPSFONT3.OBJ \
    $(PRINTER_DIR)/PRTINT2F.OBJ $(PRINTER_DIR)/CPSPI07.OBJ \
    $(PRINTER_DIR)/PARSER.OBJ
	cd $(PRINTER_DIR) && $(LINK) "@PRINTER.LNK"

$(PRINTER_DIR)/PRINTER.SYS: $(PRINTER_DIR)/PRINTER.EXE
	cd $(PRINTER_DIR) && $(EXE2BIN) "PRINTER.EXE PRINTER.SYS" <ZERO.DAT

# ---------------------------------------------------------------------------
# DEV/DISPLAY (display.sys; ega.cpi / lcd.cpi subdirs skipped)
# ---------------------------------------------------------------------------
DISPLAY_DIR := $(DEV_DIR)/DISPLAY

$(DISPLAY_DIR)/DISPLAY.CTL: $(DISPLAY_DIR)/DISPLAY.SKL $(MESSAGES_OUT)
	cd $(DISPLAY_DIR) && $(BUILDMSG) "..\\..\\MESSAGES\\USA-MS" DISPLAY.SKL

$(DISPLAY_DIR)/DISPLAY.OBJ: $(DISPLAY_DIR)/DISPLAY.ASM
	cd $(DISPLAY_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "DISPLAY.ASM,DISPLAY.OBJ;"

$(DISPLAY_DIR)/INIT.OBJ: $(DISPLAY_DIR)/INIT.ASM $(DISPLAY_DIR)/DISPLAY.CTL
	cd $(DISPLAY_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "INIT.ASM,INIT.OBJ;"

$(DISPLAY_DIR)/PARSER.OBJ: $(DISPLAY_DIR)/PARSER.ASM
	cd $(DISPLAY_DIR) && $(MASM) "$(AFLAGS) $(DEV_AINC)" "PARSER.ASM,PARSER.OBJ;"

$(DISPLAY_DIR)/DISPLAY.EXE: \
    $(DISPLAY_DIR)/DISPLAY.OBJ $(DISPLAY_DIR)/INIT.OBJ \
    $(DISPLAY_DIR)/PARSER.OBJ
	cd $(DISPLAY_DIR) && $(LINK) "@DISPLAY.LNK"

$(DISPLAY_DIR)/DISPLAY.SYS: $(DISPLAY_DIR)/DISPLAY.EXE
	cd $(DISPLAY_DIR) && $(EXE2BIN) "DISPLAY.EXE DISPLAY.SYS" <ZERO.DAT

# ---------------------------------------------------------------------------
# DEV/SMARTDRV
# ---------------------------------------------------------------------------
SMARTDRV_DIR := $(DEV_DIR)/SMARTDRV

$(SMARTDRV_DIR)/SMARTDRV.OBJ: $(SMARTDRV_DIR)/SMARTDRV.ASM
	cd $(SMARTDRV_DIR) && $(MASM) "$(AFLAGS) -I." "SMARTDRV.ASM,SMARTDRV.OBJ;"

$(SMARTDRV_DIR)/SMARTDRV.EXE: $(SMARTDRV_DIR)/SMARTDRV.OBJ
	cd $(SMARTDRV_DIR) && $(LINK) "SMARTDRV,,SMARTDRV/M;"

$(SMARTDRV_DIR)/SMARTDRV.SYS: $(SMARTDRV_DIR)/SMARTDRV.EXE
	cd $(SMARTDRV_DIR) && $(EXE2BIN) "SMARTDRV.EXE SMARTDRV.SYS"

# ---------------------------------------------------------------------------
# DEV/XMA2EMS
# ---------------------------------------------------------------------------
XMA2EMS_DIR := $(DEV_DIR)/XMA2EMS

$(XMA2EMS_DIR)/XMA2EMS.CL1: $(XMA2EMS_DIR)/XMA2EMS.SKL $(MESSAGES_OUT)
	cd $(XMA2EMS_DIR) && $(NOSRVBLD) XMA2EMS.SKL "..\\..\\MESSAGES\\USA-MS.MSG"

$(XMA2EMS_DIR)/XMA2EMS.OBJ: $(XMA2EMS_DIR)/XMA2EMS.ASM $(XMA2EMS_DIR)/XMA2EMS.CL1
	cd $(XMA2EMS_DIR) && $(MASM) "$(AFLAGS) -I. -I..\\..\\INC" "XMA2EMS.ASM,XMA2EMS.OBJ;"

$(XMA2EMS_DIR)/XMA2EMS.EXE: $(XMA2EMS_DIR)/XMA2EMS.OBJ
	cd $(XMA2EMS_DIR) && $(LINK) "XMA2EMS;"

$(XMA2EMS_DIR)/XMA2EMS.SYS: $(XMA2EMS_DIR)/XMA2EMS.EXE
	cd $(XMA2EMS_DIR) && $(EXE2BIN) "XMA2EMS.EXE XMA2EMS.SYS"

# ---------------------------------------------------------------------------
# DEV/XMAEM
# ---------------------------------------------------------------------------
XMAEM_DIR := $(DEV_DIR)/XMAEM

$(XMAEM_DIR)/XMAEM.CL1: $(XMAEM_DIR)/XMAEM.SKL $(MESSAGES_OUT)
	cd $(XMAEM_DIR) && $(NOSRVBLD) XMAEM.SKL "..\\..\\MESSAGES\\USA-MS.MSG"

$(XMAEM_DIR)/INDEINI.OBJ: $(XMAEM_DIR)/INDEINI.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEINI.ASM,INDEINI.OBJ;"

$(XMAEM_DIR)/INDEEMU.OBJ: $(XMAEM_DIR)/INDEEMU.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEEMU.ASM,INDEEMU.OBJ;"

$(XMAEM_DIR)/INDEEXC.OBJ: $(XMAEM_DIR)/INDEEXC.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEEXC.ASM,INDEEXC.OBJ;"

$(XMAEM_DIR)/INDEXMA.OBJ: $(XMAEM_DIR)/INDEXMA.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEXMA.ASM,INDEXMA.OBJ;"

$(XMAEM_DIR)/INDEDMA.OBJ: $(XMAEM_DIR)/INDEDMA.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEDMA.ASM,INDEDMA.OBJ;"

$(XMAEM_DIR)/INDEIDT.OBJ: $(XMAEM_DIR)/INDEIDT.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEIDT.ASM,INDEIDT.OBJ;"

$(XMAEM_DIR)/INDEGDT.OBJ: $(XMAEM_DIR)/INDEGDT.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEGDT.ASM,INDEGDT.OBJ;"

$(XMAEM_DIR)/INDEI15.OBJ: $(XMAEM_DIR)/INDEI15.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEI15.ASM,INDEI15.OBJ;"

$(XMAEM_DIR)/INDEMSG.OBJ: $(XMAEM_DIR)/INDEMSG.ASM $(XMAEM_DIR)/XMAEM.CL1
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEMSG.ASM,INDEMSG.OBJ;"

$(XMAEM_DIR)/INDEPAT.OBJ: $(XMAEM_DIR)/INDEPAT.ASM
	cd $(XMAEM_DIR) && $(MASM) "$(AFLAGS) -I." "INDEPAT.ASM,INDEPAT.OBJ;"

$(XMAEM_DIR)/XMAEM.SYS: \
    $(XMAEM_DIR)/INDEINI.OBJ $(XMAEM_DIR)/INDEEXC.OBJ \
    $(XMAEM_DIR)/INDEEMU.OBJ $(XMAEM_DIR)/INDEXMA.OBJ \
    $(XMAEM_DIR)/INDEDMA.OBJ $(XMAEM_DIR)/INDEI15.OBJ \
    $(XMAEM_DIR)/INDEIDT.OBJ $(XMAEM_DIR)/INDEGDT.OBJ \
    $(XMAEM_DIR)/INDEMSG.OBJ $(XMAEM_DIR)/INDEPAT.OBJ
	cd $(XMAEM_DIR) && $(LINK) "@XMAEM.LNK"
