MEMM_ROOT := $(SRC)/MEMM
EMM_DIR   := $(MEMM_ROOT)/EMM
MEMM_DIR  := $(MEMM_ROOT)/MEMM

memm: $(MEMM_DIR)/EMM386.EXE

EMM_AFLAGS := -Mx -t -DI386 -DNOHIMEM -I..\\MEMM
EMM_CFLAGS := -AS -2 -Os -Zp -zl -I. -c

$(EMM_DIR)/EMMFUNCT.OBJ: $(EMM_DIR)/EMMFUNCT.C
	cd $(EMM_DIR) && $(WCC) "$(EMM_CFLAGS) -FoEMMFUNCT.OBJ EMMFUNCT.C"

$(EMM_DIR)/EMM40.OBJ: $(EMM_DIR)/EMM40.C
	cd $(EMM_DIR) && $(WCC) "$(EMM_CFLAGS) -FoEMM40.OBJ EMM40.C"

$(EMM_DIR)/EMMP.OBJ: $(EMM_DIR)/EMMP.ASM
	cd $(EMM_DIR) && $(MASM) "$(EMM_AFLAGS)" "EMMP.ASM,EMMP.OBJ;"

$(EMM_DIR)/EMMSUP.OBJ: $(EMM_DIR)/EMMSUP.ASM
	cd $(EMM_DIR) && $(MASM) "$(EMM_AFLAGS)" "EMMSUP.ASM,EMMSUP.OBJ;"

$(EMM_DIR)/EMMDISP.OBJ: $(EMM_DIR)/EMMDISP.ASM
	cd $(EMM_DIR) && $(MASM) "$(EMM_AFLAGS)" "EMMDISP.ASM,EMMDISP.OBJ;"

$(EMM_DIR)/EMMDATA.OBJ: $(EMM_DIR)/EMMDATA.ASM
	cd $(EMM_DIR) && $(MASM) "$(EMM_AFLAGS)" "EMMDATA.ASM,EMMDATA.OBJ;"

$(EMM_DIR)/EMMINC.OBJ: $(EMM_DIR)/EMMINC.ASM
	cd $(EMM_DIR) && $(MASM) "$(EMM_AFLAGS)" "EMMINC.ASM,EMMINC.OBJ;"

$(EMM_DIR)/EMMLIB.LIB: \
    $(EMM_DIR)/EMMFUNCT.OBJ $(EMM_DIR)/EMM40.OBJ \
    $(EMM_DIR)/EMMP.OBJ $(EMM_DIR)/EMMSUP.OBJ \
    $(EMM_DIR)/EMMDISP.OBJ $(EMM_DIR)/EMMDATA.OBJ \
    $(EMM_DIR)/EMMINC.OBJ
	rm -f $(EMM_DIR)/EMMLIB.LIB
	cd $(EMM_DIR) && $(WLIB) "EMMLIB+EMMFUNCT.OBJ+EMM40.OBJ+EMMP.OBJ+EMMSUP.OBJ+EMMDISP.OBJ+EMMDATA.OBJ,;"

MEMM_AFLAGS := -Mx -t -DI386 -DNoBugMode -DNOHIMEM -I. -I..\\EMM
MEMM_CFLAGS := -AS -2 -Os -Zp -zl -I..\\EMM -c

$(MEMM_DIR)/%.OBJ: $(MEMM_DIR)/%.ASM
	cd $(MEMM_DIR) && $(MASM) "$(MEMM_AFLAGS)" "$*.ASM,$*.OBJ;"

$(MEMM_DIR)/MAPDMA.OBJ: $(MEMM_DIR)/MAPDMA.C
	cd $(MEMM_DIR) && $(WCC) "$(MEMM_CFLAGS) -FoMAPDMA.OBJ MAPDMA.C"

MEMM_OBJS := \
    $(MEMM_DIR)/MEMM386.OBJ $(MEMM_DIR)/ELIMFUNC.OBJ \
    $(MEMM_DIR)/EMM.OBJ $(MEMM_DIR)/EMMMES.OBJ \
    $(MEMM_DIR)/EMMINIT.OBJ $(MEMM_DIR)/MEMMONF.OBJ \
    $(MEMM_DIR)/INIT.OBJ $(MEMM_DIR)/M_STATE.OBJ \
    $(MEMM_DIR)/ROM_SRCH.OBJ $(MEMM_DIR)/PPAGE.OBJ \
    $(MEMM_DIR)/ALLOCMEM.OBJ $(MEMM_DIR)/INITTAB.OBJ \
    $(MEMM_DIR)/SHIPHI.OBJ $(MEMM_DIR)/EXTPOOL.OBJ \
    $(MEMM_DIR)/VDMINIT.OBJ $(MEMM_DIR)/I286.OBJ \
    $(MEMM_DIR)/I386.OBJ $(MEMM_DIR)/TABDEF.OBJ \
    $(MEMM_DIR)/TRAPDEF.OBJ $(MEMM_DIR)/VMTRAP.OBJ \
    $(MEMM_DIR)/VMINST.OBJ $(MEMM_DIR)/ELIMTRAP.OBJ \
    $(MEMM_DIR)/IOTRAP.OBJ $(MEMM_DIR)/A20TRAP.OBJ \
    $(MEMM_DIR)/OEMPROC.OBJ $(MEMM_DIR)/INITEPG.OBJ \
    $(MEMM_DIR)/VMINIT.OBJ $(MEMM_DIR)/EM286LL.OBJ \
    $(MEMM_DIR)/EM386LL.OBJ $(MEMM_DIR)/MOVEB.OBJ \
    $(MEMM_DIR)/MAPLIN.OBJ $(MEMM_DIR)/RETREAL.OBJ \
    $(MEMM_DIR)/RRTRAP.OBJ $(MEMM_DIR)/ERRHNDLR.OBJ \
    $(MEMM_DIR)/EKBD.OBJ $(MEMM_DIR)/UTIL.OBJ \
    $(MEMM_DIR)/INITDEB.OBJ $(MEMM_DIR)/MAPDMA.OBJ

$(MEMM_DIR)/EMM386.EXE: $(MEMM_OBJS) $(EMM_DIR)/EMMLIB.LIB $(MEMM_DIR)/EMM386.LNK
	cd $(MEMM_DIR) && $(WLINK) "/NOI /PACKDATA:1 @EMM386.LNK"
