# ---------------------------------------------------------------------------
# SELECT (select.exe, select.dat, select.com, select.hlp)
# SELECT is 1 level deep (SRC/SELECT/), so .. paths work directly.
# ---------------------------------------------------------------------------
SELECT_DIR  := $(SRC)/SELECT
FDISK_DIR   := $(SRC)/CMD/FDISK
TOOLS_DIR   := $(SRC)/TOOLS

# Include paths: local dir + SRC/INC (one level up)
SELECT_AINC := -I. -I..\\INC

select: \
    $(SELECT_DIR)/SELECT.COM \
    $(SELECT_DIR)/SELECT.HLP \
    $(SELECT_DIR)/SELECT.EXE \
    $(SELECT_DIR)/SELECT.DAT

# ---------------------------------------------------------------------------
# SELECT.CTL + CL files (BUILDMSG — SELECT.SKL has :util header)
# ---------------------------------------------------------------------------
$(SELECT_DIR)/SELECT.CTL: $(SELECT_DIR)/SELECT.SKL $(MESSAGES_OUT)
	cd $(SELECT_DIR) && $(BUILDMSG) "..\\MESSAGES\\USA-MS" SELECT.SKL

# CL side-effects of the same BUILDMSG run
$(SELECT_DIR)/SELECT.CLA: $(SELECT_DIR)/SELECT.CTL

# ---------------------------------------------------------------------------
# SELECT.COM  (simplest output: sstub.asm → link → exe2bin)
# ---------------------------------------------------------------------------
$(SELECT_DIR)/SSTUB.OBJ: $(SELECT_DIR)/SSTUB.ASM $(SELECT_DIR)/SELECT.CTL
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SSTUB.ASM,SSTUB.OBJ;"

$(SELECT_DIR)/SSTUB.EXE: $(SELECT_DIR)/SSTUB.OBJ
	cd $(SELECT_DIR) && $(LINK) "SSTUB;"

$(SELECT_DIR)/SELECT.COM: $(SELECT_DIR)/SSTUB.EXE
	cd $(SELECT_DIR) && $(EXE2BIN) "SSTUB.EXE SELECT.COM"

# ---------------------------------------------------------------------------
# SELECT.HLP  (ASC2HLP.EXE is a pre-built tool in TOOLS/)
# ---------------------------------------------------------------------------
$(SELECT_DIR)/SELECT.HLP: $(SELECT_DIR)/USA.TXT
	cd $(SELECT_DIR) && $(BIN)/dos-run $(TOOLS_DIR)/ASC2HLP.EXE USA.TXT SELECT.HLP

# ---------------------------------------------------------------------------
# FDBOOT.INC dependency chain (needed for BOOTREC.OBJ → SELECT.EXE)
# ---------------------------------------------------------------------------

# Step 1: FDISK5.CL1 (class 1 SKL → NOSRVBLD)
$(FDISK_DIR)/FDISK5.CL1: $(FDISK_DIR)/FDISK5.SKL $(MESSAGES_OUT)
	cd $(FDISK_DIR) && $(NOSRVBLD) FDISK5.SKL "..\\..\\MESSAGES\\USA-MS.MSG"

# Step 2: FDBOOT.OBJ
$(FDISK_DIR)/FDBOOT.OBJ: $(FDISK_DIR)/FDBOOT.ASM $(FDISK_DIR)/FDISK5.CL1
	cd $(FDISK_DIR) && $(MASM) "$(AFLAGS) -I." "FDBOOT.ASM,FDBOOT.OBJ;"

# Step 3: FDBOOT.EXE
$(FDISK_DIR)/FDBOOT.EXE: $(FDISK_DIR)/FDBOOT.OBJ
	cd $(FDISK_DIR) && $(LINK) "FDBOOT;"

# Step 4: FDBOOT.BIN
$(FDISK_DIR)/FDBOOT.BIN: $(FDISK_DIR)/FDBOOT.EXE
	cd $(FDISK_DIR) && $(EXE2BIN) "FDBOOT.EXE FDBOOT.BIN"

# Step 5: FDBOOT.INC via DBOF
$(FDISK_DIR)/FDBOOT.INC: $(FDISK_DIR)/FDBOOT.BIN
	cd $(FDISK_DIR) && $(DBOF) "FDBOOT.BIN FDBOOT.INC 600 200"

# Step 6: BOOTREC.OBJ (assembled in FDISK dir where FDBOOT.INC lives)
$(FDISK_DIR)/BOOTREC.OBJ: $(FDISK_DIR)/BOOTREC.ASM $(FDISK_DIR)/FDBOOT.INC
	cd $(FDISK_DIR) && $(MASM) "$(AFLAGS) -I." "BOOTREC.ASM,BOOTREC.OBJ;"

# Step 7: Copy BOOTREC.OBJ to SELECT dir (SELECT.LNK expects it locally)
$(SELECT_DIR)/BOOTREC.OBJ: $(FDISK_DIR)/BOOTREC.OBJ
	cp $(FDISK_DIR)/BOOTREC.OBJ $(SELECT_DIR)/BOOTREC.OBJ

# ---------------------------------------------------------------------------
# SERVICES.LIB objects
# ---------------------------------------------------------------------------
$(SELECT_DIR)/SELQUIT.OBJ: $(SELECT_DIR)/SELQUIT.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SELQUIT.ASM,SELQUIT.OBJ;"

$(SELECT_DIR)/SELCHILD.OBJ: $(SELECT_DIR)/SELCHILD.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SELCHILD.ASM,SELCHILD.OBJ;"

$(SELECT_DIR)/SERVICES.OBJ: $(SELECT_DIR)/SERVICES.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SERVICES.ASM,SERVICES.OBJ;"

$(SELECT_DIR)/GET_HELP.OBJ: $(SELECT_DIR)/GET_HELP.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "GET_HELP.ASM,GET_HELP.OBJ;"

$(SELECT_DIR)/SELSERV.OBJ: $(SELECT_DIR)/SELSERV.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SELSERV.ASM,SELSERV.OBJ;"

$(SELECT_DIR)/SERVICES.LIB: \
    $(SELECT_DIR)/SELQUIT.OBJ $(SELECT_DIR)/SELCHILD.OBJ \
    $(SELECT_DIR)/SERVICES.OBJ $(SELECT_DIR)/GET_HELP.OBJ \
    $(SELECT_DIR)/SELSERV.OBJ
	rm -f $(SELECT_DIR)/SERVICES.LIB
	cd $(SELECT_DIR) && $(LIB) "SERVICES.LIB -+ SELQUIT;"
	cd $(SELECT_DIR) && $(LIB) "SERVICES.LIB -+ SELCHILD;"
	cd $(SELECT_DIR) && $(LIB) "SERVICES.LIB -+ SERVICES;"
	cd $(SELECT_DIR) && $(LIB) "SERVICES.LIB -+ GET_HELP;"
	cd $(SELECT_DIR) && $(LIB) "SERVICES.LIB -+ SELSERV;"

# ---------------------------------------------------------------------------
# SELECT.EXE main objects (ASM)
# ---------------------------------------------------------------------------
$(SELECT_DIR)/SELECT0.OBJ: $(SELECT_DIR)/SELECT0.ASM $(SELECT_DIR)/SELECT.CTL
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SELECT0.ASM,SELECT0.OBJ;"

$(SELECT_DIR)/SELECT1.OBJ: $(SELECT_DIR)/SELECT1.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SELECT1.ASM,SELECT1.OBJ;"

$(SELECT_DIR)/SELECT2.OBJ: $(SELECT_DIR)/SELECT2.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SELECT2.ASM,SELECT2.OBJ;"

$(SELECT_DIR)/SELECT2A.OBJ: $(SELECT_DIR)/SELECT2A.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SELECT2A.ASM,SELECT2A.OBJ;"

$(SELECT_DIR)/SELECT3.OBJ: $(SELECT_DIR)/SELECT3.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SELECT3.ASM,SELECT3.OBJ;"

$(SELECT_DIR)/SELECT4.OBJ: $(SELECT_DIR)/SELECT4.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SELECT4.ASM,SELECT4.OBJ;"

$(SELECT_DIR)/SELECT5.OBJ: $(SELECT_DIR)/SELECT5.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SELECT5.ASM,SELECT5.OBJ;"

$(SELECT_DIR)/SELECT5A.OBJ: $(SELECT_DIR)/SELECT5A.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SELECT5A.ASM,SELECT5A.OBJ;"

$(SELECT_DIR)/SELECT6.OBJ: $(SELECT_DIR)/SELECT6.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SELECT6.ASM,SELECT6.OBJ;"

$(SELECT_DIR)/SELECT7.OBJ: $(SELECT_DIR)/SELECT7.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SELECT7.ASM,SELECT7.OBJ;"

$(SELECT_DIR)/SELECT8.OBJ: $(SELECT_DIR)/SELECT8.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SELECT8.ASM,SELECT8.OBJ;"

$(SELECT_DIR)/SELECT9.OBJ: $(SELECT_DIR)/SELECT9.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SELECT9.ASM,SELECT9.OBJ;"

$(SELECT_DIR)/GEN_COMS.OBJ: $(SELECT_DIR)/GEN_COMS.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "GEN_COMS.ASM,GEN_COMS.OBJ;"

$(SELECT_DIR)/MPARSE.OBJ: $(SELECT_DIR)/MPARSE.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "MPARSE.ASM,MPARSE.OBJ;"

$(SELECT_DIR)/INITMEM.OBJ: $(SELECT_DIR)/INITMEM.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "INITMEM.ASM,INITMEM.OBJ;"

$(SELECT_DIR)/INPUT.OBJ: $(SELECT_DIR)/INPUT.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "INPUT.ASM,INPUT.OBJ;"

$(SELECT_DIR)/ROUTINES.OBJ: $(SELECT_DIR)/ROUTINES.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "ROUTINES.ASM,ROUTINES.OBJ;"

$(SELECT_DIR)/ROUTINE2.OBJ: $(SELECT_DIR)/ROUTINE2.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "ROUTINE2.ASM,ROUTINE2.OBJ;"

$(SELECT_DIR)/VAR.OBJ: $(SELECT_DIR)/VAR.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "VAR.ASM,VAR.OBJ;"

$(SELECT_DIR)/PRN_DEF.OBJ: $(SELECT_DIR)/PRN_DEF.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "PRN_DEF.ASM,PRN_DEF.OBJ;"

$(SELECT_DIR)/SCN_PARM.OBJ: $(SELECT_DIR)/SCN_PARM.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SCN_PARM.ASM,SCN_PARM.OBJ;"

$(SELECT_DIR)/S_DISPLY.OBJ: $(SELECT_DIR)/S_DISPLY.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "S_DISPLY.ASM,S_DISPLY.OBJ;"

$(SELECT_DIR)/MOD_COPY.OBJ: $(SELECT_DIR)/MOD_COPY.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "MOD_COPY.ASM,MOD_COPY.OBJ;"

$(SELECT_DIR)/BRIDGE.OBJ: $(SELECT_DIR)/BRIDGE.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "BRIDGE.ASM,BRIDGE.OBJ;"

$(SELECT_DIR)/CASERVIC.OBJ: $(SELECT_DIR)/CASERVIC.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "CASERVIC.ASM,CASERVIC.OBJ;"

$(SELECT_DIR)/CKDISP.OBJ: $(SELECT_DIR)/CKDISP.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "CKDISP.ASM,CKDISP.OBJ;"

$(SELECT_DIR)/INTVEC.OBJ: $(SELECT_DIR)/INTVEC.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "INTVEC.ASM,INTVEC.OBJ;"

$(SELECT_DIR)/ASM2C.OBJ: $(SELECT_DIR)/ASM2C.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "ASM2C.ASM,ASM2C.OBJ;"

# ---------------------------------------------------------------------------
# SELECT.EXE C objects
# ---------------------------------------------------------------------------
$(SELECT_DIR)/GET_STAT.OBJ: $(SELECT_DIR)/GET_STAT.C
	cd $(SELECT_DIR) && $(CL) "-AS -Od -Zp -I. -c -FoGET_STAT.OBJ GET_STAT.C"

$(SELECT_DIR)/INT13.OBJ: $(SELECT_DIR)/INT13.C
	cd $(SELECT_DIR) && $(CL) "-AS -Od -Zp -I. -c -FoINT13.OBJ INT13.C"

$(SELECT_DIR)/GLOBAL.OBJ: $(SELECT_DIR)/GLOBAL.C
	cd $(SELECT_DIR) && $(CL) "-AS -Od -Zp -I. -c -FoGLOBAL.OBJ GLOBAL.C"

# ---------------------------------------------------------------------------
# SELECT.EXE link
# ---------------------------------------------------------------------------
SELECT_OBJS := \
    $(SELECT_DIR)/SELECT0.OBJ $(SELECT_DIR)/SELECT1.OBJ \
    $(SELECT_DIR)/SELECT2.OBJ $(SELECT_DIR)/SELECT2A.OBJ \
    $(SELECT_DIR)/SELECT3.OBJ $(SELECT_DIR)/SELECT4.OBJ \
    $(SELECT_DIR)/SELECT5.OBJ $(SELECT_DIR)/SELECT5A.OBJ \
    $(SELECT_DIR)/SELECT6.OBJ $(SELECT_DIR)/SELECT7.OBJ \
    $(SELECT_DIR)/SELECT8.OBJ $(SELECT_DIR)/SELECT9.OBJ \
    $(SELECT_DIR)/ROUTINE2.OBJ $(SELECT_DIR)/GEN_COMS.OBJ \
    $(SELECT_DIR)/ROUTINES.OBJ $(SELECT_DIR)/INTVEC.OBJ \
    $(SELECT_DIR)/CKDISP.OBJ $(SELECT_DIR)/SCN_PARM.OBJ \
    $(SELECT_DIR)/PRN_DEF.OBJ $(SELECT_DIR)/VAR.OBJ \
    $(SELECT_DIR)/CASERVIC.OBJ $(SELECT_DIR)/INPUT.OBJ \
    $(SELECT_DIR)/INITMEM.OBJ $(SELECT_DIR)/MPARSE.OBJ \
    $(SELECT_DIR)/MOD_COPY.OBJ $(SELECT_DIR)/S_DISPLY.OBJ \
    $(SELECT_DIR)/BRIDGE.OBJ $(SELECT_DIR)/ASM2C.OBJ \
    $(SELECT_DIR)/GET_STAT.OBJ $(SELECT_DIR)/GLOBAL.OBJ \
    $(SELECT_DIR)/INT13.OBJ $(SELECT_DIR)/BOOTREC.OBJ \
    $(SELECT_DIR)/SERVICES.LIB

$(SELECT_DIR)/SELECT.EXE: $(SELECT_OBJS)
	cd $(SELECT_DIR) && $(LINK) "/noe @SELECT.LNK"
	$(BIN)/fix-exepack $(SELECT_DIR)/SELECT.EXE

# ---------------------------------------------------------------------------
# SELECT.DAT  (SEL-PAN objects → link → exe2bin → compress)
# ---------------------------------------------------------------------------
$(SELECT_DIR)/PANEL.INF: $(SELECT_DIR)/USA.INF
	cp $(SELECT_DIR)/USA.INF $(SELECT_DIR)/PANEL.INF

$(SELECT_DIR)/PANELS.OBJ: $(SELECT_DIR)/PANELS.ASM $(SELECT_DIR)/PANEL.INF
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) -I." "PANELS.ASM,PANELS.OBJ;"

$(SELECT_DIR)/COLORS.OBJ: $(SELECT_DIR)/COLORS.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) -I." "COLORS.ASM,COLORS.OBJ;"

$(SELECT_DIR)/SCROLL.OBJ: $(SELECT_DIR)/SCROLL.ASM $(SELECT_DIR)/PANEL.INF
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) -I." "SCROLL.ASM,SCROLL.OBJ;"

$(SELECT_DIR)/SEL-PAN.OBJ: $(SELECT_DIR)/SEL-PAN.ASM
	cd $(SELECT_DIR) && $(MASM) "$(AFLAGS) $(SELECT_AINC)" "SEL-PAN.ASM,SEL-PAN.OBJ;"

$(SELECT_DIR)/SEL-PAN.EXE: \
    $(SELECT_DIR)/SEL-PAN.OBJ $(SELECT_DIR)/PANELS.OBJ \
    $(SELECT_DIR)/COLORS.OBJ $(SELECT_DIR)/SCROLL.OBJ
	cd $(SELECT_DIR) && $(LINK) "@SEL-PAN.LNK"

$(SELECT_DIR)/SEL-PAN.DAT: $(SELECT_DIR)/SEL-PAN.EXE
	cd $(SELECT_DIR) && $(EXE2BIN) "SEL-PAN.EXE SEL-PAN.DAT"

$(SELECT_DIR)/SELECT.DAT: $(SELECT_DIR)/SEL-PAN.DAT
	cd $(SELECT_DIR) && $(BIN)/dos-run $(TOOLS_DIR)/COMPRESS.COM
