
    #include <stdlib.h>     /* Declaration & init of DOS _osmajor & _osminor */

    #define  expected_version_major	6	/* DOS Major Version 6 */
    #define  expected_version_minor	22	/* DOS Minor Version 22 */

       /********************************************/
       /*Each C program should: 		   */
       /*					   */
       /* if ((expected_version_major != _osmajor) */
       /*   | (expected_version_minor != _osminor))*/
       /*  exit(incorrect_dos_version); 	   */
       /*					   */
       /********************************************/
