.8086
option oldstructs
.model tiny
.code
org 0
include MSBDS.INC
dw SIZE BDS_TYPE, BYTEPERSEC, SECPERCLUS, RESSEC, CFAT, CDIR, DRVLIM
dw MEDIAD, CSECFAT, SECLIM, HDLIM, HIDSEC_L, HIDSEC_H, DRVLIM_H
dw FLAGS, FORMFACTOR, FCHANGELINE, FF96TPI
end
