; ScanDisk configuration. Environment settings apply to every run.
[Environment]
Display=Auto
Mouse=On
ScanTimeOut=Off
NumPasses=1
LabelCheck=Off
LfnCheck=On

; These settings apply when SCANDISK is started with /CUSTOM.
[Custom]
DriveSummary=Auto
AllSummary=Auto
Surface=Never
CheckHost=Never
SaveLog=Off
Undo=Prompt
DS_Header=Prompt
FAT_Media=Prompt
Okay_Entries=Prompt
Bad_Chain=Prompt
Crosslinks=Prompt
Boot_Sector=Prompt
Invalid_MDFAT=Prompt
DS_Crosslinks=Prompt
DS_LostClust=Prompt
DS_Signatures=Prompt
Mismatch_FAT=Prompt
Bad_Clusters=Prompt
Bad_Entries=Prompt
LostClust=Prompt
