#!/usr/bin/env python3
"""Emit Baltic KEYB macro tables from the selected input contract.

The independent KEY reference capture remains in capture_baltic_keyboard.py.
This generator implements the existing Microsoft-format state/table ABI.
"""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCALE = ROOT / "locales/baltic"
OUTPUT = ROOT / "src/DEV/KEYBOARD/KDFBALT.ASM"
FLAGS = ["ACUTE", "GRAVE", "DIARESIS", "CIRCUMFLEX", "CEDILLA"]


def effective(profile, mode, include_bios=False):
    # normal, shift, caps, shift+caps, AltGr, Shift+AltGr, Ctrl, Alt
    physical = {}
    if include_bios and mode < 4:
        upper = mode in (1, 2)
        for first, letters in ((16, "qwertyuiop"), (30, "asdfghjkl"), (44, "zxcvbnm")):
            for scan, char in enumerate(letters, first):
                physical[scan] = {"kind": "character", "byte": ord(char.upper() if upper else char), "scan": scan}
        physical[57] = {"kind": "character", "byte": 32, "scan": 57}
    for key, row in profile["keys"].items():
        if mode < 4:
            plane = mode & 1
            # Capture flags are per selected table cell. The selected profiles
            # use the same Caps behavior for both normal/Shift effects.
            marked = any(item and item["caps"] for item in row[:2])
            if mode in (2, 3) and marked:
                plane ^= 1
        else:
            name = {4: "AltGr | Shift", 5: "Shift AltGr", 6: "Ctrl", 7: "Alt"}[mode]
            if name not in profile["planes"]:
                continue
            plane = profile["planes"].index(name)
        item = row[plane]
        if item:
            physical[int(key)] = item
    return physical


def generate():
    profiles = json.loads((LOCALE / "review/keyboard-expectations.json").read_text())["profiles"]
    lines = ["; Generated by tools/build_baltic_keyboard.py; do not hand-edit.",
             "; Baltic CP775 extension plus unchanged Russian translation logic.",
             "INCLUDE KEYBSHAR.INC", "INCLUDE POSTEQU.INC", "INCLUDE KEYBMAC.INC",
             "CODE SEGMENT PUBLIC 'CODE'", "ASSUME CS:CODE,DS:CODE",
             "DB 0FFh,'KEYB   ',8 DUP(0)", "DW BALT_COMMON_MAX,BALT_SPEC_MAX,BALT_LOGIC_MAX",
             "DW 0,5,5"]
    entries = [("RU", 441, "RU", 866), ("ET", 454, "ET", 775),
               ("EE", 454, "ET", 775), ("LV", 0, "LV", 775), ("LT", 221, "LT", 775)]
    for code, number, target, page in entries:
        lines += [f"DB '{code}'", f"DW OFFSET {code}_ENTRY,0"]
    for code, number, target, page in entries:
        lines += [f"DW {number},OFFSET {code}_ENTRY,0"]
    # ID lookup begins at the first 454 entry and walks its declared group.
    # Include the following EE alias so an explicit EE /ID:454 can match.
    for code, number, target, page in entries:
        lines += [f"{code}_ENTRY:", f"DB '{code}'", f"DW {number},OFFSET {target}_LOGIC,0",
                  "DB 2,1" if code == "ET" else "DB 1,1", f"DW {page},OFFSET {target}_PAGE,0"]
    lines += ["INCLUDE KDFRUTAB.INC"]

    for language, profile in profiles.items():
        tag = language.upper()
        tables = []
        def table(rows, flag=False, literal=None):
            number = len(tables) + 1
            tables.append((number, rows, flag, literal))
            return number
        normal = []
        for mode in range(8):
            data = effective(profile, mode)
            dead = {scan: FLAGS[item["id"] - 1] for scan, item in data.items() if item["kind"] == "dead"}
            chars = {scan: (item["byte"], 0 if item["byte"] == 224 else item["scan"]) for scan, item in data.items() if item["kind"] == "character"}
            normal.append((table(dead, flag=True) if dead else None, table(chars) if chars else None))
        compositions = []
        for key, dead in profile["dead_keys"].items():
            modes = []
            for mode in range(8):
                rows = {}
                for scan, item in effective(profile, mode, include_bios=True).items():
                    if item["kind"] == "character" and str(item["byte"]) in dead["pairs"]:
                        rows[scan] = (dead["pairs"][str(item["byte"])], 0 if item["byte"] == 32 or dead["pairs"][str(item["byte"])] == 224 else item["scan"])
                modes.append(table(rows) if rows else None)
            error = table({}, literal=dead["literal"])
            compositions.append((FLAGS[int(key) - 1], modes, error))

        # Explicit selection tree, shared for normal and composition states.
        def dispatch(callback):
            def third():
                lines.append("IFF EITHER_SHIFT"); callback(5)
                lines.append("ELSEF"); callback(4); lines.append("ENDIFF")
            lines.append("IFF R_ALT_SHIFT"); third(); lines.append("ELSEF")
            lines.append("IFF EITHER_ALT")
            lines.append("IFF EITHER_CTL"); third(); lines.append("ELSEF")
            callback(7); lines.append("ENDIFF"); lines.append("ELSEF")
            lines.append("IFF EITHER_CTL"); callback(6); lines.append("ELSEF")
            lines.append("IFF EITHER_SHIFT")
            lines.append("IFF CAPS_STATE"); callback(3); lines.append("ELSEF"); callback(1); lines.append("ENDIFF")
            lines.append("ELSEF")
            lines.append("IFF CAPS_STATE"); callback(2); lines.append("ELSEF"); callback(0); lines.append("ENDIFF")
            lines.extend(["ENDIFF"] * 4)

        lines += [f"{tag}_LOGIC:", f"DW {tag}_LOGIC_END-$", "DW 0", "OPTION EXIT_IF_FOUND"]
        for flag, modes, error in compositions:
            lines += [f"IFF {flag}", "RESET_NLS"]
            dispatch(lambda mode: lines.append(f"XLATT {modes[mode]}") if modes[mode] else None)
            lines += [f"PUT_ERROR_CHAR {error}", "ENDIFF"]
        def normal_commands(mode):
            flag, chars = normal[mode]
            if flag:
                lines.append(f"SET_FLAG {flag}")
            if chars:
                lines.append(f"XLATT {chars}")
        dispatch(normal_commands)
        lines += ["EXIT_STATE_LOGIC", f"{tag}_LOGIC_END:"]
        for section, selected in (
                ("COMMON", [item for item in tables if item[2]]),
                ("PAGE", [item for item in tables if not item[2]])):
            lines += [f"{tag}_{section}:", f"DW {tag}_{section}_END-$",
                      "DW -1" if section == "COMMON" else "DW 775"]
            for number, rows, flag, literal in selected:
                label = f"{tag}_STATE_{number}"
                lines += [f"{label}:", f"DW {label}_END-$", f"DB {number}", "DW ANY_KB",
                          "DB -1,-1" if literal is None else f"DB {literal},0"]
                if flag:
                    lines.append(f"DW {len(rows)}")
                    for scan, name in sorted(rows.items()):
                        lines += [f"DB {scan}", f"FLAG {name}"]
                elif rows:
                    lines += [f"DW {label}_TABLE_END-$", "DB TYPE_2_TAB+LITERAL_FF" if any(byte == 255 for byte, _ in rows.values()) else "DB TYPE_2_TAB", f"DB {len(rows)}"]
                    for scan, (byte, output_scan) in sorted(rows.items()):
                        lines.append(f"DB {scan},{byte},{output_scan}")
                    lines += [f"{label}_TABLE_END:", "DW 0"]
                else:
                    lines.append("DW 0")
                lines.append(f"{label}_END:")
            lines += ["DW 0", f"{tag}_{section}_END:"]
    # Keep enough room to reload the existing KEYBOARD.SYS profiles as well.
    lines += ["BALT_COMMON_MAX = 1120", "BALT_SPEC_MAX = 496", "BALT_LOGIC_MAX = 640"]
    for tag in ("ET", "LV", "LT"):
        for name, expr in (("BALT_COMMON_MAX", f"{tag}_COMMON_END-{tag}_COMMON"),
                           ("BALT_SPEC_MAX", f"{tag}_PAGE_END-{tag}_PAGE"),
                           ("BALT_LOGIC_MAX", f"{tag}_LOGIC_END-{tag}_LOGIC")):
            lines += [f"IF {expr} GT {name}", f"{name} = {expr}", "ENDIF"]
    lines += ["CODE ENDS", "END"]
    return ("\n".join(lines) + "\n").encode("ascii")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = generate()
    if args.check:
        if OUTPUT.read_bytes() != data:
            raise SystemExit("stale Baltic KEYB macro tables")
    else:
        OUTPUT.write_bytes(data)


if __name__ == "__main__":
    main()
